const charactersPart2 = [
  // ───────────────── 🧑 Human & Social ─────────────────
  // 人/亻 radical (continued)
  { char:"人", pinyin:"ren2", radical:"人", components:[], meaning:"person", emoji:"🧑", gifDuration:1, sentence:"人人平等。" },
  { char:"你", pinyin:"ni3", radical:"亻", components:["亻","尔"], meaning:"you", emoji:"👉", gifDuration:1.2, sentence:"你好吗？" },
  { char:"他", pinyin:"ta1", radical:"亻", components:["亻","也"], meaning:"he", emoji:"👨", gifDuration:1.2, sentence:"他是学生。" },
  { char:"们", pinyin:"men5", radical:"亻", components:["亻","门"], meaning:"plural", emoji:"👥", gifDuration:1.2, sentence:"我们一起去。" },
  { char:"休", pinyin:"xiu1", radical:"亻", components:["亻","木"], meaning:"rest", emoji:"😴", gifDuration:1.2, sentence:"休息一下。" },
  { char:"作", pinyin:"zuo4", radical:"亻", components:["亻","乍"], meaning:"do", emoji:"🏋️", gifDuration:1.2, sentence:"工作努力。" },
  { char:"信", pinyin:"xin4", radical:"亻", components:["亻","言"], meaning:"trust", emoji:"✉️", gifDuration:1.2, sentence:"我相信你。" },
  { char:"传", pinyin:"chuan2", radical:"亻", components:["亻","专"], meaning:"transmit", emoji:"📡", gifDuration:1.2, sentence:"传说很美。" },
  { char:"何", pinyin:"he2", radical:"亻", components:["亻","可"], meaning:"what", emoji:"❓", gifDuration:1.2, sentence:"为何迟到？" },
  { char:"但", pinyin:"dan4", radical:"亻", components:["亻","旦"], meaning:"but", emoji:"↔️", gifDuration:1.2, sentence:"虽然难，但很有趣。" },
  { char:"位", pinyin:"wei4", radical:"亻", components:["亻","立"], meaning:"position", emoji:"📍", gifDuration:1.2, sentence:"座位满了。" },
  { char:"住", pinyin:"zhu4", radical:"亻", components:["亻","主"], meaning:"live", emoji:"🏠", gifDuration:1.2, sentence:"我住在北京。" },
  { char:"借", pinyin:"jie4", radical:"亻", components:["亻","昔"], meaning:"borrow", emoji:"🤝", gifDuration:1.2, sentence:"借本书。" },
  { char:"做", pinyin:"zuo4", radical:"亻", components:["亻","古","攵"], meaning:"make", emoji:"🔨", gifDuration:1.3, sentence:"做饭。" },
  { char:"代", pinyin:"dai4", radical:"亻", components:["亻","弋"], meaning:"generation", emoji:"👨‍👦", gifDuration:1.2, sentence:"代理。" },
  { char:"付", pinyin:"fu4", radical:"亻", components:["亻","寸"], meaning:"pay", emoji:"💳", gifDuration:1.2, sentence:"付钱。" },
  { char:"仙", pinyin:"xian1", radical:"亻", components:["亻","山"], meaning:"immortal", emoji:"🧚", gifDuration:1.2, sentence:"仙人掌。" },
  { char:"份", pinyin:"fen4", radical:"亻", components:["亻","分"], meaning:"portion", emoji:"🍽️", gifDuration:1.2, sentence:"一份礼物。" },
  { char:"伴", pinyin:"ban4", radical:"亻", components:["亻","半"], meaning:"companion", emoji:"👫", gifDuration:1.2, sentence:"找个伴。" },
  { char:"佛", pinyin:"fo2", radical:"亻", components:["亻","弗"], meaning:"Buddha", emoji:"🧘", gifDuration:1.2, sentence:"信佛。" },
  { char:"供", pinyin:"gong1", radical:"亻", components:["亻","共"], meaning:"supply", emoji:"📦", gifDuration:1.2, sentence:"供不应求。" },
  { char:"使", pinyin:"shi3", radical:"亻", components:["亻","吏"], meaning:"use", emoji:"🔧", gifDuration:1.2, sentence:"使用电脑。" },
  { char:"侵", pinyin:"qin1", radical:"亻", components:["亻","帚"], meaning:"invade", emoji:"⚔️", gifDuration:1.2, sentence:"侵犯隐私。" },
  { char:"保", pinyin:"bao3", radical:"亻", components:["亻","呆"], meaning:"protect", emoji:"🛡️", gifDuration:1.2, sentence:"保护环境。" },
  { char:"侯", pinyin:"hou2", radical:"亻", components:["亻","矢"], meaning:"marquis", emoji:"👑", gifDuration:1.2, sentence:"侯爷。" },
  { char:"俗", pinyin:"su2", radical:"亻", components:["亻","谷"], meaning:"custom", emoji:"🎎", gifDuration:1.2, sentence:"风俗习惯。" },
  { char:"俘", pinyin:"fu2", radical:"亻", components:["亻","孚"], meaning:"capture", emoji:"🔒", gifDuration:1.2, sentence:"俘虏。" },
  { char:"俊", pinyin:"jun4", radical:"亻", components:["亻","夋"], meaning:"handsome", emoji:"😎", gifDuration:1.2, sentence:"英俊。" },
  { char:"俄", pinyin:"e2", radical:"亻", components:["亻","我"], meaning:"sudden", emoji:"🇷🇺", gifDuration:1.2, sentence:"俄罗斯。" },
  { char:"修", pinyin:"xiu1", radical:"亻", components:["亻","攸","彡"], meaning:"repair", emoji:"🔧", gifDuration:1.3, sentence:"修理自行车。" },
  { char:"假", pinyin:"jia3", radical:"亻", components:["亻","叚"], meaning:"false", emoji:"🎭", gifDuration:1.2, sentence:"放假了。" },
  // 女 radical
  { char:"女", pinyin:"nv3", radical:"女", components:[], meaning:"woman", emoji:"👩", gifDuration:1, sentence:"女孩子。" },
  { char:"好", pinyin:"hao3", radical:"女", components:["女","子"], meaning:"good", emoji:"👍", gifDuration:1.2, sentence:"好朋友。" },
  { char:"她", pinyin:"ta1", radical:"女", components:["女","也"], meaning:"she", emoji:"👩", gifDuration:1.2, sentence:"她是谁？" },
  { char:"妈", pinyin:"ma1", radical:"女", components:["女","马"], meaning:"mother", emoji:"👩‍👧", gifDuration:1.2, sentence:"妈妈好。" },
  { char:"姓", pinyin:"xing4", radical:"女", components:["女","生"], meaning:"surname", emoji:"📛", gifDuration:1.2, sentence:"贵姓？" },
  { char:"婚", pinyin:"hun1", radical:"女", components:["女","昏"], meaning:"marriage", emoji:"💍", gifDuration:1.2, sentence:"结婚。" },
  { char:"妹", pinyin:"mei4", radical:"女", components:["女","未"], meaning:"younger sister", emoji:"👧", gifDuration:1.2, sentence:"妹妹。" },
  { char:"姐", pinyin:"jie3", radical:"女", components:["女","且"], meaning:"older sister", emoji:"👩", gifDuration:1.2, sentence:"姐姐。" },
  { char:"奶", pinyin:"nai3", radical:"女", components:["女","乃"], meaning:"milk", emoji:"🥛", gifDuration:1.2, sentence:"喝牛奶。" },
  { char:"妙", pinyin:"miao4", radical:"女", components:["女","少"], meaning:"wonderful", emoji:"✨", gifDuration:1.2, sentence:"妙极了。" },
  { char:"妻", pinyin:"qi1", radical:"女", components:["十","彐","女"], meaning:"wife", emoji:"💑", gifDuration:1.3, sentence:"妻子。" },
  { char:"妾", pinyin:"qie4", radical:"女", components:["立","女"], meaning:"concubine", emoji:"👤", gifDuration:1.2, sentence:"妾身。" },
  { char:"始", pinyin:"shi3", radical:"女", components:["女","台"], meaning:"begin", emoji:"🏁", gifDuration:1.2, sentence:"开始。" },
  { char:"委", pinyin:"wei3", radical:"女", components:["禾","女"], meaning:"entrust", emoji:"🤝", gifDuration:1.2, sentence:"委托。" },
  { char:"姻", pinyin:"yin1", radical:"女", components:["女","因"], meaning:"marriage", emoji:"💒", gifDuration:1.2, sentence:"婚姻。" },
  { char:"姿", pinyin:"zi1", radical:"女", components:["次","女"], meaning:"posture", emoji:"💃", gifDuration:1.2, sentence:"姿势。" },
  { char:"威", pinyin:"wei1", radical:"女", components:["戊","女"], meaning:"power", emoji:"💪", gifDuration:1.2, sentence:"威力。" },
  { char:"娇", pinyin:"jiao1", radical:"女", components:["女","乔"], meaning:"delicate", emoji:"🌸", gifDuration:1.2, sentence:"娇嫩。" },
  { char:"娘", pinyin:"niang2", radical:"女", components:["女","良"], meaning:"mother", emoji:"👩‍👧", gifDuration:1.2, sentence:"姑娘。" },
  // 子 radical
  { char:"子", pinyin:"zi3", radical:"子", components:[], meaning:"child", emoji:"👶", gifDuration:1, sentence:"子女。" },
  { char:"孩", pinyin:"hai2", radical:"子", components:["子","亥"], meaning:"child", emoji:"🧒", gifDuration:1.2, sentence:"孩子们。" },
  { char:"学", pinyin:"xue2", radical:"子", components:["⺈","冖","子"], meaning:"study", emoji:"📚", gifDuration:1.2, sentence:"学习。" },
  { char:"孝", pinyin:"xiao4", radical:"子", components:["老","子"], meaning:"filial", emoji:"👴👶", gifDuration:1.2, sentence:"孝顺。" },
  { char:"孙", pinyin:"sun1", radical:"子", components:["子","小"], meaning:"grandson", emoji:"👶", gifDuration:1.2, sentence:"孙子。" },
  { char:"存", pinyin:"cun2", radical:"子", components:["才","子"], meaning:"exist", emoji:"💾", gifDuration:1.2, sentence:"存在。" },
  { char:"字", pinyin:"zi4", radical:"子", components:["宀","子"], meaning:"character", emoji:"🔤", gifDuration:1.2, sentence:"汉字。" },
  // 口 radical
  { char:"口", pinyin:"kou3", radical:"口", components:[], meaning:"mouth", emoji:"👄", gifDuration:0.9, sentence:"口腔。" },
  { char:"叫", pinyin:"jiao4", radical:"口", components:["口","丩"], meaning:"call", emoji:"🗣️", gifDuration:1.2, sentence:"大叫。" },
  { char:"吃", pinyin:"chi1", radical:"口", components:["口","乞"], meaning:"eat", emoji:"🍽️", gifDuration:1.2, sentence:"吃饭。" },
  { char:"喝", pinyin:"he1", radical:"口", components:["口","曷"], meaning:"drink", emoji:"🥤", gifDuration:1.2, sentence:"喝水。" },
  { char:"唱", pinyin:"chang4", radical:"口", components:["口","昌"], meaning:"sing", emoji:"🎤", gifDuration:1.2, sentence:"唱歌。" },
  { char:"呼", pinyin:"hu1", radical:"口", components:["口","乎"], meaning:"exhale", emoji:"💨", gifDuration:1.2, sentence:"呼吸。" },
  { char:"吸", pinyin:"xi1", radical:"口", components:["口","及"], meaning:"inhale", emoji:"🫁", gifDuration:1.2, sentence:"吸气。" },
  { char:"叶", pinyin:"ye4", radical:"口", components:["口","十"], meaning:"leaf", emoji:"🍃", gifDuration:1.2, sentence:"树叶。" },
  { char:"吹", pinyin:"chui1", radical:"口", components:["口","欠"], meaning:"blow", emoji:"🌬️", gifDuration:1.2, sentence:"吹风。" },
  { char:"呀", pinyin:"ya1", radical:"口", components:["口","牙"], meaning:"ah", emoji:"😲", gifDuration:1.2, sentence:"哎呀！" },
  { char:"呢", pinyin:"ne5", radical:"口", components:["口","尼"], meaning:"particle", emoji:"❔", gifDuration:1.2, sentence:"你呢？" },
  { char:"吧", pinyin:"ba5", radical:"口", components:["口","巴"], meaning:"bar", emoji:"🍸", gifDuration:1.2, sentence:"走吧。" },
  { char:"品", pinyin:"pin3", radical:"口", components:["口","口","口"], meaning:"product", emoji:"🏷️", gifDuration:1.2, sentence:"商品。" },
  { char:"味", pinyin:"wei4", radical:"口", components:["口","未"], meaning:"taste", emoji:"👅", gifDuration:1.2, sentence:"味道。" },
  { char:"命", pinyin:"ming4", radical:"口", components:["人","一","叩"], meaning:"life", emoji:"🧬", gifDuration:1.3, sentence:"生命。" },
  // 心/忄 radical
  { char:"心", pinyin:"xin1", radical:"心", components:[], meaning:"heart", emoji:"❤️", gifDuration:0.9, sentence:"心里。" },
  { char:"忙", pinyin:"mang2", radical:"忄", components:["忄","亡"], meaning:"busy", emoji:"🏃‍♀️", gifDuration:1.2, sentence:"很忙。" },
  { char:"快", pinyin:"kuai4", radical:"忄", components:["忄","夬"], meaning:"fast", emoji:"⚡", gifDuration:1.2, sentence:"快乐。" },
  { char:"想", pinyin:"xiang3", radical:"心", components:["相","心"], meaning:"think", emoji:"💭", gifDuration:1.2, sentence:"想念。" },
  { char:"思", pinyin:"si1", radical:"心", components:["田","心"], meaning:"think", emoji:"🤔", gifDuration:1.2, sentence:"思考。" },
  { char:"意", pinyin:"yi4", radical:"心", components:["音","心"], meaning:"meaning", emoji:"💡", gifDuration:1.2, sentence:"意思。" },
  { char:"志", pinyin:"zhi4", radical:"心", components:["士","心"], meaning:"will", emoji:"🎯", gifDuration:1.2, sentence:"意志。" },
  { char:"忘", pinyin:"wang4", radical:"心", components:["亡","心"], meaning:"forget", emoji:"🧠❌", gifDuration:1.2, sentence:"忘记。" },
  { char:"忍", pinyin:"ren3", radical:"心", components:["刃","心"], meaning:"endure", emoji:"😣", gifDuration:1.2, sentence:"忍耐。" },
  { char:"急", pinyin:"ji2", radical:"心", components:["刍","心"], meaning:"urgent", emoji:"⏰", gifDuration:1.2, sentence:"紧急。" },
  { char:"怒", pinyin:"nu4", radical:"心", components:["奴","心"], meaning:"anger", emoji:"😡", gifDuration:1.2, sentence:"发怒。" },
  { char:"恐", pinyin:"kong3", radical:"心", components:["巩","心"], meaning:"fear", emoji:"😱", gifDuration:1.2, sentence:"恐惧。" },
  { char:"恶", pinyin:"e4", radical:"心", components:["亚","心"], meaning:"evil", emoji:"👿", gifDuration:1.2, sentence:"恶人。" },
  { char:"悲", pinyin:"bei1", radical:"心", components:["非","心"], meaning:"sad", emoji:"😢", gifDuration:1.2, sentence:"悲伤。" },
  { char:"惑", pinyin:"huo4", radical:"心", components:["或","心"], meaning:"confuse", emoji:"😕", gifDuration:1.2, sentence:"疑惑。" },
  { char:"恋", pinyin:"lian4", radical:"心", components:["亦","心"], meaning:"love", emoji:"💘", gifDuration:1.2, sentence:"恋爱。" },
  { char:"恩", pinyin:"en1", radical:"心", components:["因","心"], meaning:"grace", emoji:"🙏", gifDuration:1.2, sentence:"恩情。" },

  // ───────────────── 🏠 Places & Buildings ─────────────────
  // 宀 radical
  { char:"宀", pinyin:"mian2", radical:"宀", components:[], meaning:"roof", emoji:"🏠", gifDuration:0.9, sentence:"宝盖头。" },
  { char:"家", pinyin:"jia1", radical:"宀", components:["宀","豕"], meaning:"home", emoji:"👨‍👩‍👧‍👦", gifDuration:1.2, sentence:"回家。" },
  { char:"安", pinyin:"an1", radical:"宀", components:["宀","女"], meaning:"peace", emoji:"🕊️", gifDuration:1.2, sentence:"安全。" },
  { char:"室", pinyin:"shi4", radical:"宀", components:["宀","至"], meaning:"room", emoji:"🛏️", gifDuration:1.2, sentence:"卧室。" },
  { char:"宫", pinyin:"gong1", radical:"宀", components:["宀","吕"], meaning:"palace", emoji:"🏯", gifDuration:1.2, sentence:"故宫。" },
  { char:"灾", pinyin:"zai1", radical:"宀", components:["宀","火"], meaning:"disaster", emoji:"🏚️", gifDuration:1.2, sentence:"火灾。" },
  { char:"宇", pinyin:"yu3", radical:"宀", components:["宀","于"], meaning:"universe", emoji:"🌌", gifDuration:1.2, sentence:"宇宙。" },
  { char:"守", pinyin:"shou3", radical:"宀", components:["宀","寸"], meaning:"guard", emoji:"🛡️", gifDuration:1.2, sentence:"守卫。" },
  { char:"宅", pinyin:"zhai2", radical:"宀", components:["宀","乇"], meaning:"residence", emoji:"🏡", gifDuration:1.2, sentence:"住宅。" },
  { char:"宏", pinyin:"hong2", radical:"宀", components:["宀","厷"], meaning:"grand", emoji:"🏛️", gifDuration:1.2, sentence:"宏大。" },
  { char:"宗", pinyin:"zong1", radical:"宀", components:["宀","示"], meaning:"ancestor", emoji:"🕯️", gifDuration:1.2, sentence:"宗教。" },
  { char:"宜", pinyin:"yi2", radical:"宀", components:["宀","且"], meaning:"suitable", emoji:"✅", gifDuration:1.2, sentence:"适宜。" },
  { char:"宝", pinyin:"bao3", radical:"宀", components:["宀","玉"], meaning:"treasure", emoji:"💎", gifDuration:1.2, sentence:"宝贝。" },
  { char:"实", pinyin:"shi2", radical:"宀", components:["宀","头"], meaning:"real", emoji:"🔍", gifDuration:1.2, sentence:"真实。" },
  // 广 radical
  { char:"广", pinyin:"guang3", radical:"广", components:[], meaning:"wide", emoji:"🏛️", gifDuration:1, sentence:"广场。" },
  { char:"店", pinyin:"dian4", radical:"广", components:["广","占"], meaning:"shop", emoji:"🏪", gifDuration:1.2, sentence:"商店。" },
  { char:"府", pinyin:"fu3", radical:"广", components:["广","付"], meaning:"prefecture", emoji:"🏢", gifDuration:1.2, sentence:"政府。" },
  { char:"度", pinyin:"du4", radical:"广", components:["广","廿","又"], meaning:"degree", emoji:"🌡️", gifDuration:1.2, sentence:"温度。" },
  { char:"庭", pinyin:"ting2", radical:"广", components:["广","廷"], meaning:"court", emoji:"🏡", gifDuration:1.2, sentence:"家庭。" },
  { char:"康", pinyin:"kang1", radical:"广", components:["广","隶"], meaning:"health", emoji:"💪", gifDuration:1.2, sentence:"健康。" },
  { char:"庙", pinyin:"miao4", radical:"广", components:["广","由"], meaning:"temple", emoji:"⛩️", gifDuration:1.2, sentence:"寺庙。" },
  { char:"廊", pinyin:"lang2", radical:"广", components:["广","郎"], meaning:"corridor", emoji:"🏛️", gifDuration:1.2, sentence:"走廊。" },
  // 厂 radical
  { char:"厂", pinyin:"chang3", radical:"厂", components:[], meaning:"factory", emoji:"🏭", gifDuration:1, sentence:"工厂。" },
  { char:"历", pinyin:"li4", radical:"厂", components:["厂","力"], meaning:"history", emoji:"📆", gifDuration:1.2, sentence:"历史。" },
  { char:"压", pinyin:"ya1", radical:"厂", components:["厂","土"], meaning:"press", emoji:"⬇️", gifDuration:1.2, sentence:"压力。" },
  { char:"厕", pinyin:"ce4", radical:"厂", components:["厂","则"], meaning:"toilet", emoji:"🚽", gifDuration:1.2, sentence:"厕所。" },
  { char:"原", pinyin:"yuan2", radical:"厂", components:["厂","泉"], meaning:"origin", emoji:"🔙", gifDuration:1.2, sentence:"原来。" },
  { char:"厨", pinyin:"chu2", radical:"厂", components:["厂","豆","寸"], meaning:"kitchen", emoji:"🍳", gifDuration:1.3, sentence:"厨房。" },
  // 门 radical
  { char:"门", pinyin:"men2", radical:"门", components:[], meaning:"door", emoji:"🚪", gifDuration:0.9, sentence:"门口。" },
  { char:"间", pinyin:"jian1", radical:"门", components:["门","日"], meaning:"room", emoji:"↔️", gifDuration:1.2, sentence:"房间。" },
  { char:"问", pinyin:"wen4", radical:"门", components:["门","口"], meaning:"ask", emoji:"❓", gifDuration:1.2, sentence:"问题。" },
  { char:"闭", pinyin:"bi4", radical:"门", components:["门","才"], meaning:"close", emoji:"🔒", gifDuration:1.2, sentence:"闭眼。" },
  { char:"闻", pinyin:"wen2", radical:"门", components:["门","耳"], meaning:"hear", emoji:"👂", gifDuration:1.2, sentence:"新闻。" },
  { char:"闪", pinyin:"shan3", radical:"门", components:["门","人"], meaning:"flash", emoji:"⚡", gifDuration:1.2, sentence:"闪电。" },
  { char:"阁", pinyin:"ge2", radical:"门", components:["门","各"], meaning:"pavilion", emoji:"🏯", gifDuration:1.2, sentence:"楼阁。" },
  // 户 radical
  { char:"户", pinyin:"hu4", radical:"户", components:[], meaning:"door", emoji:"🚪", gifDuration:1, sentence:"户口。" },
  { char:"房", pinyin:"fang2", radical:"户", components:["户","方"], meaning:"house", emoji:"🏘️", gifDuration:1.2, sentence:"房间。" },
  { char:"扇", pinyin:"shan4", radical:"户", components:["户","羽"], meaning:"fan", emoji:"🪭", gifDuration:1.2, sentence:"扇子。" },
  { char:"所", pinyin:"suo3", radical:"户", components:["户","斤"], meaning:"place", emoji:"📍", gifDuration:1.2, sentence:"所以。" },
  { char:"扁", pinyin:"bian3", radical:"户", components:["户","冊"], meaning:"flat", emoji:"📏", gifDuration:1.2, sentence:"扁担。" },

  // ───────────────── 🎨 Arts & Tools ─────────────────
  // 手/扌 radical
  { char:"手", pinyin:"shou3", radical:"手", components:[], meaning:"hand", emoji:"✋", gifDuration:1, sentence:"左手。" },
  { char:"打", pinyin:"da3", radical:"扌", components:["扌","丁"], meaning:"hit", emoji:"🥊", gifDuration:1.2, sentence:"打架。" },
  { char:"把", pinyin:"ba3", radical:"扌", components:["扌","巴"], meaning:"hold", emoji:"🤲", gifDuration:1.2, sentence:"把门。" },
  { char:"拿", pinyin:"na2", radical:"手", components:["合","手"], meaning:"take", emoji:"🫴", gifDuration:1.2, sentence:"拿东西。" },
  { char:"接", pinyin:"jie1", radical:"扌", components:["扌","妾"], meaning:"receive", emoji:"📥", gifDuration:1.2, sentence:"接电话。" },
  { char:"推", pinyin:"tui1", radical:"扌", components:["扌","隹"], meaning:"push", emoji:"🤚", gifDuration:1.2, sentence:"推门。" },
  { char:"拉", pinyin:"la1", radical:"扌", components:["扌","立"], meaning:"pull", emoji:"🤏", gifDuration:1.2, sentence:"拉车。" },
  { char:"握", pinyin:"wo4", radical:"扌", components:["扌","屋"], meaning:"grasp", emoji:"🤝", gifDuration:1.2, sentence:"握手。" },
  { char:"指", pinyin:"zhi3", radical:"扌", components:["扌","旨"], meaning:"point", emoji:"👆", gifDuration:1.2, sentence:"手指。" },
  { char:"按", pinyin:"an4", radical:"扌", components:["扌","安"], meaning:"press", emoji:"👇", gifDuration:1.2, sentence:"按铃。" },
  { char:"挥", pinyin:"hui1", radical:"扌", components:["扌","军"], meaning:"wave", emoji:"👋", gifDuration:1.2, sentence:"挥手。" },
  { char:"持", pinyin:"chi2", radical:"扌", components:["扌","寺"], meaning:"hold", emoji:"✊", gifDuration:1.2, sentence:"坚持。" },
  { char:"折", pinyin:"zhe2", radical:"扌", components:["扌","斤"], meaning:"break", emoji:"💔", gifDuration:1.2, sentence:"折断。" },
  { char:"批", pinyin:"pi1", radical:"扌", components:["扌","比"], meaning:"criticize", emoji:"📝", gifDuration:1.2, sentence:"批评。" },
  { char:"技", pinyin:"ji4", radical:"扌", components:["扌","支"], meaning:"skill", emoji:"🛠️", gifDuration:1.2, sentence:"技术。" },
  { char:"抄", pinyin:"chao1", radical:"扌", components:["扌","少"], meaning:"copy", emoji:"📋", gifDuration:1.2, sentence:"抄写。" },
  // 刀/刂 radical
  { char:"刀", pinyin:"dao1", radical:"刀", components:[], meaning:"knife", emoji:"🔪", gifDuration:0.9, sentence:"刀子。" },
  { char:"切", pinyin:"qie1", radical:"刀", components:["七","刀"], meaning:"cut", emoji:"✂️", gifDuration:1.2, sentence:"切菜。" },
  { char:"分", pinyin:"fen1", radical:"刀", components:["八","刀"], meaning:"divide", emoji:"➗", gifDuration:1.2, sentence:"分开。" },
  { char:"划", pinyin:"hua2", radical:"刀", components:["戈","刂"], meaning:"row", emoji:"🚣", gifDuration:1.2, sentence:"划船。" },
  { char:"刻", pinyin:"ke4", radical:"刂", components:["亥","刂"], meaning:"carve", emoji:"🪒", gifDuration:1.2, sentence:"刻苦。" },
  { char:"利", pinyin:"li4", radical:"刂", components:["禾","刂"], meaning:"sharp", emoji:"🔪", gifDuration:1.2, sentence:"锋利。" },
  { char:"初", pinyin:"chu1", radical:"刀", components:["衣","刀"], meaning:"beginning", emoji:"🔰", gifDuration:1.2, sentence:"初一。" },
  { char:"判", pinyin:"pan4", radical:"刂", components:["半","刂"], meaning:"judge", emoji:"⚖️", gifDuration:1.2, sentence:"判断。" },
  { char:"刚", pinyin:"gang1", radical:"刂", components:["冈","刂"], meaning:"just", emoji:"💪", gifDuration:1.2, sentence:"刚来。" },
  { char:"创", pinyin:"chuang4", radical:"刂", components:["仓","刂"], meaning:"create", emoji:"💡", gifDuration:1.2, sentence:"创新。" },
  // 糸/纟 radical
  { char:"糸", pinyin:"mi4", radical:"糸", components:[], meaning:"silk", emoji:"🧵", gifDuration:0.9, sentence:"丝米。" },
  { char:"红", pinyin:"hong2", radical:"纟", components:["纟","工"], meaning:"red", emoji:"🔴", gifDuration:1.2, sentence:"红色。" },
  { char:"纪", pinyin:"ji4", radical:"纟", components:["纟","己"], meaning:"record", emoji:"📝", gifDuration:1.2, sentence:"纪念。" },
  { char:"线", pinyin:"xian4", radical:"纟", components:["纟","戋"], meaning:"thread", emoji:"🧵", gifDuration:1.2, sentence:"毛线。" },
  { char:"组", pinyin:"zu3", radical:"纟", components:["纟","且"], meaning:"group", emoji:"👥", gifDuration:1.2, sentence:"组织。" },
  { char:"织", pinyin:"zhi1", radical:"纟", components:["纟","只"], meaning:"weave", emoji:"🕸️", gifDuration:1.2, sentence:"织布。" },
  { char:"给", pinyin:"gei3", radical:"纟", components:["纟","合"], meaning:"give", emoji:"🎁", gifDuration:1.2, sentence:"给你。" },
  { char:"结", pinyin:"jie2", radical:"纟", components:["纟","吉"], meaning:"knot", emoji:"🔗", gifDuration:1.2, sentence:"结束。" },
  { char:"经", pinyin:"jing1", radical:"纟", components:["纟","圣"], meaning:"classic", emoji:"📖", gifDuration:1.2, sentence:"经常。" },
  { char:"绝", pinyin:"jue2", radical:"纟", components:["纟","色"], meaning:"cut off", emoji:"✂️", gifDuration:1.2, sentence:"绝对。" },
  { char:"统", pinyin:"tong3", radical:"纟", components:["纟","充"], meaning:"unite", emoji:"🤝", gifDuration:1.2, sentence:"统一。" },
  { char:"纸", pinyin:"zhi3", radical:"纟", components:["纟","氏"], meaning:"paper", emoji:"📄", gifDuration:1.2, sentence:"白纸。" },
  { char:"维", pinyin:"wei2", radical:"纟", components:["纟","隹"], meaning:"maintain", emoji:"🔧", gifDuration:1.2, sentence:"维护。" },
  // 金/钅 radical
  { char:"金", pinyin:"jin1", radical:"金", components:[], meaning:"gold", emoji:"🥇", gifDuration:1, sentence:"金子。" },
  { char:"银", pinyin:"yin2", radical:"钅", components:["钅","艮"], meaning:"silver", emoji:"🥈", gifDuration:1.2, sentence:"银行。" },
  { char:"钱", pinyin:"qian2", radical:"钅", components:["钅","戋"], meaning:"money", emoji:"💵", gifDuration:1.2, sentence:"有钱。" },
  { char:"铁", pinyin:"tie3", radical:"钅", components:["钅","失"], meaning:"iron", emoji:"⛓️", gifDuration:1.2, sentence:"铁路。" },
  { char:"钟", pinyin:"zhong1", radical:"钅", components:["钅","中"], meaning:"clock", emoji:"🕰️", gifDuration:1.2, sentence:"闹钟。" },
  { char:"针", pinyin:"zhen1", radical:"钅", components:["钅","十"], meaning:"needle", emoji:"🪡", gifDuration:1.2, sentence:"别针。" },
  { char:"钢", pinyin:"gang1", radical:"钅", components:["钅","冈"], meaning:"steel", emoji:"🔩", gifDuration:1.2, sentence:"钢笔。" },
  { char:"铜", pinyin:"tong2", radical:"钅", components:["钅","同"], meaning:"copper", emoji:"🪙", gifDuration:1.2, sentence:"铜线。" },
  { char:"锁", pinyin:"suo3", radical:"钅", components:["钅","肖"], meaning:"lock", emoji:"🔐", gifDuration:1.2, sentence:"门锁。" },
  { char:"锅", pinyin:"guo1", radical:"钅", components:["钅","咼"], meaning:"pot", emoji:"🍲", gifDuration:1.2, sentence:"铁锅。" },
  // 言/讠 radical
  { char:"言", pinyin:"yan2", radical:"言", components:[], meaning:"speech", emoji:"💬", gifDuration:1, sentence:"语言。" },
  { char:"话", pinyin:"hua4", radical:"讠", components:["讠","舌"], meaning:"speech", emoji:"🗣️", gifDuration:1.2, sentence:"说话。" },
  { char:"说", pinyin:"shuo1", radical:"讠", components:["讠","兑"], meaning:"speak", emoji:"🗨️", gifDuration:1.2, sentence:"说话。" },
  { char:"语", pinyin:"yu3", radical:"讠", components:["讠","吾"], meaning:"language", emoji:"🗣️", gifDuration:1.2, sentence:"英语。" },
  { char:"读", pinyin:"du2", radical:"讠", components:["讠","卖"], meaning:"read", emoji:"📖", gifDuration:1.2, sentence:"读书。" },
  { char:"课", pinyin:"ke4", radical:"讠", components:["讠","果"], meaning:"lesson", emoji:"📚", gifDuration:1.2, sentence:"上课。" },
  { char:"讲", pinyin:"jiang3", radical:"讠", components:["讠","井"], meaning:"speak", emoji:"🗣️", gifDuration:1.2, sentence:"讲课。" },
  { char:"计", pinyin:"ji4", radical:"讠", components:["讠","十"], meaning:"plan", emoji:"📊", gifDuration:1.2, sentence:"计算。" },
  { char:"让", pinyin:"rang4", radical:"讠", components:["讠","上"], meaning:"let", emoji:"👉", gifDuration:1.2, sentence:"让座。" },
  { char:"诗", pinyin:"shi1", radical:"讠", components:["讠","寺"], meaning:"poem", emoji:"✒️", gifDuration:1.2, sentence:"写诗。" },
  { char:"词", pinyin:"ci2", radical:"讠", components:["讠","司"], meaning:"word", emoji:"📝", gifDuration:1.2, sentence:"词语。" },
  { char:"试", pinyin:"shi4", radical:"讠", components:["讠","式"], meaning:"test", emoji:"📝", gifDuration:1.2, sentence:"考试。" },
  { char:"诚", pinyin:"cheng2", radical:"讠", components:["讠","成"], meaning:"honest", emoji:"🤝", gifDuration:1.2, sentence:"诚实。" },
  { char:"误", pinyin:"wu4", radical:"讠", components:["讠","吴"], meaning:"mistake", emoji:"❌", gifDuration:1.2, sentence:"错误。" },
  { char:"诉", pinyin:"su4", radical:"讠", components:["讠","斥"], meaning:"tell", emoji:"🗣️", gifDuration:1.2, sentence:"告诉。" },
  { char:"谢", pinyin:"xie4", radical:"讠", components:["讠","射"], meaning:"thanks", emoji:"🙏", gifDuration:1.2, sentence:"谢谢。" },
];