const charactersPart1 = [
  // ───────────────── 🚶 Movement & Direction ─────────────────
  // 走 radical
  { char:"走", pinyin:"zou3", radical:"走", components:[], meaning:"walk", emoji:"🚶", gifDuration:1.2, sentence:"我们走路去公园。" },
  { char:"起", pinyin:"qi3", radical:"走", components:["走","己"], meaning:"rise", emoji:"⬆️", gifDuration:1.2, sentence:"早上六点起床。" },
  { char:"越", pinyin:"yue4", radical:"走", components:["走","戉"], meaning:"exceed", emoji:"🏃", gifDuration:1.2, sentence:"他跑得越来越快。" },
  { char:"超", pinyin:"chao1", radical:"走", components:["走","召"], meaning:"surpass", emoji:"🆙", gifDuration:1.2, sentence:"超级市场很大。" },
  { char:"赶", pinyin:"gan3", radical:"走", components:["走","干"], meaning:"rush", emoji:"🏃‍♂️", gifDuration:1.2, sentence:"我们赶时间。" },
  { char:"赵", pinyin:"zhao4", radical:"走", components:["走","乂"], meaning:"Zhao", emoji:"👤", gifDuration:1.2, sentence:"赵先生是老师。" },
  { char:"趋", pinyin:"qu1", radical:"走", components:["走","刍"], meaning:"tend", emoji:"🐎", gifDuration:1.2, sentence:"趋势很明显。" },
  { char:"趟", pinyin:"tang4", radical:"走", components:["走","尚"], meaning:"trip", emoji:"🚶‍♀️", gifDuration:1.2, sentence:"我去了趟北京。" },
  { char:"赴", pinyin:"fu4", radical:"走", components:["走","卜"], meaning:"go to", emoji:"🏃", gifDuration:1.2, sentence:"他赴约去了。" },
  { char:"趁", pinyin:"chen4", radical:"走", components:["走","㐱"], meaning:"while", emoji:"⏱️", gifDuration:1.2, sentence:"趁热吃吧。" },
  // 彳 radical
  { char:"彳", pinyin:"chi4", radical:"彳", components:[], meaning:"step", emoji:"🦶", gifDuration:0.9, sentence:"彳亍而行。" },
  { char:"征", pinyin:"zheng1", radical:"彳", components:["彳","正"], meaning:"journey", emoji:"🎒", gifDuration:1.2, sentence:"他们出征远方。" },
  { char:"徒", pinyin:"tu2", radical:"彳", components:["彳","走"], meaning:"on foot", emoji:"👣", gifDuration:1.2, sentence:"徒步旅行很有趣。" },
  { char:"徙", pinyin:"xi3", radical:"彳", components:["彳","止","龰"], meaning:"migrate", emoji:"🚚", gifDuration:1.4, sentence:"鸟迁徙到南方。" },
  { char:"後", pinyin:"hou4", radical:"彳", components:["彳","幺","夂"], meaning:"after", emoji:"🔙", gifDuration:1.2, sentence:"后来我们和好了。" },
  { char:"徐", pinyin:"xu2", radical:"彳", components:["彳","余"], meaning:"slowly", emoji:"🐢", gifDuration:1.2, sentence:"清风徐来。" },
  { char:"得", pinyin:"de2", radical:"彳", components:["彳","㝵","寸"], meaning:"get", emoji:"🎁", gifDuration:1.2, sentence:"他得到了奖品。" },
  { char:"德", pinyin:"de2", radical:"彳", components:["彳","十","罒","一","心"], meaning:"virtue", emoji:"🌟", gifDuration:1.5, sentence:"品德高尚。" },
  { char:"律", pinyin:"lv4", radical:"彳", components:["彳","聿"], meaning:"law", emoji:"⚖️", gifDuration:1.2, sentence:"遵守法律。" },
  { char:"很", pinyin:"hen3", radical:"彳", components:["彳","艮"], meaning:"very", emoji:"💪", gifDuration:1.2, sentence:"今天很热。" },
  { char:"復", pinyin:"fu4", radical:"彳", components:["彳","复"], meaning:"return", emoji:"↩️", gifDuration:1.3, sentence:"病復发了。" },
  { char:"微", pinyin:"wei1", radical:"彳", components:["彳","微"], meaning:"tiny", emoji:"🔬", gifDuration:1.3, sentence:"微信很方便。" },
  // 行 radical
  { char:"行", pinyin:"xing2", radical:"行", components:[], meaning:"go", emoji:"🚶", gifDuration:1, sentence:"行路难。" },
  { char:"街", pinyin:"jie1", radical:"行", components:["行","圭"], meaning:"street", emoji:"🛣️", gifDuration:1.2, sentence:"逛街购物。" },
  { char:"衙", pinyin:"ya2", radical:"行", components:["行","吾"], meaning:"office", emoji:"🏛️", gifDuration:1.2, sentence:"衙门旧时官府。" },
  // 足 radical
  { char:"足", pinyin:"zu2", radical:"足", components:[], meaning:"foot", emoji:"🦶", gifDuration:1, sentence:"知足常乐。" },
  { char:"跑", pinyin:"pao3", radical:"足", components:["足","包"], meaning:"run", emoji:"🏃‍♂️", gifDuration:1.2, sentence:"狗跑得很快。" },
  { char:"跳", pinyin:"tiao4", radical:"足", components:["足","兆"], meaning:"jump", emoji:"🤾", gifDuration:0.9, sentence:"小孩喜欢跳舞。" },
  { char:"路", pinyin:"lu4", radical:"足", components:["足","各"], meaning:"road", emoji:"🛤️", gifDuration:1.2, sentence:"一路平安。" },
  { char:"跟", pinyin:"gen1", radical:"足", components:["足","艮"], meaning:"follow", emoji:"👣", gifDuration:1.2, sentence:"跟着妈妈走。" },
  { char:"踢", pinyin:"ti1", radical:"足", components:["足","易"], meaning:"kick", emoji:"⚽", gifDuration:1.2, sentence:"踢足球。" },
  { char:"踩", pinyin:"cai3", radical:"足", components:["足","采"], meaning:"step on", emoji:"🦶", gifDuration:1.2, sentence:"小心踩到水。" },
  { char:"跪", pinyin:"gui4", radical:"足", components:["足","危"], meaning:"kneel", emoji:"🧎", gifDuration:1.3, sentence:"跪下求饶。" },
  { char:"踏", pinyin:"ta4", radical:"足", components:["足","沓"], meaning:"tread", emoji:"🦶", gifDuration:1.2, sentence:"踏青郊游。" },
  // 廴 radical
  { char:"建", pinyin:"jian4", radical:"廴", components:["廴","聿"], meaning:"build", emoji:"🏗️", gifDuration:1.2, sentence:"建房子。" },
  { char:"延", pinyin:"yan2", radical:"廴", components:["廴","正"], meaning:"prolong", emoji:"⏳", gifDuration:1.2, sentence:"延期举行。" },
  { char:"廷", pinyin:"ting2", radical:"廴", components:["廴","壬"], meaning:"court", emoji:"🏛️", gifDuration:1.2, sentence:"朝廷大臣。" },

  // ───────────────── 🌿 Nature & Elements ─────────────────
  // 木 radical
  { char:"木", pinyin:"mu4", radical:"木", components:[], meaning:"tree", emoji:"🌳", gifDuration:0.9, sentence:"一棵大树。" },
  { char:"林", pinyin:"lin2", radical:"木", components:["木","木"], meaning:"forest", emoji:"🌲🌲", gifDuration:1.2, sentence:"森林里有很多动物。" },
  { char:"森", pinyin:"sen1", radical:"木", components:["木","林"], meaning:"dense forest", emoji:"🌳🌳🌳", gifDuration:1.2, sentence:"森林深处。" },
  { char:"本", pinyin:"ben3", radical:"木", components:["木","一"], meaning:"root", emoji:"🌱", gifDuration:1.2, sentence:"读书是本。" },
  { char:"末", pinyin:"mo4", radical:"木", components:["木","一"], meaning:"tip", emoji:"🌿", gifDuration:1.2, sentence:"周末愉快。" },
  { char:"果", pinyin:"guo3", radical:"木", components:["田","木"], meaning:"fruit", emoji:"🍎", gifDuration:1.2, sentence:"水果很好吃。" },
  { char:"棵", pinyin:"ke1", radical:"木", components:["木","果"], meaning:"tree measure", emoji:"🌴", gifDuration:1.2, sentence:"一棵大树。" },
  { char:"机", pinyin:"ji1", radical:"木", components:["木","几"], meaning:"machine", emoji:"🤖", gifDuration:1.2, sentence:"手机坏了。" },
  { char:"桌", pinyin:"zhuo1", radical:"木", components:["木","卓"], meaning:"table", emoji:"🪑", gifDuration:1.2, sentence:"餐桌上有饭菜。" },
  { char:"桥", pinyin:"qiao2", radical:"木", components:["木","乔"], meaning:"bridge", emoji:"🌉", gifDuration:1.2, sentence:"过桥左拐。" },
  { char:"根", pinyin:"gen1", radical:"木", components:["木","艮"], meaning:"root", emoji:"🌱", gifDuration:1.2, sentence:"树根很深。" },
  { char:"树", pinyin:"shu4", radical:"木", components:["木","对"], meaning:"tree", emoji:"🌳", gifDuration:1.2, sentence:"植树造林。" },
  { char:"材", pinyin:"cai2", radical:"木", components:["木","才"], meaning:"material", emoji:"🪵", gifDuration:1.2, sentence:"材料齐全。" },
  { char:"村", pinyin:"cun1", radical:"木", components:["木","寸"], meaning:"village", emoji:"🏡", gifDuration:1.2, sentence:"小村庄很美。" },
  { char:"松", pinyin:"song1", radical:"木", components:["木","公"], meaning:"pine", emoji:"🌲", gifDuration:1.2, sentence:"松树长青。" },
  { char:"板", pinyin:"ban3", radical:"木", components:["木","反"], meaning:"board", emoji:"📋", gifDuration:1.2, sentence:"木板很结实。" },
  // 水/氵 radical
  { char:"水", pinyin:"shui3", radical:"水", components:[], meaning:"water", emoji:"💧", gifDuration:1, sentence:"喝水。" },
  { char:"河", pinyin:"he2", radical:"氵", components:["氵","可"], meaning:"river", emoji:"🏞️", gifDuration:1.2, sentence:"黄河是中国第二长河。" },
  { char:"海", pinyin:"hai3", radical:"氵", components:["氵","每"], meaning:"sea", emoji:"🌊", gifDuration:1.2, sentence:"大海很美。" },
  { char:"江", pinyin:"jiang1", radical:"氵", components:["氵","工"], meaning:"large river", emoji:"🌊", gifDuration:1.2, sentence:"长江流经很多城市。" },
  { char:"汗", pinyin:"han4", radical:"氵", components:["氵","干"], meaning:"sweat", emoji:"💦", gifDuration:1.2, sentence:"他流了很多汗。" },
  { char:"汁", pinyin:"zhi1", radical:"氵", components:["氵","十"], meaning:"juice", emoji:"🧃", gifDuration:1.2, sentence:"橙汁很好喝。" },
  { char:"池", pinyin:"chi2", radical:"氵", components:["氵","也"], meaning:"pond", emoji:"🪷", gifDuration:1.2, sentence:"池塘里有鱼。" },
  { char:"洗", pinyin:"xi3", radical:"氵", components:["氵","先"], meaning:"wash", emoji:"🧼", gifDuration:1.2, sentence:"洗手吃饭。" },
  { char:"游", pinyin:"you2", radical:"氵", components:["氵","斿"], meaning:"swim", emoji:"🏊", gifDuration:1.2, sentence:"游泳锻炼身体。" },
  { char:"湖", pinyin:"hu2", radical:"氵", components:["氵","胡"], meaning:"lake", emoji:"🚣", gifDuration:1.2, sentence:"西湖风景如画。" },
  { char:"洋", pinyin:"yang2", radical:"氵", components:["氵","羊"], meaning:"ocean", emoji:"🌊", gifDuration:1.2, sentence:"太平洋很大。" },
  { char:"泡", pinyin:"pao4", radical:"氵", components:["氵","包"], meaning:"bubble", emoji:"🫧", gifDuration:1.2, sentence:"泡一杯茶。" },
  { char:"波", pinyin:"bo1", radical:"氵", components:["氵","皮"], meaning:"wave", emoji:"🌊", gifDuration:1.2, sentence:"波浪起伏。" },
  { char:"泪", pinyin:"lei4", radical:"氵", components:["氵","目"], meaning:"tear", emoji:"😢", gifDuration:1.2, sentence:"她流下了眼泪。" },
  { char:"深", pinyin:"shen1", radical:"氵", components:["氵","罙"], meaning:"deep", emoji:"🌊", gifDuration:1.2, sentence:"这口井很深。" },
  { char:"浅", pinyin:"qian3", radical:"氵", components:["氵","戋"], meaning:"shallow", emoji:"🏖️", gifDuration:1.2, sentence:"水很浅。" },
  // 火 radical
  { char:"火", pinyin:"huo3", radical:"火", components:[], meaning:"fire", emoji:"🔥", gifDuration:0.9, sentence:"火灭了。" },
  { char:"炎", pinyin:"yan2", radical:"火", components:["火","火"], meaning:"flame", emoji:"🔥🔥", gifDuration:1.2, sentence:"发炎了要吃药。" },
  { char:"灯", pinyin:"deng1", radical:"火", components:["火","丁"], meaning:"lamp", emoji:"💡", gifDuration:1.2, sentence:"开灯。" },
  { char:"灾", pinyin:"zai1", radical:"火", components:["宀","火"], meaning:"disaster", emoji:"🔥🏠", gifDuration:1.2, sentence:"火灾很可怕。" },
  { char:"灭", pinyin:"mie4", radical:"火", components:["一","火"], meaning:"extinguish", emoji:"🚫🔥", gifDuration:1.2, sentence:"灭火。" },
  { char:"灰", pinyin:"hui1", radical:"火", components:["厂","火"], meaning:"ash", emoji:"🏭", gifDuration:1.2, sentence:"炉灰要清理。" },
  { char:"炭", pinyin:"tan4", radical:"火", components:["山","厂","火"], meaning:"charcoal", emoji:"🪵", gifDuration:1.2, sentence:"冬天烧炭取暖。" },
  { char:"灶", pinyin:"zao4", radical:"火", components:["火","土"], meaning:"stove", emoji:"🍳", gifDuration:1.2, sentence:"灶王爷上天。" },
  { char:"烟", pinyin:"yan1", radical:"火", components:["火","因"], meaning:"smoke", emoji:"💨", gifDuration:1.2, sentence:"禁止吸烟。" },
  { char:"烧", pinyin:"shao1", radical:"火", components:["火","尧"], meaning:"burn", emoji:"🔥", gifDuration:1.2, sentence:"烧水做饭。" },
  { char:"燃", pinyin:"ran2", radical:"火", components:["火","然"], meaning:"ignite", emoji:"🔥", gifDuration:1.3, sentence:"燃料不足。" },
  // 山 radical
  { char:"山", pinyin:"shan1", radical:"山", components:[], meaning:"mountain", emoji:"⛰️", gifDuration:1, sentence:"山上空气好。" },
  { char:"岳", pinyin:"yue4", radical:"山", components:["丘","山"], meaning:"high mountain", emoji:"🏔️", gifDuration:1.2, sentence:"岳父就是妻子的父亲。" },
  { char:"岩", pinyin:"yan2", radical:"山", components:["山","石"], meaning:"rock", emoji:"🪨", gifDuration:1.2, sentence:"岩石很硬。" },
  { char:"岸", pinyin:"an4", radical:"山", components:["山","厂","干"], meaning:"shore", emoji:"🏖️", gifDuration:1.2, sentence:"河岸边。" },
  { char:"峰", pinyin:"feng1", radical:"山", components:["山","夆"], meaning:"peak", emoji:"⛰️", gifDuration:1.2, sentence:"登山运动员爬上高峰。" },
  { char:"峡", pinyin:"xia2", radical:"山", components:["山","夹"], meaning:"gorge", emoji:"🏞️", gifDuration:1.2, sentence:"三峡大坝。" },
  { char:"岭", pinyin:"ling3", radical:"山", components:["山","令"], meaning:"ridge", emoji:"⛰️", gifDuration:1.2, sentence:"翻山越岭。" },
  // 石 radical
  { char:"石", pinyin:"shi2", radical:"石", components:[], meaning:"stone", emoji:"🪨", gifDuration:1, sentence:"石头。" },
  { char:"矿", pinyin:"kuang4", radical:"石", components:["石","广"], meaning:"mine", emoji:"⛏️", gifDuration:1.2, sentence:"煤矿工人。" },
  { char:"研", pinyin:"yan2", radical:"石", components:["石","开"], meaning:"research", emoji:"🔬", gifDuration:1.2, sentence:"研究科学。" },
  { char:"破", pinyin:"po4", radical:"石", components:["石","皮"], meaning:"break", emoji:"💥", gifDuration:1.2, sentence:"衣服破了。" },
  { char:"硬", pinyin:"ying4", radical:"石", components:["石","更"], meaning:"hard", emoji:"💎", gifDuration:1.2, sentence:"硬骨头。" },
  { char:"碎", pinyin:"sui4", radical:"石", components:["石","卒"], meaning:"shatter", emoji:"💔", gifDuration:1.2, sentence:"杯子碎了。" },
  { char:"碑", pinyin:"bei1", radical:"石", components:["石","卑"], meaning:"monument", emoji:"📜", gifDuration:1.2, sentence:"人民英雄纪念碑。" },
  // 日 radical
  { char:"日", pinyin:"ri4", radical:"日", components:[], meaning:"sun", emoji:"☀️", gifDuration:0.9, sentence:"今天是星期日。" },
  { char:"明", pinyin:"ming2", radical:"日", components:["日","月"], meaning:"bright", emoji:"🌞", gifDuration:1.2, sentence:"明天会更好。" },
  { char:"星", pinyin:"xing1", radical:"日", components:["日","生"], meaning:"star", emoji:"⭐", gifDuration:1.2, sentence:"星星眨眼睛。" },
  { char:"早", pinyin:"zao3", radical:"日", components:["日","十"], meaning:"early", emoji:"🌅", gifDuration:1.2, sentence:"早上好！" },
  { char:"时", pinyin:"shi2", radical:"日", components:["日","寸"], meaning:"time", emoji:"⏰", gifDuration:1.2, sentence:"时间就是金钱。" },
  { char:"春", pinyin:"chun1", radical:"日", components:["𡗸","日"], meaning:"spring", emoji:"🌸", gifDuration:1.2, sentence:"春天来了。" },
  { char:"晚", pinyin:"wan3", radical:"日", components:["日","免"], meaning:"evening", emoji:"🌆", gifDuration:1.2, sentence:"晚上吃什么？" },
  { char:"晴", pinyin:"qing2", radical:"日", components:["日","青"], meaning:"clear", emoji:"☀️", gifDuration:1.2, sentence:"天气晴朗。" },
  // 雨 radical
  { char:"雨", pinyin:"yu3", radical:"雨", components:[], meaning:"rain", emoji:"🌧️", gifDuration:1, sentence:"下雨了。" },
  { char:"雪", pinyin:"xue3", radical:"雨", components:["雨","彐"], meaning:"snow", emoji:"❄️", gifDuration:1.2, sentence:"冬天下雪。" },
  { char:"雷", pinyin:"lei2", radical:"雨", components:["雨","田"], meaning:"thunder", emoji:"⚡", gifDuration:1.2, sentence:"打雷了，快回家。" },
  { char:"雾", pinyin:"wu4", radical:"雨", components:["雨","务"], meaning:"fog", emoji:"🌫️", gifDuration:1.2, sentence:"大雾天气开车小心。" },
  { char:"霜", pinyin:"shuang1", radical:"雨", components:["雨","相"], meaning:"frost", emoji:"❄️", gifDuration:1.2, sentence:"地上有霜。" },
  // 气 radical
  { char:"气", pinyin:"qi4", radical:"气", components:[], meaning:"air", emoji:"💨", gifDuration:0.9, sentence:"空气新鲜。" },
  { char:"汽", pinyin:"qi4", radical:"氵", components:["氵","气"], meaning:"steam", emoji:"♨️", gifDuration:1.2, sentence:"烧水冒出蒸汽。" },
  { char:"氛", pinyin:"fen1", radical:"气", components:["气","分"], meaning:"atmosphere", emoji:"🌬️", gifDuration:1.2, sentence:"气氛很好。" },
  // 风 radical
  { char:"风", pinyin:"feng1", radical:"风", components:[], meaning:"wind", emoji:"🌬️", gifDuration:1, sentence:"刮风了。" },
  { char:"飘", pinyin:"piao1", radical:"风", components:["票","风"], meaning:"float", emoji:"🍃", gifDuration:1.2, sentence:"红旗飘。" },
  { char:"飓", pinyin:"ju4", radical:"风", components:["风","具"], meaning:"hurricane", emoji:"🌀", gifDuration:1.3, sentence:"飓风来了！" },
];