const charactersPart4 = [
  // ───────────────── 🌿 Nature & Elements (more) ─────────────────
  { char:"雹", pinyin:"bao2", radical:"雨", components:["雨","包"], meaning:"hail", emoji:"🧊", gifDuration:1.2, sentence:"下冰雹了！" },
  { char:"霾", pinyin:"mai2", radical:"雨", components:["雨","貍"], meaning:"haze", emoji:"🌫️", gifDuration:1.3, sentence:"今天有雾霾。" },
  { char:"氧", pinyin:"yang3", radical:"气", components:["气","羊"], meaning:"oxygen", emoji:"🫧", gifDuration:1.2, sentence:"我们需要氧气。" },
  { char:"氢", pinyin:"qing1", radical:"气", components:["气","圣"], meaning:"hydrogen", emoji:"💨", gifDuration:1.2, sentence:"氢气很轻。" },
  { char:"飓", pinyin:"ju4", radical:"风", components:["风","具"], meaning:"hurricane", emoji:"🌀", gifDuration:1.3, sentence:"飓风来了！" },
  { char:"飒", pinyin:"sa4", radical:"风", components:["立","风"], meaning:"rustle", emoji:"🍃", gifDuration:1.2, sentence:"秋风飒飒。" },
  { char:"坪", pinyin:"ping2", radical:"土", components:["土","平"], meaning:"flat ground", emoji:"🏞️", gifDuration:1.2, sentence:"草坪很绿。" },
  { char:"坑", pinyin:"keng1", radical:"土", components:["土","亢"], meaning:"pit", emoji:"🕳️", gifDuration:1.2, sentence:"地上有个坑。" },
  { char:"堤", pinyin:"di1", radical:"土", components:["土","是"], meaning:"embankment", emoji:"🌊", gifDuration:1.2, sentence:"河堤很长。" },
  { char:"砖", pinyin:"zhuan1", radical:"石", components:["石","专"], meaning:"brick", emoji:"🧱", gifDuration:1.2, sentence:"房子是砖做的。" },
  { char:"础", pinyin:"chu3", radical:"石", components:["石","出"], meaning:"foundation", emoji:"🏗️", gifDuration:1.2, sentence:"基础很重要。" },
  { char:"碌", pinyin:"lu4", radical:"石", components:["石","录"], meaning:"busy", emoji:"🏃", gifDuration:1.2, sentence:"他工作很忙碌。" },
  { char:"碍", pinyin:"ai4", radical:"石", components:["石","㝵"], meaning:"hinder", emoji:"🚧", gifDuration:1.2, sentence:"没有障碍。" },
  { char:"晒", pinyin:"shai4", radical:"日", components:["日","西"], meaning:"sunbathe", emoji:"☀️", gifDuration:1.2, sentence:"在外面晒太阳。" },
  { char:"晓", pinyin:"xiao3", radical:"日", components:["日","尧"], meaning:"dawn", emoji:"🌅", gifDuration:1.2, sentence:"天刚晓。" },
  { char:"晖", pinyin:"hui1", radical:"日", components:["日","军"], meaning:"sunshine", emoji:"🌞", gifDuration:1.2, sentence:"朝晖很美。" },
  { char:"涛", pinyin:"tao1", radical:"氵", components:["氵","寿"], meaning:"waves", emoji:"🌊", gifDuration:1.2, sentence:"波涛汹涌。" },
  { char:"淋", pinyin:"lin2", radical:"氵", components:["氵","林"], meaning:"drench", emoji:"🌧️", gifDuration:1.2, sentence:"我被雨淋湿了。" },
  { char:"漏", pinyin:"lou4", radical:"氵", components:["氵","屚"], meaning:"leak", emoji:"💧", gifDuration:1.2, sentence:"水漏了一地。" },
  { char:"溪", pinyin:"xi1", radical:"氵", components:["氵","奚"], meaning:"creek", emoji:"🏞️", gifDuration:1.2, sentence:"小溪流水。" },
  { char:"渔", pinyin:"yu2", radical:"氵", components:["氵","鱼"], meaning:"fishing", emoji:"🎣", gifDuration:1.2, sentence:"渔民出海打鱼。" },
  { char:"炸", pinyin:"zha2", radical:"火", components:["火","乍"], meaning:"explode", emoji:"💥", gifDuration:1.2, sentence:"煤气爆炸了。" },
  { char:"炼", pinyin:"lian4", radical:"火", components:["火","柬"], meaning:"refine", emoji:"🔥", gifDuration:1.2, sentence:"炼钢很辛苦。" },
  { char:"烤", pinyin:"kao3", radical:"火", components:["火","考"], meaning:"roast", emoji:"🍖", gifDuration:1.2, sentence:"我们在烤肉。" },
  { char:"烫", pinyin:"tang4", radical:"火", components:["汤","火"], meaning:"scald", emoji:"🌡️", gifDuration:1.2, sentence:"小心烫手！" },
  { char:"杆", pinyin:"gan1", radical:"木", components:["木","干"], meaning:"pole", emoji:"🏑", gifDuration:1.2, sentence:"旗杆很高。" },
  { char:"朵", pinyin:"duo3", radical:"木", components:["几","木"], meaning:"flower measure", emoji:"🌸", gifDuration:1.2, sentence:"一朵花。" },
  { char:"栖", pinyin:"qi1", radical:"木", components:["木","西"], meaning:"perch", emoji:"🐦", gifDuration:1.2, sentence:"鸟儿栖在树上。" },
  { char:"械", pinyin:"xie4", radical:"木", components:["木","戒"], meaning:"machinery", emoji:"⚙️", gifDuration:1.2, sentence:"机械坏了。" },
  { char:"榆", pinyin:"yu2", radical:"木", components:["木","俞"], meaning:"elm", emoji:"🌳", gifDuration:1.2, sentence:"榆树很高。" },

  // ───────────────── 🧑 Human & Social (more) ─────────────────
  { char:"仇", pinyin:"chou2", radical:"亻", components:["亻","九"], meaning:"hatred", emoji:"😠", gifDuration:1.2, sentence:"他们之间有仇。" },
  { char:"仍", pinyin:"reng2", radical:"亻", components:["亻","乃"], meaning:"still", emoji:"🕰️", gifDuration:1.2, sentence:"他仍然在工作。" },
  { char:"仪", pinyin:"yi2", radical:"亻", components:["亻","义"], meaning:"ceremony", emoji:"🎎", gifDuration:1.2, sentence:"仪式很隆重。" },
  { char:"仔", pinyin:"zai3", radical:"亻", components:["亻","子"], meaning:"young animal", emoji:"🐣", gifDuration:1.2, sentence:"牛仔很忙。" },
  { char:"伍", pinyin:"wu3", radical:"亻", components:["亻","五"], meaning:"squad", emoji:"👥", gifDuration:1.2, sentence:"队伍排得很长。" },
  { char:"仿", pinyin:"fang3", radical:"亻", components:["亻","方"], meaning:"imitate", emoji:"🗣️", gifDuration:1.2, sentence:"不要模仿别人。" },
  { char:"伪", pinyin:"wei3", radical:"亻", components:["亻","为"], meaning:"fake", emoji:"🎭", gifDuration:1.2, sentence:"这是伪钞。" },
  { char:"佣", pinyin:"yong1", radical:"亻", components:["亻","用"], meaning:"servant", emoji:"🧹", gifDuration:1.2, sentence:"他雇了一个佣人。" },
  { char:"奴", pinyin:"nu2", radical:"女", components:["女","又"], meaning:"slave", emoji:"⛓️", gifDuration:1.2, sentence:"废除奴隶制度。" },
  { char:"妆", pinyin:"zhuang1", radical:"女", components:["丬","女"], meaning:"makeup", emoji:"💄", gifDuration:1.2, sentence:"她正在化妆。" },
  { char:"孜", pinyin:"zi1", radical:"子", components:["子","攵"], meaning:"diligent", emoji:"📚", gifDuration:1.2, sentence:"学习要孜孜不倦。" },
  { char:"叨", pinyin:"dao1", radical:"口", components:["口","刀"], meaning:"chatter", emoji:"🗣️", gifDuration:1.2, sentence:"他老是唠叨。" },
  { char:"叭", pinyin:"ba1", radical:"口", components:["口","八"], meaning:"! sound", emoji:"🔊", gifDuration:1.2, sentence:"喇叭响了。" },
  { char:"咧", pinyin:"lie3", radical:"口", components:["口","列"], meaning:"grin", emoji:"😁", gifDuration:1.2, sentence:"他咧嘴笑了。" },
  { char:"唠", pinyin:"lao2", radical:"口", components:["口","劳"], meaning:"chatter", emoji:"💬", gifDuration:1.2, sentence:"别唠了。" },
  { char:"憾", pinyin:"han4", radical:"忄", components:["忄","感"], meaning:"regret", emoji:"😞", gifDuration:1.2, sentence:"很遗憾缺席。" },
  { char:"懒", pinyin:"lan3", radical:"忄", components:["忄","赖"], meaning:"lazy", emoji:"🦥", gifDuration:1.2, sentence:"他太懒了。" },
  { char:"惩", pinyin:"cheng2", radical:"心", components:["征","心"], meaning:"punish", emoji:"⚖️", gifDuration:1.2, sentence:"惩罚犯罪分子。" },

  // ───────────────── 🏠 Places & Buildings (more) ─────────────────
  { char:"宵", pinyin:"xiao1", radical:"宀", components:["宀","肖"], meaning:"night", emoji:"🌙", gifDuration:1.2, sentence:"元宵节快乐！" },
  { char:"寝", pinyin:"qin3", radical:"宀", components:["宀","爿","帚"], meaning:"sleep", emoji:"🛌", gifDuration:1.3, sentence:"就寝时间到了。" },
  { char:"寞", pinyin:"mo4", radical:"宀", components:["宀","莫"], meaning:"lonely", emoji:"😔", gifDuration:1.2, sentence:"我感到寂寞。" },
  { char:"寡", pinyin:"gua3", radical:"宀", components:["宀","頁","分"], meaning:"few", emoji:"1️⃣", gifDuration:1.3, sentence:"沉默寡言。" },
  { char:"察", pinyin:"cha2", radical:"宀", components:["宀","祭"], meaning:"examine", emoji:"🔍", gifDuration:1.2, sentence:"警察调查案件。" },
  { char:"庙", pinyin:"miao4", radical:"广", components:["广","由"], meaning:"temple", emoji:"⛩️", gifDuration:1.2, sentence:"寺庙里很安静。" },
  { char:"扇", pinyin:"shan4", radical:"户", components:["户","羽"], meaning:"fan", emoji:"🪭", gifDuration:1.2, sentence:"用电风扇。" },
  { char:"闯", pinyin:"chuang3", radical:"门", components:["门","马"], meaning:"rush", emoji:"🚪", gifDuration:1.2, sentence:"不要闯红灯！" },
  { char:"阅", pinyin:"yue4", radical:"门", components:["门","兑"], meaning:"read", emoji:"📖", gifDuration:1.2, sentence:"阅览室里很安静。" },
  { char:"阔", pinyin:"kuo4", radical:"门", components:["门","活"], meaning:"wide", emoji:"🌊", gifDuration:1.2, sentence:"视野很开阔。" },

  // ───────────────── 🎨 Arts & Tools (more) ─────────────────
  { char:"扰", pinyin:"rao3", radical:"扌", components:["扌","尤"], meaning:"disturb", emoji:"😵", gifDuration:1.2, sentence:"别打扰我。" },
  { char:"拒", pinyin:"ju4", radical:"扌", components:["扌","巨"], meaning:"refuse", emoji:"🙅", gifDuration:1.2, sentence:"他拒绝帮助。" },
  { char:"拔", pinyin:"ba2", radical:"扌", components:["扌","犮"], meaning:"pull out", emoji:"🥕", gifDuration:1.2, sentence:"拔萝卜。" },
  { char:"拆", pinyin:"chai1", radical:"扌", components:["扌","斥"], meaning:"dismantle", emoji:"🏚️", gifDuration:1.2, sentence:"拆房子。" },
  { char:"描", pinyin:"miao2", radical:"扌", components:["扌","苗"], meaning:"depict", emoji:"✍️", gifDuration:1.2, sentence:"她在描画。" },
  { char:"揭", pinyin:"jie1", radical:"扌", components:["扌","曷"], meaning:"uncover", emoji:"👀", gifDuration:1.2, sentence:"揭开秘密。" },
  { char:"揽", pinyin:"lan3", radical:"扌", components:["扌","览"], meaning:"grasp", emoji:"🤲", gifDuration:1.2, sentence:"他把活儿全揽了。" },
  { char:"刊", pinyin:"kan1", radical:"刂", components:["干","刂"], meaning:"publish", emoji:"📰", gifDuration:1.2, sentence:"这本杂志每周刊。" },
  { char:"则", pinyin:"ze2", radical:"刂", components:["贝","刂"], meaning:"rule", emoji:"📏", gifDuration:1.2, sentence:"遵守规则。" },
  { char:"删", pinyin:"shan1", radical:"刂", components:["册","刂"], meaning:"delete", emoji:"🗑️", gifDuration:1.2, sentence:"删掉文件。" },
  { char:"诺", pinyin:"nuo4", radical:"讠", components:["讠","若"], meaning:"promise", emoji:"🤝", gifDuration:1.2, sentence:"一诺千金。" },
  { char:"谋", pinyin:"mou2", radical:"讠", components:["讠","某"], meaning:"plan", emoji:"📝", gifDuration:1.2, sentence:"阴谋诡计。" },
  { char:"谤", pinyin:"bang4", radical:"讠", components:["讠","旁"], meaning:"slander", emoji:"🗣️", gifDuration:1.2, sentence:"不要诽谤别人。" },
  { char:"谦", pinyin:"qian1", radical:"讠", components:["讠","兼"], meaning:"modest", emoji:"😌", gifDuration:1.2, sentence:"谦虚使人进步。" },
  { char:"谨", pinyin:"jin3", radical:"讠", components:["讠","堇"], meaning:"cautious", emoji:"🧐", gifDuration:1.2, sentence:"小心谨慎。" },
  { char:"钞", pinyin:"chao1", radical:"钅", components:["钅","少"], meaning:"banknote", emoji:"💵", gifDuration:1.2, sentence:"钞票很多。" },
  { char:"钓", pinyin:"diao4", radical:"钅", components:["钅","勺"], meaning:"fishhook", emoji:"🎣", gifDuration:1.2, sentence:"钓鱼很放松。" },
  { char:"铭", pinyin:"ming2", radical:"钅", components:["钅","名"], meaning:"inscribe", emoji:"🏅", gifDuration:1.2, sentence:"铭记在心。" },
  { char:"错", pinyin:"cuo4", radical:"钅", components:["钅","昔"], meaning:"wrong", emoji:"❌", gifDuration:1.2, sentence:"我做错了。" },
  { char:"锤", pinyin:"chui2", radical:"钅", components:["钅","垂"], meaning:"hammer", emoji:"🔨", gifDuration:1.2, sentence:"用锤子敲。" },
  { char:"锁", pinyin:"suo3", radical:"钅", components:["钅","肖"], meaning:"lock", emoji:"🔐", gifDuration:1.2, sentence:"锁上门。" },
  { char:"锐", pinyin:"rui4", radical:"钅", components:["钅","兑"], meaning:"sharp", emoji:"🗡️", gifDuration:1.2, sentence:"刀很锐利。" },
  { char:"镜", pinyin:"jing4", radical:"钅", components:["钅","竟"], meaning:"mirror", emoji:"🪞", gifDuration:1.2, sentence:"照镜子。" },

  // ───────────────── 🧠 Body & Health (more) ─────────────────
  { char:"眯", pinyin:"mi1", radical:"目", components:["目","米"], meaning:"squint", emoji:"😑", gifDuration:1.2, sentence:"他眯着眼睛。" },
  { char:"瞧", pinyin:"qiao2", radical:"目", components:["目","焦"], meaning:"look", emoji:"👀", gifDuration:1.2, sentence:"瞧一瞧看一看。" },
  { char:"瞪", pinyin:"deng4", radical:"目", components:["目","登"], meaning:"stare", emoji:"😳", gifDuration:1.2, sentence:"他瞪着我。" },
  { char:"躬", pinyin:"gong1", radical:"身", components:["身","弓"], meaning:"bow", emoji:"🙇", gifDuration:1.2, sentence:"鞠躬行礼。" },
  { char:"疲", pinyin:"pi2", radical:"疒", components:["疒","皮"], meaning:"tired", emoji:"😴", gifDuration:1.2, sentence:"工作很疲劳。" },
  { char:"疼", pinyin:"teng2", radical:"疒", components:["疒","冬"], meaning:"painful", emoji:"😣", gifDuration:1.2, sentence:"我头疼。" },
  { char:"虚", pinyin:"xu1", radical:"虍", components:["虍","业"], meaning:"empty/weak", emoji:"😶", gifDuration:1.2, sentence:"身体虚弱。" },

  // ───────────────── 🐅 Animals (more) ─────────────────
  { char:"狡", pinyin:"jiao3", radical:"犭", components:["犭","交"], meaning:"crafty", emoji:"🦊", gifDuration:1.2, sentence:"狡猾的狐狸。" },
  { char:"猾", pinyin:"hua2", radical:"犭", components:["犭","骨"], meaning:"sly", emoji:"🐍", gifDuration:1.2, sentence:"老奸巨猾。" },
  { char:"猩", pinyin:"xing1", radical:"犭", components:["犭","星"], meaning:"orangutan", emoji:"🦧", gifDuration:1.2, sentence:"大猩猩很聪明。" },
  { char:"猿", pinyin:"yuan2", radical:"犭", components:["犭","袁"], meaning:"ape", emoji:"🦍", gifDuration:1.2, sentence:"猿猴很高。" },
  { char:"驻", pinyin:"zhu4", radical:"马", components:["马","主"], meaning:"station", emoji:"🏠", gifDuration:1.2, sentence:"军队驻扎。" },
  { char:"骆", pinyin:"luo4", radical:"马", components:["马","各"], meaning:"camel", emoji:"🐫", gifDuration:1.2, sentence:"骑骆驼。" },
  { char:"驼", pinyin:"tuo2", radical:"马", components:["马","它"], meaning:"camel", emoji:"🐪", gifDuration:1.2, sentence:"沙漠之舟是骆驼。" },
  { char:"骗", pinyin:"pian4", radical:"马", components:["马","扁"], meaning:"cheat", emoji:"🤥", gifDuration:1.2, sentence:"不要骗人。" },
  { char:"鸦", pinyin:"ya1", radical:"鸟", components:["牙","鸟"], meaning:"crow", emoji:"🐦‍⬛", gifDuration:1.2, sentence:"乌鸦很聪明。" },
  { char:"鲍", pinyin:"bao4", radical:"鱼", components:["鱼","包"], meaning:"abalone", emoji:"🐟", gifDuration:1.2, sentence:"鲍鱼很贵。" },
  { char:"鲁", pinyin:"lu3", radical:"鱼", components:["鱼","日"], meaning:"rash", emoji:"🥢", gifDuration:1.2, sentence:"他很鲁莽。" },
  { char:"蠹", pinyin:"du4", radical:"虫", components:["木","蛀","虫"], meaning:"bookworm", emoji:"🐛", gifDuration:1.3, sentence:"书被虫蠹了。" },
  { char:"蝇", pinyin:"ying2", radical:"虫", components:["虫","黾"], meaning:"fly", emoji:"🪰", gifDuration:1.2, sentence:"苍蝇很讨厌。" },
  { char:"螳", pinyin:"tang2", radical:"虫", components:["虫","堂"], meaning:"mantis", emoji:"🦗", gifDuration:1.2, sentence:"螳螂捕蝉。" },
  { char:"蝉", pinyin:"chan2", radical:"虫", components:["虫","单"], meaning:"cicada", emoji:"🦗", gifDuration:1.2, sentence:"夏天蝉鸣。" },

  // ───────────────── 🍚 Food & Drink (more) ─────────────────
  { char:"饥", pinyin:"ji1", radical:"饣", components:["饣","几"], meaning:"hungry", emoji:"🫄", gifDuration:1.2, sentence:"饥寒交迫。" },
  { char:"秧", pinyin:"yang1", radical:"禾", components:["禾","央"], meaning:"rice seedling", emoji:"🌱", gifDuration:1.2, sentence:"插秧很辛苦。" },
  { char:"稻", pinyin:"dao4", radical:"禾", components:["禾","舀"], meaning:"paddy", emoji:"🌾", gifDuration:1.2, sentence:"稻田金黄。" },
  { char:"稿", pinyin:"gao3", radical:"禾", components:["禾","高"], meaning:"manuscript", emoji:"📝", gifDuration:1.2, sentence:"交稿日期到了。" },
  { char:"稼", pinyin:"jia4", radical:"禾", components:["禾","家"], meaning:"crops", emoji:"🌾", gifDuration:1.2, sentence:"庄稼长得很好。" },
  { char:"穗", pinyin:"sui4", radical:"禾", components:["禾","惠"], meaning:"ear of grain", emoji:"🌾", gifDuration:1.2, sentence:"麦穗饱满。" },
  { char:"粮", pinyin:"liang2", radical:"米", components:["米","良"], meaning:"grain", emoji:"🌾", gifDuration:1.2, sentence:"粮食储备。" },
  { char:"糯", pinyin:"nuo4", radical:"米", components:["米","需"], meaning:"glutinous", emoji:"🍡", gifDuration:1.2, sentence:"糯米很黏。" },
  { char:"糕", pinyin:"gao1", radical:"米", components:["米","羔"], meaning:"cake", emoji:"🍰", gifDuration:1.2, sentence:"生日蛋糕。" },
  { char:"糖", pinyin:"tang2", radical:"米", components:["米","唐"], meaning:"sugar", emoji:"🍬", gifDuration:1.2, sentence:"太多糖不健康。" },
  { char:"酒", pinyin:"jiu3", radical:"酉", components:["氵","酉"], meaning:"alcohol", emoji:"🍶", gifDuration:1.2, sentence:"喝酒不开车。" },
  { char:"酸", pinyin:"suan1", radical:"酉", components:["酉","夋"], meaning:"sour", emoji:"🍋", gifDuration:1.2, sentence:"柠檬很酸。" },
  { char:"醋", pinyin:"cu4", radical:"酉", components:["酉","昔"], meaning:"vinegar", emoji:"🍶", gifDuration:1.2, sentence:"吃饺子蘸醋。" },
  { char:"酱", pinyin:"jiang4", radical:"酉", components:["爿","夕","酉"], meaning:"sauce", emoji:"🍛", gifDuration:1.3, sentence:"酱油是调味品。" },

  // ───────────────── 👗 Clothing (more) ─────────────────
  { char:"袍", pinyin:"pao2", radical:"衤", components:["衤","包"], meaning:"robe", emoji:"🥋", gifDuration:1.2, sentence:"长袍马褂。" },
  { char:"袖", pinyin:"xiu4", radical:"衤", components:["衤","由"], meaning:"sleeve", emoji:"👔", gifDuration:1.2, sentence:"袖手旁观。" },
  { char:"袜", pinyin:"wa4", radical:"衤", components:["衤","末"], meaning:"sock", emoji:"🧦", gifDuration:1.2, sentence:"穿袜子。" },
  { char:"帐", pinyin:"zhang4", radical:"巾", components:["巾","长"], meaning:"curtain", emoji:"🛏️", gifDuration:1.2, sentence:"蚊帐。" },
  { char:"帖", pinyin:"tie3", radical:"巾", components:["巾","占"], meaning:"card", emoji:"📋", gifDuration:1.2, sentence:"请帖。" },
  { char:"帆", pinyin:"fan1", radical:"巾", components:["巾","凡"], meaning:"sail", emoji:"⛵", gifDuration:1.2, sentence:"一帆风顺。" },
  { char:"裁", pinyin:"cai2", radical:"衣", components:["𢦏","衣"], meaning:"cut fabric", emoji:"✂️", gifDuration:1.2, sentence:"裁剪衣服。" },
  { char:"裂", pinyin:"lie4", radical:"衣", components:["列","衣"], meaning:"split", emoji:"🧥", gifDuration:1.2, sentence:"衣服裂开了。" },

  // ───────────────── 📚 Study & Knowledge (more) ─────────────────
  { char:"签", pinyin:"qian1", radical:"竹", components:["⺮","佥"], meaning:"sign", emoji:"🖊️", gifDuration:1.2, sentence:"请签名。" },
  { char:"簿", pinyin:"bu4", radical:"竹", components:["⺮","薄"], meaning:"notebook", emoji:"📓", gifDuration:1.2, sentence:"账簿。" },
  { char:"簇", pinyin:"cu4", radical:"竹", components:["⺮","族"], meaning:"cluster", emoji:"💐", gifDuration:1.2, sentence:"一簇鲜花。" },
  { char:"票", pinyin:"piao4", radical:"示", components:["西","示"], meaning:"ticket", emoji:"🎫", gifDuration:1.2, sentence:"买了票。" },
  { char:"禁", pinyin:"jin4", radical:"示", components:["林","示"], meaning:"prohibit", emoji:"🚫", gifDuration:1.2, sentence:"禁止吸烟。" },
  { char:"祸", pinyin:"huo4", radical:"示", components:["示","咼"], meaning:"disaster", emoji:"🔥", gifDuration:1.2, sentence:"祸不单行。" },
  { char:"规", pinyin:"gui1", radical:"见", components:["夫","见"], meaning:"rule", emoji:"📏", gifDuration:1.2, sentence:"遵守规定。" },
  { char:"觅", pinyin:"mi4", radical:"见", components:["爫","见"], meaning:"seek", emoji:"🔍", gifDuration:1.2, sentence:"觅食。" },
  { char:"览", pinyin:"lan3", radical:"见", components:["斩","见"], meaning:"view", emoji:"🖼️", gifDuration:1.2, sentence:"展览。" },
  { char:"竣", pinyin:"jun4", radical:"立", components:["立","夋"], meaning:"finish", emoji:"🏁", gifDuration:1.2, sentence:"工程竣工。" },
  { char:"靖", pinyin:"jing4", radical:"青", components:["立","青"], meaning:"peaceful", emoji:"🕊️", gifDuration:1.2, sentence:"边境绥靖。" },

  // ───────────────── 😌 Emotions & Mind (more) ─────────────────
  { char:"惦", pinyin:"dian4", radical:"忄", components:["忄","店"], meaning:"worry", emoji:"😟", gifDuration:1.2, sentence:"我惦念他。" },
  { char:"懊", pinyin:"ao4", radical:"忄", components:["忄","奥"], meaning:"regret", emoji:"😩", gifDuration:1.2, sentence:"很懊悔。" },
  { char:"憔", pinyin:"qiao2", radical:"忄", components:["忄","焦"], meaning:"haggard", emoji:"😔", gifDuration:1.2, sentence:"面容憔悴。" },
  { char:"恿", pinyin:"yong3", radical:"心", components:["甬","心"], meaning:"urge", emoji:"🤨", gifDuration:1.2, sentence:"怂恿别人。" },
  { char:"您", pinyin:"nin2", radical:"心", components:["你","心"], meaning:"you polite", emoji:"🙇", gifDuration:1.2, sentence:"您好！" },

  // ───────────────── 🧮 Objects & Materials (more) ─────────────────
  { char:"轿", pinyin:"jiao4", radical:"车", components:["车","乔"], meaning:"sedan chair", emoji:"🛕", gifDuration:1.2, sentence:"花轿。" },
  { char:"辐", pinyin:"fu2", radical:"车", components:["车","畐"], meaning:"spoke", emoji:"☢️", gifDuration:1.2, sentence:"辐射。" },
  { char:"辑", pinyin:"ji2", radical:"车", components:["车","咠"], meaning:"compile", emoji:"📚", gifDuration:1.2, sentence:"编辑文件。" },
  { char:"舰", pinyin:"jian4", radical:"舟", components:["舟","见"], meaning:"warship", emoji:"🛳️", gifDuration:1.2, sentence:"航空母舰。" },
  { char:"舶", pinyin:"bo2", radical:"舟", components:["舟","白"], meaning:"ocean ship", emoji:"🚢", gifDuration:1.2, sentence:"舶来品。" },
  { char:"艇", pinyin:"ting3", radical:"舟", components:["舟","廷"], meaning:"small boat", emoji:"🚤", gifDuration:1.2, sentence:"快艇。" },
  { char:"瓯", pinyin:"ou1", radical:"瓦", components:["区","瓦"], meaning:"basin", emoji:"🥣", gifDuration:1.2, sentence:"瓷瓯。" },
  { char:"甄", pinyin:"zhen1", radical:"瓦", components:["垔","瓦"], meaning:"distinguish", emoji:"🔍", gifDuration:1.2, sentence:"甄别。" },
  { char:"贺", pinyin:"he4", radical:"贝", components:["加","贝"], meaning:"congratulate", emoji:"🎉", gifDuration:1.2, sentence:"祝贺你！" },
  { char:"贷", pinyin:"dai4", radical:"贝", components:["代","贝"], meaning:"loan", emoji:"🏦", gifDuration:1.2, sentence:"银行贷款。" },
  { char:"贸", pinyin:"mao4", radical:"贝", components:["卯","贝"], meaning:"trade", emoji:"🤝", gifDuration:1.2, sentence:"对外贸易。" },
  { char:"赊", pinyin:"she1", radical:"贝", components:["佘","贝"], meaning:"buy on credit", emoji:"💳", gifDuration:1.2, sentence:"赊账。" },
  { char:"赈", pinyin:"zhen4", radical:"贝", components:["辰","贝"], meaning:"relief", emoji:"🎁", gifDuration:1.2, sentence:"赈灾。" },
  { char:"赌", pinyin:"du3", radical:"贝", components:["者","贝"], meaning:"gamble", emoji:"🎰", gifDuration:1.2, sentence:"赌博有害。" },
  { char:"劫", pinyin:"jie2", radical:"力", components:["去","力"], meaning:"rob", emoji:"🦹", gifDuration:1.2, sentence:"抢劫银行。" },
  { char:"勘", pinyin:"kan1", radical:"力", components:["甚","力"], meaning:"survey", emoji:"🗺️", gifDuration:1.2, sentence:"勘探石油。" },
  { char:"募", pinyin:"mu4", radical:"力", components:["莫","力"], meaning:"raise", emoji:"💰", gifDuration:1.2, sentence:"募捐。" },
  { char:"叙", pinyin:"xu4", radical:"又", components:["余","又"], meaning:"narrate", emoji:"📖", gifDuration:1.2, sentence:"叙述故事。" },
  { char:"叛", pinyin:"pan4", radical:"又", components:["半","反"], meaning:"rebel", emoji:"⚔️", gifDuration:1.2, sentence:"叛变。" },
  { char:"墓", pinyin:"mu4", radical:"土", components:["莫","土"], meaning:"tomb", emoji:"🪦", gifDuration:1.2, sentence:"扫墓。" },
  { char:"壁", pinyin:"bi4", radical:"土", components:["辟","土"], meaning:"wall", emoji:"🧱", gifDuration:1.2, sentence:"墙壁很厚。" },
  { char:"雇", pinyin:"gu4", radical:"隹", components:["户","隹"], meaning:"employ", emoji:"💼", gifDuration:1.2, sentence:"雇佣工人。" },

  // ───────────────── 🌍 Miscellaneous useful ─────────────────
  { char:"矛", pinyin:"mao2", radical:"矛", components:[], meaning:"spear", emoji:"🗡️", gifDuration:1, sentence:"矛盾。" },
  { char:"盾", pinyin:"dun4", radical:"目", components:["厂","十","目"], meaning:"shield", emoji:"🛡️", gifDuration:1.2, sentence:"矛盾。" },
  { char:"乖", pinyin:"guai1", radical:"丿", components:["千","北"], meaning:"well-behaved", emoji:"😇", gifDuration:1.2, sentence:"乖孩子。" },
  { char:"乘", pinyin:"cheng2", radical:"丿", components:["禾","北"], meaning:"ride", emoji:"🚌", gifDuration:1.2, sentence:"乘车。" },
  { char:"举", pinyin:"ju3", radical:"丶", components:["兴","丰"], meaning:"raise", emoji:"🙋", gifDuration:1.2, sentence:"举手。" },
  { char:"乃", pinyin:"nai3", radical:"丿", components:[], meaning:"then", emoji:"⏭️", gifDuration:1, sentence:"乃是。" },
  { char:"乏", pinyin:"fa2", radical:"丿", components:[], meaning:"tired", emoji:"😴", gifDuration:1, sentence:"缺乏。" },
  { char:"乌", pinyin:"wu1", radical:"丿", components:[], meaning:"crow", emoji:"🐦‍⬛", gifDuration:1, sentence:"乌鸦。" },
  { char:"乍", pinyin:"zha4", radical:"丿", components:[], meaning:"sudden", emoji:"⚡", gifDuration:1, sentence:"乍一看。" },
  { char:"乎", pinyin:"hu1", radical:"丿", components:[], meaning:"interrogative", emoji:"❓", gifDuration:1, sentence:"在乎吗？" },
  { char:"乐", pinyin:"le4", radical:"丿", components:[], meaning:"happy/music", emoji:"😄", gifDuration:1, sentence:"快乐。" },
  { char:"乔", pinyin:"qiao2", radical:"丿", components:[], meaning:"tall", emoji:"🌲", gifDuration:1, sentence:"乔木。" },
  { char:"参", pinyin:"can1", radical:"厶", components:["厶","大","彡"], meaning:"participate", emoji:"🙋", gifDuration:1.3, sentence:"参加比赛。" },
  { char:"弱", pinyin:"ruo4", radical:"弓", components:["弓","冫"], meaning:"weak", emoji:"😔", gifDuration:1.2, sentence:"身体虚弱。" },
  { char:"强", pinyin:"qiang2", radical:"弓", components:["弓","虽"], meaning:"strong", emoji:"💪", gifDuration:1.2, sentence:"强大。" },
  { char:"弹", pinyin:"dan4", radical:"弓", components:["弓","单"], meaning:"bullet", emoji:"💣", gifDuration:1.2, sentence:"子弹。" },
  { char:"张", pinyin:"zhang1", radical:"弓", components:["弓","长"], meaning:"open up", emoji:"📈", gifDuration:1.2, sentence:"张开嘴。" },
  { char:"引", pinyin:"yin3", radical:"弓", components:["弓","丨"], meaning:"pull", emoji:"🧲", gifDuration:1.2, sentence:"引导。" },
  { char:"弗", pinyin:"fu2", radical:"弓", components:["弓","丿"], meaning:"not", emoji:"🚫", gifDuration:1.2, sentence:"弗能。" },
  { char:"弘", pinyin:"hong2", radical:"弓", components:["弓","厶"], meaning:"vast", emoji:"🌊", gifDuration:1.2, sentence:"弘扬。" },
  { char:"弛", pinyin:"chi2", radical:"弓", components:["弓","也"], meaning:"relax", emoji:"😌", gifDuration:1.2, sentence:"松弛。" },
  { char:"弟", pinyin:"di4", radical:"弓", components:["弓","丷"], meaning:"younger brother", emoji:"👦", gifDuration:1.2, sentence:"弟弟。" },
  { char:"弦", pinyin:"xian2", radical:"弓", components:["弓","玄"], meaning:"string", emoji:"🎻", gifDuration:1.2, sentence:"弓弦。" },
  { char:"弧", pinyin:"hu2", radical:"弓", components:["弓","瓜"], meaning:"arc", emoji:"🌈", gifDuration:1.2, sentence:"弧形。" },
  { char:"弯", pinyin:"wan1", radical:"弓", components:["亦","弓"], meaning:"bend", emoji:"↩️", gifDuration:1.2, sentence:"弯路。" },
  { char:"弥", pinyin:"mi2", radical:"弓", components:["弓","尔"], meaning:"full", emoji:"🈵", gifDuration:1.2, sentence:"弥漫。" },
  { char:"弼", pinyin:"bi4", radical:"弓", components:["弜","口","车"], meaning:"assist", emoji:"🤝", gifDuration:1.3, sentence:"辅弼。" },
  { char:"疆", pinyin:"jiang1", radical:"田", components:["弓","土","畺"], meaning:"border", emoji:"🗺️", gifDuration:1.3, sentence:"边疆。" },
];

// Total in this file: 300