const charactersPart7 = [
  // ───────────────── 🌿 Nature & Elements (more solids, gases) ─────────────────
  { char:"氕", pinyin:"pie1", radical:"气", components:["气","丿"], meaning:"protium", emoji:"⚛️", gifDuration:1.2, sentence:"氕核。" },
  { char:"氘", pinyin:"dao1", radical:"气", components:["气","丨"], meaning:"deuterium", emoji:"⚛️", gifDuration:1.2, sentence:"氘核。" },
  { char:"氙", pinyin:"xian1", radical:"气", components:["气","山"], meaning:"xenon", emoji:"💡", gifDuration:1.2, sentence:"氙气灯。" },
  { char:"氚", pinyin:"chuan1", radical:"气", components:["气","川"], meaning:"tritium", emoji:"⚛️", gifDuration:1.2, sentence:"氚水。" },
  { char:"氜", pinyin:"ri4", radical:"气", components:["气","日"], meaning:"helium", emoji:"🎈", gifDuration:1.2, sentence:"氜气。" },
  { char:"氛", pinyin:"fen1", radical:"气", components:["气","分"], meaning:"atmosphere", emoji:"🌬️", gifDuration:1.2, sentence:"氛围。" },
  { char:"氟", pinyin:"fu2", radical:"气", components:["气","弗"], meaning:"fluorine", emoji:"🦷", gifDuration:1.2, sentence:"氟化物。" },
  { char:"氪", pinyin:"ke4", radical:"气", components:["气","克"], meaning:"krypton", emoji:"🟢", gifDuration:1.2, sentence:"氪金。" },
  { char:"氖", pinyin:"nai3", radical:"气", components:["气","乃"], meaning:"neon", emoji:"🟡", gifDuration:1.2, sentence:"氖灯。" },
  { char:"氡", pinyin:"dong1", radical:"气", components:["气","冬"], meaning:"radon", emoji:"☢️", gifDuration:1.2, sentence:"氡气。" },
  { char:"氩", pinyin:"ya4", radical:"气", components:["气","亚"], meaning:"argon", emoji:"🟣", gifDuration:1.2, sentence:"氩弧焊。" },
  { char:"氤", pinyin:"yin1", radical:"气", components:["气","因"], meaning:"misty", emoji:"🌁", gifDuration:1.2, sentence:"氤氲。" },
  { char:"氲", pinyin:"yun1", radical:"气", components:["气","昷"], meaning:"thick", emoji:"🌫️", gifDuration:1.2, sentence:"氤氲。" },
  { char:"氵", pinyin:"shui3", radical:"氵", components:[], meaning:"water radical", emoji:"💧", gifDuration:1, sentence:"三点水。" },
  { char:"氾", pinyin:"fan4", radical:"氵", components:["氵","㔾"], meaning:"flood", emoji:"🌊", gifDuration:1.2, sentence:"氾滥。" },
  { char:"氿", pinyin:"gui3", radical:"氵", components:["氵","九"], meaning:"spring", emoji:"⛲", gifDuration:1.2, sentence:"氿泉。" },
  { char:"汀", pinyin:"ting1", radical:"氵", components:["氵","丁"], meaning:"sandbank", emoji:"🏝️", gifDuration:1.2, sentence:"汀洲。" },
  { char:"汁", pinyin:"zhi1", radical:"氵", components:["氵","十"], meaning:"juice", emoji:"🧃", gifDuration:1.2, sentence:"果汁。" },
  { char:"汇", pinyin:"hui4", radical:"氵", components:["氵","匚"], meaning:"converge", emoji:"🤝", gifDuration:1.2, sentence:"汇合。" },
  { char:"汉", pinyin:"han4", radical:"氵", components:["氵","又"], meaning:"Han", emoji:"🇨🇳", gifDuration:1.2, sentence:"汉字。" },
  { char:"汈", pinyin:"diao1", radical:"氵", components:["氵","刁"], meaning:"Diao River", emoji:"🏞️", gifDuration:1.2, sentence:"汈水。" },
  { char:"泛", pinyin:"fan4", radical:"氵", components:["氵","乏"], meaning:"float", emoji:"🛶", gifDuration:1.2, sentence:"广泛。" },
  { char:"汍", pinyin:"wan2", radical:"氵", components:["氵","丸"], meaning:"shed tears", emoji:"😢", gifDuration:1.2, sentence:"汍澜。" },
  { char:"汎", pinyin:"fan4", radical:"氵", components:["氵","凡"], meaning:"wide", emoji:"🌊", gifDuration:1.2, sentence:"汎爱。" },
  { char:"汏", pinyin:"tai4", radical:"氵", components:["氵","大"], meaning:"cleanse", emoji:"🧼", gifDuration:1.2, sentence:"汏洗。" },
  { char:"汐", pinyin:"xi1", radical:"氵", components:["氵","夕"], meaning:"night tide", emoji:"🌊", gifDuration:1.2, sentence:"潮汐。" },
  { char:"汔", pinyin:"qi4", radical:"氵", components:["氵","气"], meaning:"almost", emoji:"🤏", gifDuration:1.2, sentence:"汔此。" },
  { char:"汕", pinyin:"shan4", radical:"氵", components:["氵","山"], meaning:"Swatow", emoji:"🏙️", gifDuration:1.2, sentence:"汕头。" },
  { char:"汗", pinyin:"han4", radical:"氵", components:["氵","干"], meaning:"sweat", emoji:"💦", gifDuration:1.2, sentence:"流汗。" },
  { char:"沆", pinyin:"hang4", radical:"氵", components:["氵","亢"], meaning:"vast", emoji:"🌊", gifDuration:1.2, sentence:"沆瀣一气。" },
  { char:"沈", pinyin:"shen3", radical:"氵", components:["氵","冘"], meaning:"sink", emoji:"⬇️", gifDuration:1.2, sentence:"沈阳。" },
  { char:"沉", pinyin:"chen2", radical:"氵", components:["氵","冗"], meaning:"sink", emoji:"🌊", gifDuration:1.2, sentence:"沉默。" },
  { char:"沌", pinyin:"dun4", radical:"氵", components:["氵","屯"], meaning:"chaos", emoji:"🌀", gifDuration:1.2, sentence:"混沌。" },
  { char:"沍", pinyin:"hu4", radical:"氵", components:["氵","互"], meaning:"frozen", emoji:"❄️", gifDuration:1.2, sentence:"凝沍。" },
  { char:"沏", pinyin:"qi1", radical:"氵", components:["氵","切"], meaning:"infuse", emoji:"🍵", gifDuration:1.2, sentence:"沏茶。" },
  { char:"沐", pinyin:"mu4", radical:"氵", components:["氵","木"], meaning:"bathe", emoji:"🛀", gifDuration:1.2, sentence:"沐浴。" },
  { char:"沔", pinyin:"mian3", radical:"氵", components:["氵","丏"], meaning:"flood", emoji:"🌊", gifDuration:1.2, sentence:"沔水。" },
  { char:"沛", pinyin:"pei4", radical:"氵", components:["氵","市"], meaning:"copious", emoji:"💧", gifDuration:1.2, sentence:"充沛。" },
  { char:"沗", pinyin:"hong2", radical:"氵", components:["氵","太"], meaning:"vast", emoji:"🌊", gifDuration:1.2, sentence:"沗水。" },
  { char:"沘", pinyin:"bi3", radical:"氵", components:["氵","比"], meaning:"Bi River", emoji:"🏞️", gifDuration:1.2, sentence:"沘水。" },
  { char:"沙", pinyin:"sha1", radical:"氵", components:["氵","少"], meaning:"sand", emoji:"🏖️", gifDuration:1.2, sentence:"沙子。" },
  { char:"沚", pinyin:"zhi3", radical:"氵", components:["氵","止"], meaning:"islet", emoji:"🏝️", gifDuration:1.2, sentence:"水中沚。" },
  { char:"洵", pinyin:"xun2", radical:"氵", components:["氵","旬"], meaning:"true", emoji:"✅", gifDuration:1.2, sentence:"洵属事实。" },
  { char:"洹", pinyin:"huan2", radical:"氵", components:["氵","亘"], meaning:"Huan River", emoji:"🏞️", gifDuration:1.2, sentence:"洹水。" },
  { char:"洺", pinyin:"ming2", radical:"氵", components:["氵","名"], meaning:"Ming River", emoji:"🏞️", gifDuration:1.2, sentence:"洺河。" },
  { char:"活", pinyin:"huo2", radical:"氵", components:["氵","舌"], meaning:"live", emoji:"🧬", gifDuration:1.2, sentence:"生活。" },
  { char:"洼", pinyin:"wa1", radical:"氵", components:["氵","圭"], meaning:"hollow", emoji:"🕳️", gifDuration:1.2, sentence:"洼地。" },
  { char:"洽", pinyin:"qia4", radical:"氵", components:["氵","合"], meaning:"negotiate", emoji:"🤝", gifDuration:1.2, sentence:"洽谈。" },
  { char:"派", pinyin:"pai4", radical:"氵", components:["氵","辰"], meaning:"faction", emoji:"👥", gifDuration:1.2, sentence:"党派。" },
  { char:"浔", pinyin:"xun2", radical:"氵", components:["氵","寻"], meaning:"water's edge", emoji:"🏞️", gifDuration:1.2, sentence:"江浔。" },
  { char:"洛", pinyin:"luo4", radical:"氵", components:["氵","各"], meaning:"Luo River", emoji:"🏞️", gifDuration:1.2, sentence:"洛阳。" },
  { char:"浏", pinyin:"liu2", radical:"氵", components:["氵","刘"], meaning:"clear", emoji:"👀", gifDuration:1.2, sentence:"浏览。" },
  { char:"济", pinyin:"ji4", radical:"氵", components:["氵","齐"], meaning:"help", emoji:"🆘", gifDuration:1.2, sentence:"救济。" },
  { char:"浑", pinyin:"hun2", radical:"氵", components:["氵","军"], meaning:"muddy", emoji:"🌫️", gifDuration:1.2, sentence:"浑身。" },
  { char:"浓", pinyin:"nong2", radical:"氵", components:["氵","农"], meaning:"dense", emoji:"☕", gifDuration:1.2, sentence:"浓茶。" },
  { char:"浙", pinyin:"zhe4", radical:"氵", components:["氵","折"], meaning:"Zhejiang", emoji:"🏙️", gifDuration:1.2, sentence:"浙江。" },
  { char:"浚", pinyin:"jun4", radical:"氵", components:["氵","夋"], meaning:"dredge", emoji:"🚜", gifDuration:1.2, sentence:"疏浚。" },
  { char:"浣", pinyin:"huan4", radical:"氵", components:["氵","完"], meaning:"wash", emoji:"🧼", gifDuration:1.2, sentence:"浣衣。" },
  { char:"浦", pinyin:"pu3", radical:"氵", components:["氵","甫"], meaning:"river bank", emoji:"🏞️", gifDuration:1.2, sentence:"黄浦江。" },
  { char:"浩", pinyin:"hao4", radical:"氵", components:["氵","告"], meaning:"vast", emoji:"🌊", gifDuration:1.2, sentence:"浩大。" },
  { char:"浪", pinyin:"lang4", radical:"氵", components:["氵","良"], meaning:"wave", emoji:"🌊", gifDuration:1.2, sentence:"浪费。" },
  { char:"浮", pinyin:"fu2", radical:"氵", components:["氵","孚"], meaning:"float", emoji:"🫧", gifDuration:1.2, sentence:"浮动。" },
  { char:"浴", pinyin:"yu4", radical:"氵", components:["氵","谷"], meaning:"bathe", emoji:"🚿", gifDuration:1.2, sentence:"浴室。" },
  { char:"浸", pinyin:"jin4", radical:"氵", components:["氵","曼"], meaning:"soak", emoji:"💧", gifDuration:1.2, sentence:"浸泡。" },
  { char:"涂", pinyin:"tu2", radical:"氵", components:["氵","余"], meaning:"paint", emoji:"🎨", gifDuration:1.2, sentence:"涂抹。" },
  { char:"涅", pinyin:"nie4", radical:"氵", components:["氵","日","土"], meaning:"black dye", emoji:"🖤", gifDuration:1.2, sentence:"涅磐。" },
  { char:"消", pinyin:"xiao1", radical:"氵", components:["氵","肖"], meaning:"disappear", emoji:"🌫️", gifDuration:1.2, sentence:"消灭。" },
  { char:"涉", pinyin:"she4", radical:"氵", components:["氵","步"], meaning:"wade", emoji:"👣", gifDuration:1.2, sentence:"涉及。" },
  { char:"涌", pinyin:"yong3", radical:"氵", components:["氵","甬"], meaning:"gush", emoji:"⛲", gifDuration:1.2, sentence:"涌现。" },
  { char:"涕", pinyin:"ti4", radical:"氵", components:["氵","弟"], meaning:"tears", emoji:"😢", gifDuration:1.2, sentence:"鼻涕。" },
  { char:"涛", pinyin:"tao1", radical:"氵", components:["氵","寿"], meaning:"billows", emoji:"🌊", gifDuration:1.2, sentence:"波涛。" },
  { char:"涡", pinyin:"wo1", radical:"氵", components:["氵","咼"], meaning:"whirlpool", emoji:"🌀", gifDuration:1.2, sentence:"漩涡。" },
  { char:"润", pinyin:"run4", radical:"氵", components:["氵","闰"], meaning:"moist", emoji:"💦", gifDuration:1.2, sentence:"滋润。" },
  { char:"涨", pinyin:"zhang3", radical:"氵", components:["氵","张"], meaning:"rise", emoji:"📈", gifDuration:1.2, sentence:"涨价。" },
  { char:"涩", pinyin:"se4", radical:"氵", components:["氵","歮"], meaning:"astringent", emoji:"🍋", gifDuration:1.2, sentence:"苦涩。" },
  { char:"涯", pinyin:"ya2", radical:"氵", components:["氵","厓"], meaning:"shore", emoji:"🏖️", gifDuration:1.2, sentence:"天涯。" },
  { char:"液", pinyin:"ye4", radical:"氵", components:["氵","夜"], meaning:"liquid", emoji:"🧪", gifDuration:1.2, sentence:"液体。" },
  { char:"涵", pinyin:"han2", radical:"氵", components:["氵","函"], meaning:"contain", emoji:"📨", gifDuration:1.2, sentence:"内涵。" },
  { char:"凉", pinyin:"liang2", radical:"冫", components:["冫","京"], meaning:"cool", emoji:"❄️", gifDuration:1.2, sentence:"凉快。" },
  { char:"淀", pinyin:"dian4", radical:"氵", components:["氵","定"], meaning:"sediment", emoji:"🏞️", gifDuration:1.2, sentence:"沉淀。" },
  { char:"淄", pinyin:"zi1", radical:"氵", components:["氵","甾"], meaning:"black", emoji:"🖤", gifDuration:1.2, sentence:"淄博。" },
  { char:"淅", pinyin:"xi1", radical:"氵", components:["氵","析"], meaning:"drizzle", emoji:"🌧️", gifDuration:1.2, sentence:"淅沥。" },
  { char:"淆", pinyin:"xiao2", radical:"氵", components:["氵","肴"], meaning:"confuse", emoji:"😕", gifDuration:1.2, sentence:"混淆。" },
  { char:"淇", pinyin:"qi2", radical:"氵", components:["氵","其"], meaning:"Qi River", emoji:"🏞️", gifDuration:1.2, sentence:"淇水。" },
  { char:"淋", pinyin:"lin2", radical:"氵", components:["氵","林"], meaning:"drench", emoji:"🌧️", gifDuration:1.2, sentence:"淋雨。" },
  { char:"淌", pinyin:"tang3", radical:"氵", components:["氵","尚"], meaning:"drip", emoji:"💧", gifDuration:1.2, sentence:"淌汗。" },
  { char:"淑", pinyin:"shu1", radical:"氵", components:["氵","叔"], meaning:"gentle", emoji:"😌", gifDuration:1.2, sentence:"淑女。" },
  { char:"淘", pinyin:"tao2", radical:"氵", components:["氵","匋"], meaning:"wash", emoji:"🧼", gifDuration:1.2, sentence:"淘米。" },
  { char:"淚", pinyin:"lei4", radical:"氵", components:["氵","戾"], meaning:"tears", emoji:"😢", gifDuration:1.2, sentence:"眼淚。" },
  { char:"淡", pinyin:"dan4", radical:"氵", components:["氵","炎"], meaning:"insipid", emoji:"😐", gifDuration:1.2, sentence:"平淡。" },
  { char:"淨", pinyin:"jing4", radical:"氵", components:["氵","爭"], meaning:"clean", emoji:"🧼", gifDuration:1.2, sentence:"乾淨。" },
  { char:"淪", pinyin:"lun2", radical:"氵", components:["氵","侖"], meaning:"sink", emoji:"⬇️", gifDuration:1.2, sentence:"淪陷。" },
  { char:"淫", pinyin:"yin2", radical:"氵", components:["氵","夃"], meaning:"excessive", emoji:"🌧️", gifDuration:1.2, sentence:"淫雨。" },
  { char:"淮", pinyin:"huai2", radical:"氵", components:["氵","隹"], meaning:"Huai River", emoji:"🏞️", gifDuration:1.2, sentence:"淮河。" },
  { char:"深", pinyin:"shen1", radical:"氵", components:["氵","罙"], meaning:"deep", emoji:"🌊", gifDuration:1.2, sentence:"深海。" },
  { char:"淳", pinyin:"chun2", radical:"氵", components:["氵","享"], meaning:"honest", emoji:"😇", gifDuration:1.2, sentence:"淳朴。" },
  { char:"混", pinyin:"hun4", radical:"氵", components:["氵","昆"], meaning:"mix", emoji:"🌀", gifDuration:1.2, sentence:"混合。" },
  { char:"淹", pinyin:"yan1", radical:"氵", components:["氵","奄"], meaning:"flood", emoji:"🌊", gifDuration:1.2, sentence:"淹没。" },
  { char:"淺", pinyin:"qian3", radical:"氵", components:["氵","戔"], meaning:"shallow", emoji:"🏖️", gifDuration:1.2, sentence:"淺水。" },
  { char:"添", pinyin:"tian1", radical:"氵", components:["氵","忝"], meaning:"add", emoji:"➕", gifDuration:1.2, sentence:"添加。" },
  { char:"清", pinyin:"qing1", radical:"氵", components:["氵","青"], meaning:"clear", emoji:"🔍", gifDuration:1.2, sentence:"清楚。" },
  { char:"渊", pinyin:"yuan1", radical:"氵", components:["氵","𣶒"], meaning:"abyss", emoji:"🕳️", gifDuration:1.2, sentence:"深渊。" },
  { char:"渐", pinyin:"jian4", radical:"氵", components:["氵","斩"], meaning:"gradually", emoji:"🐢", gifDuration:1.2, sentence:"渐渐。" },
  { char:"温", pinyin:"wen1", radical:"氵", components:["氵","昷"], meaning:"warm", emoji:"🌡️", gifDuration:1.2, sentence:"温度。" },

  // ───────────────── 🧑 Human & Social (more) ─────────────────
  { char:"倜", pinyin:"ti4", radical:"亻", components:["亻","周"], meaning:"unrestrained", emoji:"😎", gifDuration:1.2, sentence:"倜傥。" },
  { char:"傥", pinyin:"tang3", radical:"亻", components:["亻","党"], meaning:"if", emoji:"🤔", gifDuration:1.2, sentence:"倜傥。" },
  { char:"傧", pinyin:"bin1", radical:"亻", components:["亻","宾"], meaning:"best man", emoji:"💒", gifDuration:1.2, sentence:"傧相。" },
  { char:"傩", pinyin:"nuo2", radical:"亻", components:["亻","难"], meaning:"exorcise", emoji:"👹", gifDuration:1.2, sentence:"傩戏。" },
  { char:"催", pinyin:"cui1", radical:"亻", components:["亻","崔"], meaning:"urge", emoji:"⏰", gifDuration:1.2, sentence:"催促。" },
  { char:"傻", pinyin:"sha3", radical:"亻", components:["亻","囟","八","夂"], meaning:"silly", emoji:"🤪", gifDuration:1.3, sentence:"傻瓜。" },
  { char:"像", pinyin:"xiang4", radical:"亻", components:["亻","象"], meaning:"resemble", emoji:"🖼️", gifDuration:1.2, sentence:"好像。" },
  { char:"僖", pinyin:"xi1", radical:"亻", components:["亻","喜"], meaning:"joy", emoji:"😄", gifDuration:1.2, sentence:"僖乐。" },
  { char:"僬", pinyin:"jiao1", radical:"亻", components:["亻","焦"], meaning:"clear", emoji:"🔍", gifDuration:1.2, sentence:"僬僬。" },
  { char:"僭", pinyin:"jian4", radical:"亻", components:["亻","朁"], meaning:"usurp", emoji:"👑", gifDuration:1.2, sentence:"僭越。" },
  { char:"僵", pinyin:"jiang1", radical:"亻", components:["亻","畺"], meaning:"stiff", emoji:"🧊", gifDuration:1.2, sentence:"僵直。" },
  { char:"僻", pinyin:"pi4", radical:"亻", components:["亻","辟"], meaning:"remote", emoji:"⛰️", gifDuration:1.2, sentence:"僻静。" },
  { char:"儆", pinyin:"jing3", radical:"亻", components:["亻","敬"], meaning:"caution", emoji:"🚨", gifDuration:1.2, sentence:"以儆效尤。" },
  { char:"儋", pinyin:"dan1", radical:"亻", components:["亻","詹"], meaning:"carry", emoji:"🎒", gifDuration:1.2, sentence:"儋负。" },
  { char:"儇", pinyin:"xuan1", radical:"亻", components:["亻","睘"], meaning:"agile", emoji:"🤸", gifDuration:1.2, sentence:"儇巧。" },
  { char:"儆", pinyin:"jing3", radical:"亻", components:["亻","敬"], meaning:"warn", emoji:"⚠️", gifDuration:1.2, sentence:"儆戒。" },
  { char:"儋", pinyin:"dan1", radical:"亻", components:["亻","詹"], meaning:"carry", emoji:"🎒", gifDuration:1.2, sentence:"儋州。" },
  { char:"偌", pinyin:"ruo4", radical:"亻", components:["亻","若"], meaning:"such", emoji:"👉", gifDuration:1.2, sentence:"偌大。" },
  { char:"傣", pinyin:"dai3", radical:"亻", components:["亻","泰"], meaning:"Dai", emoji:"👥", gifDuration:1.2, sentence:"傣族。" },
  { char:"傧", pinyin:"bin1", radical:"亻", components:["亻","宾"], meaning:"best man", emoji:"💒", gifDuration:1.2, sentence:"傧相。" },
  { char:"傩", pinyin:"nuo2", radical:"亻", components:["亻","难"], meaning:"exorcism", emoji:"👹", gifDuration:1.2, sentence:"傩舞。" },
  { char:"催", pinyin:"cui1", radical:"亻", components:["亻","崔"], meaning:"hasten", emoji:"⏩", gifDuration:1.2, sentence:"催眠。" },
  { char:"傻", pinyin:"sha3", radical:"亻", components:["亻","囟","八","夂"], meaning:"fool", emoji:"🤪", gifDuration:1.3, sentence:"傻眼。" },
  { char:"像", pinyin:"xiang4", radical:"亻", components:["亻","象"], meaning:"image", emoji:"🖼️", gifDuration:1.2, sentence:"画像。" },
  { char:"僖", pinyin:"xi1", radical:"亻", components:["亻","喜"], meaning:"happy", emoji:"😀", gifDuration:1.2, sentence:"僖乐。" },
  { char:"僬", pinyin:"jiao1", radical:"亻", components:["亻","焦"], meaning:"bright", emoji:"🔆", gifDuration:1.2, sentence:"僬明。" },
  { char:"僭", pinyin:"jian4", radical:"亻", components:["亻","朁"], meaning:"usurp", emoji:"👑", gifDuration:1.2, sentence:"僭号。" },
  { char:"僵", pinyin:"jiang1", radical:"亻", components:["亻","畺"], meaning:"rigid", emoji:"🧊", gifDuration:1.2, sentence:"僵持。" },
  { char:"僻", pinyin:"pi4", radical:"亻", components:["亻","辟"], meaning:"isolated", emoji:"🏝️", gifDuration:1.2, sentence:"偏僻。" },
  { char:"儆", pinyin:"jing3", radical:"亻", components:["亻","敬"], meaning:"warn", emoji:"🚨", gifDuration:1.2, sentence:"儆醒。" },
  { char:"儋", pinyin:"dan1", radical:"亻", components:["亻","詹"], meaning:"bear", emoji:"🎒", gifDuration:1.2, sentence:"儋当。" },
  { char:"偌", pinyin:"ruo4", radical:"亻", components:["亻","若"], meaning:"so", emoji:"👉", gifDuration:1.2, sentence:"偌许。" },
  { char:"傣", pinyin:"dai3", radical:"亻", components:["亻","泰"], meaning:"Dai people", emoji:"👥", gifDuration:1.2, sentence:"傣剧。" },
  { char:"傧", pinyin:"bin1", radical:"亻", components:["亻","宾"], meaning:"usher", emoji:"🤵", gifDuration:1.2, sentence:"男傧。" },
  { char:"傩", pinyin:"nuo2", radical:"亻", components:["亻","难"], meaning:"exorcise", emoji:"👹", gifDuration:1.2, sentence:"驱傩。" },
  { char:"催", pinyin:"cui1", radical:"亻", components:["亻","崔"], meaning:"press", emoji:"⏰", gifDuration:1.2, sentence:"催债。" },

  // ───────────────── 🐅 Animals (more) ─────────────────
  { char:"猁", pinyin:"li4", radical:"犭", components:["犭","利"], meaning:"lynx", emoji:"🐱", gifDuration:1.2, sentence:"猞猁。" },
  { char:"猇", pinyin:"xiao1", radical:"犭", components:["犭","虎"], meaning:"roar", emoji:"🐅", gifDuration:1.2, sentence:"猇亭。" },
  { char:"猊", pinyin:"ni2", radical:"犭", components:["犭","兒"], meaning:"lion", emoji:"🦁", gifDuration:1.2, sentence:"狻猊。" },
  { char:"猋", pinyin:"biao1", radical:"犬", components:["犬","犬","犬"], meaning:"whirlwind", emoji:"💨", gifDuration:1.2, sentence:"猋风。" },
  { char:"猌", pinyin:"yin4", radical:"犭", components:["犭","垔"], meaning:"dog", emoji:"🐶", gifDuration:1.2, sentence:"猌狗。" },
  { char:"猒", pinyin:"yan4", radical:"犭", components:["犭","臽"], meaning:"satiated", emoji:"😋", gifDuration:1.2, sentence:"猒足。" },
  { char:"猘", pinyin:"zhi4", radical:"犭", components:["犭","制"], meaning:"mad dog", emoji:"🐶", gifDuration:1.2, sentence:"猘犬。" },
  { char:"猡", pinyin:"luo2", radical:"犭", components:["犭","罗"], meaning:"fierce", emoji:"🐗", gifDuration:1.2, sentence:"猡猡。" },
  { char:"猢", pinyin:"hu2", radical:"犭", components:["犭","胡"], meaning:"monkey", emoji:"🐒", gifDuration:1.2, sentence:"猢狲。" },
  { char:"猤", pinyin:"gui4", radical:"犭", components:["犭","癸"], meaning:"fierce", emoji:"🐗", gifDuration:1.2, sentence:"猤悍。" },
  { char:"猬", pinyin:"wei4", radical:"犭", components:["犭","胃"], meaning:"hedgehog", emoji:"🦔", gifDuration:1.2, sentence:"刺猬。" },
  { char:"猭", pinyin:"chuan2", radical:"犭", components:["犭","彖"], meaning:"wild dog", emoji:"🐺", gifDuration:1.2, sentence:"猭狗。" },
  { char:"猯", pinyin:"tuan1", radical:"犭", components:["犭","耑"], meaning:"badger", emoji:"🦡", gifDuration:1.2, sentence:"猯子。" },
  { char:"猰", pinyin:"ya4", radical:"犭", components:["犭","契"], meaning:"dog", emoji:"🐶", gifDuration:1.2, sentence:"猰犬。" },
  { char:"猱", pinyin:"nao2", radical:"犭", components:["犭","柔"], meaning:"monkey", emoji:"🐒", gifDuration:1.2, sentence:"猱升。" },
  { char:"猲", pinyin:"ge2", radical:"犭", components:["犭","曷"], meaning:"pig dog", emoji:"🐗", gifDuration:1.2, sentence:"猲狗。" },
  { char:"猵", pinyin:"bian1", radical:"犭", components:["犭","扁"], meaning:"otter", emoji:"🦦", gifDuration:1.2, sentence:"水猵。" },
  { char:"猷", pinyin:"you2", radical:"犭", components:["酋","犬"], meaning:"plan", emoji:"🤔", gifDuration:1.2, sentence:"鸿猷。" },
  { char:"猸", pinyin:"mei2", radical:"犭", components:["犭","眉"], meaning:"civet", emoji:"🐱", gifDuration:1.2, sentence:"猸子。" },
  { char:"猹", pinyin:"cha2", radical:"犭", components:["犭","查"], meaning:"badger", emoji:"🦡", gifDuration:1.2, sentence:"猹獾。" },
  { char:"猺", pinyin:"yao2", radical:"犭", components:["犭","䍃"], meaning:"jackal", emoji:"🐺", gifDuration:1.2, sentence:"猺犬。" },
  { char:"猼", pinyin:"bo2", radical:"犭", components:["犭","尃"], meaning:"leopard", emoji:"🐆", gifDuration:1.2, sentence:"猼兽。" },
  { char:"猽", pinyin:"ming2", radical:"犭", components:["犭","冥"], meaning:"dark dog", emoji:"🐕‍🦺", gifDuration:1.2, sentence:"猽犬。" },
  { char:"獀", pinyin:"sou1", radical:"犭", components:["犭","叟"], meaning:"hunting dog", emoji:"🐕", gifDuration:1.2, sentence:"獀犬。" },
  { char:"獉", pinyin:"zhen1", radical:"犭", components:["犭","秦"], meaning:"wild boar", emoji:"🐗", gifDuration:1.2, sentence:"獉猪。" },
  { char:"獒", pinyin:"ao2", radical:"犬", components:["敖","犬"], meaning:"mastiff", emoji:"🐕", gifDuration:1.2, sentence:"藏獒。" },
  { char:"獓", pinyin:"ao2", radical:"犭", components:["犭","敖"], meaning:"wild dog", emoji:"🐺", gifDuration:1.2, sentence:"獓犬。" },
  { char:"獠", pinyin:"liao2", radical:"犭", components:["犭","尞"], meaning:"hunt", emoji:"🏹", gifDuration:1.2, sentence:"獠猎。" },
  { char:"獦", pinyin:"ge2", radical:"犭", components:["犭","葛"], meaning:"ape", emoji:"🦍", gifDuration:1.2, sentence:"獦狚。" },
  { char:"獬", pinyin:"xie4", radical:"犭", components:["犭","解"], meaning:"unicorn", emoji:"🦄", gifDuration:1.2, sentence:"獬豸。" },
  { char:"獭", pinyin:"ta3", radical:"犭", components:["犭","赖"], meaning:"otter", emoji:"🦦", gifDuration:1.2, sentence:"水獭。" },
  { char:"獯", pinyin:"xun1", radical:"犭", components:["犭","熏"], meaning:"tribe", emoji:"👥", gifDuration:1.2, sentence:"獯粥。" },
  { char:"獴", pinyin:"meng3", radical:"犭", components:["犭","蒙"], meaning:"mongoose", emoji:"🐱", gifDuration:1.2, sentence:"獴哥。" },
  { char:"獿", pinyin:"nao2", radical:"犭", components:["犭","夒"], meaning:"monkey", emoji:"🐒", gifDuration:1.2, sentence:"獿猴。" },
  { char:"獾", pinyin:"huan1", radical:"犭", components:["犭","雚"], meaning:"badger", emoji:"🦡", gifDuration:1.2, sentence:"獾猪。" },
  { char:"犸", pinyin:"ma3", radical:"犭", components:["犭","马"], meaning:"mammoth", emoji:"🦣", gifDuration:1.2, sentence:"猛犸。" },
  { char:"犼", pinyin:"hou3", radical:"犭", components:["犭","孔"], meaning:"mythical beast", emoji:"🐲", gifDuration:1.2, sentence:"金毛犼。" },

  // ───────────────── 🧮 More objects & materials ─────────────────
  { char:"钣", pinyin:"ban3", radical:"钅", components:["钅","反"], meaning:"sheet metal", emoji:"🔩", gifDuration:1.2, sentence:"钣金。" },
  { char:"钤", pinyin:"qian2", radical:"钅", components:["钅","今"], meaning:"seal", emoji:"🔏", gifDuration:1.2, sentence:"钤印。" },
  { char:"钫", pinyin:"fang1", radical:"钅", components:["钅","方"], meaning:"francium", emoji:"⚛️", gifDuration:1.2, sentence:"钫元素。" },
  { char:"钬", pinyin:"huo3", radical:"钅", components:["钅","火"], meaning:"holmium", emoji:"🔥", gifDuration:1.2, sentence:"钬激光。" },
  { char:"钭", pinyin:"tou3", radical:"钅", components:["钅","斗"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"钭氏。" },
  { char:"钯", pinyin:"ba3", radical:"钅", components:["钅","巴"], meaning:"palladium", emoji:"💍", gifDuration:1.2, sentence:"钯金。" },
  { char:"钺", pinyin:"yue4", radical:"钅", components:["钅","戉"], meaning:"battle-axe", emoji:"🪓", gifDuration:1.2, sentence:"斧钺。" },
  { char:"钼", pinyin:"mu4", radical:"钅", components:["钅","目"], meaning:"molybdenum", emoji:"🔩", gifDuration:1.2, sentence:"钼钢。" },
  { char:"钽", pinyin:"tan3", radical:"钅", components:["钅","旦"], meaning:"tantalum", emoji:"🔌", gifDuration:1.2, sentence:"钽电容。" },
  { char:"钿", pinyin:"tian2", radical:"钅", components:["钅","田"], meaning:"ornament", emoji:"💎", gifDuration:1.2, sentence:"铜钿。" },
  { char:"铆", pinyin:"mao3", radical:"钅", components:["钅","卯"], meaning:"rivet", emoji:"🔩", gifDuration:1.2, sentence:"铆接。" },
  { char:"铈", pinyin:"shi4", radical:"钅", components:["钅","市"], meaning:"cerium", emoji:"🔥", gifDuration:1.2, sentence:"铈火石。" },
  { char:"铉", pinyin:"xuan4", radical:"钅", components:["钅","玄"], meaning:"stick", emoji:"🪄", gifDuration:1.2, sentence:"玉铉。" },
  { char:"铊", pinyin:"ta1", radical:"钅", components:["钅","它"], meaning:"thallium", emoji:"☠️", gifDuration:1.2, sentence:"铊毒。" },
  { char:"铋", pinyin:"bi4", radical:"钅", components:["钅","必"], meaning:"bismuth", emoji:"💊", gifDuration:1.2, sentence:"铋剂。" },
  { char:"铌", pinyin:"ni2", radical:"钅", components:["钅","尼"], meaning:"niobium", emoji:"🔩", gifDuration:1.2, sentence:"铌铁。" },
  { char:"铍", pinyin:"pi2", radical:"钅", components:["钅","皮"], meaning:"beryllium", emoji:"⚠️", gifDuration:1.2, sentence:"铍青铜。" },
  { char:"铑", pinyin:"lao3", radical:"钅", components:["钅","老"], meaning:"rhodium", emoji:"💍", gifDuration:1.2, sentence:"铑金。" },
  { char:"铒", pinyin:"er3", radical:"钅", components:["钅","耳"], meaning:"erbium", emoji:"🟢", gifDuration:1.2, sentence:"铒激光。" },
  { char:"铕", pinyin:"you3", radical:"钅", components:["钅","有"], meaning:"europium", emoji:"🔴", gifDuration:1.2, sentence:"铕荧光。" },
  { char:"铖", pinyin:"cheng2", radical:"钅", components:["钅","成"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"铖氏。" },
  { char:"铗", pinyin:"jia2", radical:"钅", components:["钅","夹"], meaning:"pincers", emoji:"🔧", gifDuration:1.2, sentence:"铁铗。" },
  { char:"铙", pinyin:"nao2", radical:"钅", components:["钅","尧"], meaning:"cymbal", emoji:"🥁", gifDuration:1.2, sentence:"铜铙。" },
  { char:"铬", pinyin:"ge4", radical:"钅", components:["钅","各"], meaning:"chromium", emoji:"✨", gifDuration:1.2, sentence:"镀铬。" },
  { char:"铞", pinyin:"diao4", radical:"钅", components:["钅","吊"], meaning:"padlock", emoji:"🔒", gifDuration:1.2, sentence:"铞子。" },
  { char:"铟", pinyin:"yin1", radical:"钅", components:["钅","因"], meaning:"indium", emoji:"🔗", gifDuration:1.2, sentence:"铟丝。" },
  { char:"铥", pinyin:"diu1", radical:"钅", components:["钅","丢"], meaning:"thulium", emoji:"🔵", gifDuration:1.2, sentence:"铥元素。" },
  { char:"铪", pinyin:"ha1", radical:"钅", components:["钅","合"], meaning:"hafnium", emoji:"🔗", gifDuration:1.2, sentence:"铪丝。" },
  { char:"铯", pinyin:"se4", radical:"钅", components:["钅","色"], meaning:"cesium", emoji:"⏱️", gifDuration:1.2, sentence:"铯原子钟。" },
  { char:"铷", pinyin:"ru2", radical:"钅", components:["钅","如"], meaning:"rubidium", emoji:"🔴", gifDuration:1.2, sentence:"铷灯。" },
  { char:"铹", pinyin:"lao2", radical:"钅", components:["钅","劳"], meaning:"lawrencium", emoji:"⚛️", gifDuration:1.2, sentence:"铹元素。" },
  { char:"铼", pinyin:"lai2", radical:"钅", components:["钅","来"], meaning:"rhenium", emoji:"🔩", gifDuration:1.2, sentence:"铼合金。" },
  { char:"铽", pinyin:"te4", radical:"钅", components:["钅","忒"], meaning:"terbium", emoji:"🟢", gifDuration:1.2, sentence:"铽荧光。" },
  { char:"锇", pinyin:"e2", radical:"钅", components:["钅","我"], meaning:"osmium", emoji:"🔵", gifDuration:1.2, sentence:"锇铱。" },
  { char:"锊", pinyin:"lve4", radical:"钅", components:["钅","寽"], meaning:"ancient weight", emoji:"⚖️", gifDuration:1.2, sentence:"六锊。" },
  { char:"锒", pinyin:"lang2", radical:"钅", components:["钅","良"], meaning:"chain", emoji:"⛓️", gifDuration:1.2, sentence:"锒铛入狱。" },
  { char:"锘", pinyin:"nuo4", radical:"钅", components:["钅","若"], meaning:"nobelium", emoji:"⚛️", gifDuration:1.2, sentence:"锘元素。" },
  { char:"锛", pinyin:"ben1", radical:"钅", components:["钅","奔"], meaning:"adze", emoji:"🪓", gifDuration:1.2, sentence:"锛子。" },
  { char:"锝", pinyin:"de2", radical:"钅", components:["钅","㝵"], meaning:"technetium", emoji:"☢️", gifDuration:1.2, sentence:"锝元素。" },
  { char:"锞", pinyin:"ke4", radical:"钅", components:["钅","果"], meaning:"ingot", emoji:"🪙", gifDuration:1.2, sentence:"银锞。" },
  { char:"锠", pinyin:"chang1", radical:"钅", components:["钅","昌"], meaning:"spear", emoji:"🗡️", gifDuration:1.2, sentence:"锠矛。" },
  { char:"锪", pinyin:"huo1", radical:"钅", components:["钅","忽"], meaning:"scraper", emoji:"🔧", gifDuration:1.2, sentence:"锪刀。" },
  { char:"锬", pinyin:"tan2", radical:"钅", components:["钅","炎"], meaning:"lance", emoji:"🗡️", gifDuration:1.2, sentence:"锬矛。" },
  { char:"锱", pinyin:"zi1", radical:"钅", components:["钅","甾"], meaning:"weight", emoji:"⚖️", gifDuration:1.2, sentence:"锱铢。" },
  { char:"锴", pinyin:"kai3", radical:"钅", components:["钅","皆"], meaning:"high quality iron", emoji:"🔩", gifDuration:1.2, sentence:"锴铁。" },
  { char:"锵", pinyin:"sheng4", radical:"钅", components:["钅","省"], meaning:"scissors", emoji:"✂️", gifDuration:1.2, sentence:"锵刀。" },
  { char:"锷", pinyin:"e4", radical:"钅", components:["钅","咢"], meaning:"blade", emoji:"🔪", gifDuration:1.2, sentence:"锋锷。" },
  { char:"锸", pinyin:"cha1", radical:"钅", components:["钅","臿"], meaning:"spade", emoji:"🪏", gifDuration:1.2, sentence:"铁锸。" },
  { char:"锹", pinyin:"qiao1", radical:"钅", components:["钅","秋"], meaning:"shovel", emoji:"🪏", gifDuration:1.2, sentence:"铁锹。" },
  { char:"锺", pinyin:"zhong1", radical:"钅", components:["钅","重"], meaning:"bell", emoji:"🔔", gifDuration:1.2, sentence:"锺爱。" },
  { char:"锻", pinyin:"duan4", radical:"钅", components:["钅","段"], meaning:"forge", emoji:"🔨", gifDuration:1.2, sentence:"锻炼。" },
  { char:"锽", pinyin:"huang2", radical:"钅", components:["钅","皇"], meaning:"bell", emoji:"🔔", gifDuration:1.2, sentence:"钟锽。" },
  { char:"锾", pinyin:"huan2", radical:"钅", components:["钅","爰"], meaning:"weight", emoji:"⚖️", gifDuration:1.2, sentence:"铜锾。" },
  { char:"锿", pinyin:"ai1", radical:"钅", components:["钅","哀"], meaning:"einsteinium", emoji:"⚛️", gifDuration:1.2, sentence:"锿元素。" },
  { char:"镀", pinyin:"du4", radical:"钅", components:["钅","度"], meaning:"plating", emoji:"🔩", gifDuration:1.2, sentence:"镀金。" },
  { char:"镁", pinyin:"mei3", radical:"钅", components:["钅","美"], meaning:"magnesium", emoji:"🔥", gifDuration:1.2, sentence:"镁光灯。" },
  { char:"镂", pinyin:"lou4", radical:"钅", components:["钅","娄"], meaning:"engrave", emoji:"🔪", gifDuration:1.2, sentence:"镂空。" },
  { char:"镐", pinyin:"hao4", radical:"钅", components:["钅","高"], meaning:"pickaxe", emoji:"⛏️", gifDuration:1.2, sentence:"十字镐。" },
  { char:"镒", pinyin:"yi4", radical:"钅", components:["钅","益"], meaning:"weight", emoji:"⚖️", gifDuration:1.2, sentence:"千镒。" },
  { char:"镓", pinyin:"jia1", radical:"钅", components:["钅","家"], meaning:"gallium", emoji:"🌡️", gifDuration:1.2, sentence:"镓元素。" },
  { char:"镔", pinyin:"bin1", radical:"钅", components:["钅","宾"], meaning:"fine steel", emoji:"🗡️", gifDuration:1.2, sentence:"镔铁。" },
  { char:"镗", pinyin:"tang2", radical:"钅", components:["钅","堂"], meaning:"boring tool", emoji:"🔧", gifDuration:1.2, sentence:"镗床。" },
  { char:"镚", pinyin:"beng4", radical:"钅", components:["钅","崩"], meaning:"small coin", emoji:"🪙", gifDuration:1.2, sentence:"钢镚。" },
  { char:"镣", pinyin:"liao4", radical:"钅", components:["钅","尞"], meaning:"fetters", emoji:"⛓️", gifDuration:1.2, sentence:"镣铐。" },
  { char:"镤", pinyin:"pu2", radical:"钅", components:["钅","菐"], meaning:"protactinium", emoji:"☢️", gifDuration:1.2, sentence:"镤元素。" },
  { char:"镥", pinyin:"lu3", radical:"钅", components:["钅","鲁"], meaning:"lutetium", emoji:"🔬", gifDuration:1.2, sentence:"镥元素。" },
  { char:"镨", pinyin:"pu3", radical:"钅", components:["钅","普"], meaning:"praseodymium", emoji:"🟢", gifDuration:1.2, sentence:"镨钕。" },
  { char:"镩", pinyin:"cuan1", radical:"钅", components:["钅","窜"], meaning:"ice skate", emoji:"⛸️", gifDuration:1.2, sentence:"冰镩。" },
  { char:"镫", pinyin:"deng4", radical:"钅", components:["钅","登"], meaning:"stirrup", emoji:"🐎", gifDuration:1.2, sentence:"马镫。" },
  { char:"镱", pinyin:"yi4", radical:"钅", components:["钅","意"], meaning:"ytterbium", emoji:"🔬", gifDuration:1.2, sentence:"镱元素。" },
  { char:"镳", pinyin:"biao1", radical:"钅", components:["钅","麃"], meaning:"bit", emoji:"🐴", gifDuration:1.2, sentence:"马镳。" },
  { char:"镵", pinyin:"chan2", radical:"钅", components:["钅","毚"], meaning:"sharp", emoji:"🗡️", gifDuration:1.2, sentence:"镵刀。" },
  { char:"镶", pinyin:"xiang1", radical:"钅", components:["钅","襄"], meaning:"inlay", emoji:"💎", gifDuration:1.2, sentence:"镶嵌。" },
  { char:"镼", pinyin:"qu1", radical:"钅", components:["钅","屈"], meaning:"bracelet", emoji:"💍", gifDuration:1.2, sentence:"玉镼。" },
  { char:"镽", pinyin:"liao4", radical:"钅", components:["钅","翏"], meaning:"chain", emoji:"⛓️", gifDuration:1.2, sentence:"镽铐。" },
  { char:"镾", pinyin:"mi2", radical:"钅", components:["钅","爾"], meaning:"full", emoji:"🈵", gifDuration:1.2, sentence:"镾月。" },
  { char:"长", pinyin:"xin1", radical:"钅", components:["钅","新"], meaning:"new metal", emoji:"🌟", gifDuration:1.2, sentence:"长铸。" },
  { char:"长", pinyin:"chang2", radical:"长", components:[], meaning:"long", emoji:"📏", gifDuration:1, sentence:"长短。" },
  { char:"闩", pinyin:"shuan1", radical:"门", components:["门","一"], meaning:"bolt", emoji:"🔒", gifDuration:1.2, sentence:"门闩。" },
  { char:"闫", pinyin:"yan2", radical:"门", components:["门","三"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"闫姓。" },
  { char:"闱", pinyin:"wei2", radical:"门", components:["门","韦"], meaning:"door", emoji:"🚪", gifDuration:1.2, sentence:"宫闱。" },
  { char:"闳", pinyin:"hong2", radical:"门", components:["门","厷"], meaning:"wide", emoji:"🌊", gifDuration:1.2, sentence:"闳大。" },
  { char:"闵", pinyin:"min3", radical:"门", components:["门","文"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"闵行。" },
  { char:"闶", pinyin:"kang4", radical:"门", components:["门","亢"], meaning:"high door", emoji:"🚪", gifDuration:1.2, sentence:"闶阆。" },
  { char:"闼", pinyin:"ta4", radical:"门", components:["门","达"], meaning:"door", emoji:"🚪", gifDuration:1.2, sentence:"排闼。" },
  { char:"闾", pinyin:"lv2", radical:"门", components:["门","吕"], meaning:"gate", emoji:"🏘️", gifDuration:1.2, sentence:"闾里。" },
  { char:"闿", pinyin:"kai3", radical:"门", components:["门","岂"], meaning:"open", emoji:"🔓", gifDuration:1.2, sentence:"闿门。" },
  { char:"阇", pinyin:"du1", radical:"门", components:["门","者"], meaning:"watchtower", emoji:"🏰", gifDuration:1.2, sentence:"城阇。" },
  { char:"阉", pinyin:"yan1", radical:"门", components:["门","奄"], meaning:"eunuch", emoji:"👤", gifDuration:1.2, sentence:"阉割。" },
  { char:"阏", pinyin:"e4", radical:"门", components:["门","於"], meaning:"block", emoji:"🚧", gifDuration:1.2, sentence:"阏塞。" },
  { char:"阒", pinyin:"qu4", radical:"门", components:["门","狊"], meaning:"quiet", emoji:"🤫", gifDuration:1.2, sentence:"阒然。" },
  { char:"阑", pinyin:"lan2", radical:"门", components:["门","柬"], meaning:"railing", emoji:"🚪", gifDuration:1.2, sentence:"阑干。" },
  { char:"阕", pinyin:"que4", radical:"门", components:["门","癸"], meaning:"end", emoji:"🏁", gifDuration:1.2, sentence:"乐阕。" },
  { char:"阖", pinyin:"he2", radical:"门", components:["门","盍"], meaning:"close", emoji:"🔒", gifDuration:1.2, sentence:"阖家。" },
  { char:"阗", pinyin:"tian2", radical:"门", components:["门","真"], meaning:"fill", emoji:"🈵", gifDuration:1.2, sentence:"喧阗。" },
  { char:"阘", pinyin:"ta4", radical:"门", components:["门","沓"], meaning:"door", emoji:"🚪", gifDuration:1.2, sentence:"门阘。" },
  { char:"阛", pinyin:"huan2", radical:"门", components:["门","睘"], meaning:"market", emoji:"🏪", gifDuration:1.2, sentence:"阛阓。" },
  { char:"阞", pinyin:"le4", radical:"阝", components:["阝","力"], meaning:"vein", emoji:"🩸", gifDuration:1.2, sentence:"地阞。" }
];