const charactersPart6 = [
  // ───────────────── 🧑 Human & Social (rare) ─────────────────
  { char:"仇", pinyin:"chou2", radical:"亻", components:["亻","九"], meaning:"hatred", emoji:"😠", gifDuration:1.2, sentence:"报仇雪恨。" },
  { char:"侏", pinyin:"zhu1", radical:"亻", components:["亻","朱"], meaning:"dwarf", emoji:"🧍‍♂️", gifDuration:1.2, sentence:"侏儒症。" },
  { char:"侨", pinyin:"qiao2", radical:"亻", components:["亻","乔"], meaning:"overseas", emoji:"✈️", gifDuration:1.2, sentence:"华侨归国。" },
  { char:"佞", pinyin:"ning4", radical:"亻", components:["亻","妄"], meaning:"flatter", emoji:"🗣️", gifDuration:1.2, sentence:"奸佞小人。" },
  { char:"侥", pinyin:"jiao3", radical:"亻", components:["亻","尧"], meaning:"lucky", emoji:"🍀", gifDuration:1.2, sentence:"侥幸取胜。" },
  { char:"佻", pinyin:"tiao1", radical:"亻", components:["亻","兆"], meaning:"frivolous", emoji:"😜", gifDuration:1.2, sentence:"轻佻。" },
  { char:"佼", pinyin:"jiao3", radical:"亻", components:["亻","交"], meaning:"handsome", emoji:"😎", gifDuration:1.2, sentence:"佼佼者。" },
  { char:"佹", pinyin:"gui3", radical:"亻", components:["亻","危"], meaning:"crafty", emoji:"🦊", gifDuration:1.2, sentence:"佹辩。" },
  { char:"侔", pinyin:"mou2", radical:"亻", components:["亻","牟"], meaning:"equal", emoji:"⚖️", gifDuration:1.2, sentence:"侔色。" },
  { char:"侗", pinyin:"dong4", radical:"亻", components:["亻","同"], meaning:"childish", emoji:"👶", gifDuration:1.2, sentence:"侗族。" },
  { char:"侜", pinyin:"zhou1", radical:"亻", components:["亻","舟"], meaning:"deceive", emoji:"🤥", gifDuration:1.2, sentence:"侜张为幻。" },
  { char:"俦", pinyin:"chou2", radical:"亻", components:["亻","寿"], meaning:"companion", emoji:"👫", gifDuration:1.2, sentence:"俦侣。" },
  { char:"倥", pinyin:"kong1", radical:"亻", components:["亻","空"], meaning:"ignorant", emoji:"😶", gifDuration:1.2, sentence:"倥侗。" },
  { char:"倌", pinyin:"guan1", radical:"亻", components:["亻","官"], meaning:"servant", emoji:"🧹", gifDuration:1.2, sentence:"羊倌。" },
  { char:"倮", pinyin:"luo3", radical:"亻", components:["亻","果"], meaning:"naked", emoji:"👤", gifDuration:1.2, sentence:"倮虫。" },
  { char:"偈", pinyin:"ji2", radical:"亻", components:["亻","曷"], meaning:"brave", emoji:"💪", gifDuration:1.2, sentence:"偈语。" },
  { char:"傩", pinyin:"nuo2", radical:"亻", components:["亻","难"], meaning:"exorcism", emoji:"👹", gifDuration:1.2, sentence:"傩戏。" },
  { char:"催", pinyin:"cui1", radical:"亻", components:["亻","崔"], meaning:"urge", emoji:"⏰", gifDuration:1.2, sentence:"催促。" },
  { char:"傻", pinyin:"sha3", radical:"亻", components:["亻","囟","八","夂"], meaning:"foolish", emoji:"🤪", gifDuration:1.3, sentence:"傻笑。" },
  { char:"僭", pinyin:"jian4", radical:"亻", components:["亻","朁"], meaning:"usurp", emoji:"👑", gifDuration:1.2, sentence:"僭越。" },
  { char:"僵", pinyin:"jiang1", radical:"亻", components:["亻","畺"], meaning:"stiff", emoji:"🧊", gifDuration:1.2, sentence:"僵局。" },
  { char:"僻", pinyin:"pi4", radical:"亻", components:["亻","辟"], meaning:"secluded", emoji:"🏞️", gifDuration:1.2, sentence:"偏僻。" },
  { char:"儆", pinyin:"jing3", radical:"亻", components:["亻","敬"], meaning:"warn", emoji:"⚠️", gifDuration:1.2, sentence:"以儆效尤。" },
  { char:"儋", pinyin:"dan1", radical:"亻", components:["亻","詹"], meaning:"carry", emoji:"🎒", gifDuration:1.2, sentence:"儋州。" },
  { char:"偌", pinyin:"ruo4", radical:"亻", components:["亻","若"], meaning:"such", emoji:"👉", gifDuration:1.2, sentence:"偌大。" },
  { char:"傣", pinyin:"dai3", radical:"亻", components:["亻","泰"], meaning:"Dai people", emoji:"👥", gifDuration:1.2, sentence:"傣族。" },
  { char:"傧", pinyin:"bin1", radical:"亻", components:["亻","宾"], meaning:"best man", emoji:"💒", gifDuration:1.2, sentence:"傧相。" },
  { char:"傩", pinyin:"nuo2", radical:"亻", components:["亻","难"], meaning:"exorcise", emoji:"👹", gifDuration:1.2, sentence:"傩舞。" },
  { char:"催", pinyin:"cui1", radical:"亻", components:["亻","崔"], meaning:"urge", emoji:"⏰", gifDuration:1.2, sentence:"催眠。" },
  { char:"傻", pinyin:"sha3", radical:"亻", components:["亻","囟","八","夂"], meaning:"silly", emoji:"🤪", gifDuration:1.3, sentence:"傻瓜。" },
  { char:"像", pinyin:"xiang4", radical:"亻", components:["亻","象"], meaning:"resemble", emoji:"🖼️", gifDuration:1.2, sentence:"画像。" },
  { char:"僖", pinyin:"xi1", radical:"亻", components:["亻","喜"], meaning:"joy", emoji:"😄", gifDuration:1.2, sentence:"僖乐。" },
  { char:"僬", pinyin:"jiao1", radical:"亻", components:["亻","焦"], meaning:"clear", emoji:"🔍", gifDuration:1.2, sentence:"僬僬。" },
  { char:"僭", pinyin:"jian4", radical:"亻", components:["亻","朁"], meaning:"usurp", emoji:"👑", gifDuration:1.2, sentence:"僭越。" },
  { char:"僵", pinyin:"jiang1", radical:"亻", components:["亻","畺"], meaning:"stiff", emoji:"🧊", gifDuration:1.2, sentence:"僵直。" },
  { char:"僻", pinyin:"pi4", radical:"亻", components:["亻","辟"], meaning:"remote", emoji:"⛰️", gifDuration:1.2, sentence:"僻静。" },
  { char:"儆", pinyin:"jing3", radical:"亻", components:["亻","敬"], meaning:"caution", emoji:"🚨", gifDuration:1.2, sentence:"儆戒。" },
  { char:"儋", pinyin:"dan1", radical:"亻", components:["亻","詹"], meaning:"carry", emoji:"🎒", gifDuration:1.2, sentence:"儋负。" },

  // ───────────────── 🌿 Nature & Elements (more water/wood) ─────────────────
  { char:"泱", pinyin:"yang1", radical:"氵", components:["氵","央"], meaning:"vast", emoji:"🌊", gifDuration:1.2, sentence:"泱泱大国。" },
  { char:"泯", pinyin:"min3", radical:"氵", components:["氵","民"], meaning:"obliterate", emoji:"❌", gifDuration:1.2, sentence:"泯灭。" },
  { char:"泫", pinyin:"xuan4", radical:"氵", components:["氵","玄"], meaning:"weep", emoji:"😢", gifDuration:1.2, sentence:"泫然泪下。" },
  { char:"泠", pinyin:"ling2", radical:"氵", components:["氵","令"], meaning:"cool", emoji:"❄️", gifDuration:1.2, sentence:"泠风。" },
  { char:"泞", pinyin:"ning4", radical:"氵", components:["氵","宁"], meaning:"muddy", emoji:"🌧️", gifDuration:1.2, sentence:"泥泞。" },
  { char:"泯", pinyin:"min3", radical:"氵", components:["氵","民"], meaning:"vanish", emoji:"🌫️", gifDuration:1.2, sentence:"泯然。" },
  { char:"泱", pinyin:"yang1", radical:"氵", components:["氵","央"], meaning:"grand", emoji:"🌊", gifDuration:1.2, sentence:"江水泱泱。" },
  { char:"泡", pinyin:"pao4", radical:"氵", components:["氵","包"], meaning:"bubble", emoji:"🫧", gifDuration:1.2, sentence:"起泡。" },
  { char:"泼", pinyin:"po1", radical:"氵", components:["氵","发"], meaning:"splash", emoji:"💦", gifDuration:1.2, sentence:"泼水。" },
  { char:"泗", pinyin:"si4", radical:"氵", components:["氵","四"], meaning:"Si River", emoji:"🏞️", gifDuration:1.2, sentence:"泗水。" },
  { char:"泮", pinyin:"pan4", radical:"氵", components:["氵","半"], meaning:"melt", emoji:"🔥", gifDuration:1.2, sentence:"冰泮。" },
  { char:"泰", pinyin:"tai4", radical:"水", components:["大","氺"], meaning:"peaceful", emoji:"🕊️", gifDuration:1.2, sentence:"泰山。" },
  { char:"泵", pinyin:"beng4", radical:"水", components:["石","水"], meaning:"pump", emoji:"🚰", gifDuration:1.2, sentence:"水泵。" },
  { char:"涓", pinyin:"juan1", radical:"氵", components:["氵","肙"], meaning:"trickle", emoji:"💧", gifDuration:1.2, sentence:"涓涓细流。" },
  { char:"涔", pinyin:"cen2", radical:"氵", components:["氵","岑"], meaning:"rain", emoji:"🌧️", gifDuration:1.2, sentence:"涔涔。" },
  { char:"涩", pinyin:"se4", radical:"氵", components:["氵","歮"], meaning:"astringent", emoji:"🍋", gifDuration:1.2, sentence:"苦涩。" },
  { char:"涌", pinyin:"yong3", radical:"氵", components:["氵","甬"], meaning:"gush", emoji:"⛲", gifDuration:1.2, sentence:"涌出。" },
  { char:"涣", pinyin:"huan4", radical:"氵", components:["氵","奂"], meaning:"disperse", emoji:"💨", gifDuration:1.2, sentence:"涣散。" },
  { char:"涤", pinyin:"di2", radical:"氵", components:["氵","条"], meaning:"wash", emoji:"🧼", gifDuration:1.2, sentence:"洗涤。" },
  { char:"润", pinyin:"run4", radical:"氵", components:["氵","闰"], meaning:"moist", emoji:"💦", gifDuration:1.2, sentence:"雨润。" },
  { char:"涧", pinyin:"jian4", radical:"氵", components:["氵","间"], meaning:"ravine", emoji:"🏞️", gifDuration:1.2, sentence:"山涧。" },
  { char:"涮", pinyin:"shuan4", radical:"氵", components:["氵","刷"], meaning:"rinse", emoji:"🚿", gifDuration:1.2, sentence:"涮火锅。" },
  { char:"淙", pinyin:"cong2", radical:"氵", components:["氵","宗"], meaning:"gurgle", emoji:"💧", gifDuration:1.2, sentence:"流水淙淙。" },
  { char:"淝", pinyin:"fei2", radical:"氵", components:["氵","肥"], meaning:"Fei River", emoji:"🏞️", gifDuration:1.2, sentence:"淝水。" },
  { char:"淞", pinyin:"song1", radical:"氵", components:["氵","松"], meaning:"Song River", emoji:"🏞️", gifDuration:1.2, sentence:"吴淞口。" },
  { char:"淠", pinyin:"pi4", radical:"氵", components:["氵","畀"], meaning:"Pi River", emoji:"🏞️", gifDuration:1.2, sentence:"淠河。" },
  { char:"淡", pinyin:"dan4", radical:"氵", components:["氵","炎"], meaning:"insipid", emoji:"😐", gifDuration:1.2, sentence:"平淡。" },
  { char:"淤", pinyin:"yu1", radical:"氵", components:["氵","於"], meaning:"silt", emoji:"🌫️", gifDuration:1.2, sentence:"淤积。" },
  { char:"淦", pinyin:"gan4", radical:"氵", components:["氵","金"], meaning:"Gan River", emoji:"🏞️", gifDuration:1.2, sentence:"淦水。" },
  { char:"淫", pinyin:"yin2", radical:"氵", components:["氵","夃"], meaning:"excessive", emoji:"🌧️", gifDuration:1.2, sentence:"淫雨。" },
  { char:"淬", pinyin:"cui4", radical:"氵", components:["氵","卒"], meaning:"quench", emoji:"🔨", gifDuration:1.2, sentence:"淬火。" },
  { char:"淹", pinyin:"yan1", radical:"氵", components:["氵","奄"], meaning:"submerge", emoji:"🌊", gifDuration:1.2, sentence:"淹没。" },
  { char:"渊", pinyin:"yuan1", radical:"氵", components:["氵","𣶒"], meaning:"abyss", emoji:"🌊", gifDuration:1.2, sentence:"深渊。" },
  { char:"淅", pinyin:"xi1", radical:"氵", components:["氵","析"], meaning:"drizzle", emoji:"🌧️", gifDuration:1.2, sentence:"淅沥。" },
  { char:"淆", pinyin:"xiao2", radical:"氵", components:["氵","肴"], meaning:"confuse", emoji:"😕", gifDuration:1.2, sentence:"混淆。" },
  { char:"淇", pinyin:"qi2", radical:"氵", components:["氵","其"], meaning:"Qi River", emoji:"🏞️", gifDuration:1.2, sentence:"淇水。" },
  { char:"潺", pinyin:"chan2", radical:"氵", components:["氵","孱"], meaning:"murmur", emoji:"💧", gifDuration:1.2, sentence:"潺潺流水。" },
  { char:"淼", pinyin:"miao3", radical:"水", components:["水","水","水"], meaning:"vast water", emoji:"🌊", gifDuration:1.2, sentence:"淼茫。" },
  { char:"灿", pinyin:"can4", radical:"火", components:["火","山"], meaning:"brilliant", emoji:"🌟", gifDuration:1.2, sentence:"灿烂。" },
  { char:"炀", pinyin:"yang2", radical:"火", components:["火","昜"], meaning:"melt", emoji:"🔥", gifDuration:1.2, sentence:"炀火。" },
  { char:"炅", pinyin:"jiong3", radical:"火", components:["火","日"], meaning:"bright", emoji:"☀️", gifDuration:1.2, sentence:"炅然。" },
  { char:"炆", pinyin:"wen2", radical:"火", components:["火","文"], meaning:"warm", emoji:"♨️", gifDuration:1.2, sentence:"炆火。" },
  { char:"炘", pinyin:"xin4", radical:"火", components:["火","斤"], meaning:"brilliant", emoji:"✨", gifDuration:1.2, sentence:"炘炘。" },
  { char:"炙", pinyin:"zhi4", radical:"火", components:["月","火"], meaning:"roast", emoji:"🍖", gifDuration:1.2, sentence:"炙烤。" },
  { char:"炤", pinyin:"zhao4", radical:"火", components:["火","召"], meaning:"shine", emoji:"🔦", gifDuration:1.2, sentence:"炤耀。" },
  { char:"炷", pinyin:"zhu4", radical:"火", components:["火","主"], meaning:"incense", emoji:"🕯️", gifDuration:1.2, sentence:"一炷香。" },
  { char:"炱", pinyin:"tai2", radical:"火", components:["火","台"], meaning:"soot", emoji:"♨️", gifDuration:1.2, sentence:"煤炱。" },
  { char:"炲", pinyin:"tai2", radical:"火", components:["火","台"], meaning:"soot", emoji:"🏭", gifDuration:1.2, sentence:"炲烟。" },
  { char:"炴", pinyin:"yang3", radical:"火", components:["火","央"], meaning:"blaze", emoji:"🔥", gifDuration:1.2, sentence:"炴炴。" },
  { char:"炵", pinyin:"teng2", radical:"火", components:["火","冬"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"炵炵。" },
  { char:"炻", pinyin:"shi2", radical:"火", components:["火","石"], meaning:"stoneware", emoji:"🏺", gifDuration:1.2, sentence:"炻器。" },
  { char:"烊", pinyin:"yang2", radical:"火", components:["火","羊"], meaning:"melt", emoji:"🔥", gifDuration:1.2, sentence:"烊化。" },
  { char:"烌", pinyin:"xiu1", radical:"火", components:["火","休"], meaning:"warm", emoji:"♨️", gifDuration:1.2, sentence:"烌烌。" },
  { char:"烎", pinyin:"yin2", radical:"火", components:["开","火"], meaning:"open fire", emoji:"🔥", gifDuration:1.2, sentence:"烎火。" },
  { char:"烐", pinyin:"zhou1", radical:"火", components:["火","舟"], meaning:"cook", emoji:"🍳", gifDuration:1.2, sentence:"烐饭。" },
  { char:"烔", pinyin:"tong2", radical:"火", components:["火","同"], meaning:"hot", emoji:"🌡️", gifDuration:1.2, sentence:"烔烔。" },
  { char:"烗", pinyin:"kai1", radical:"火", components:["火","亥"], meaning:"burn", emoji:"🔥", gifDuration:1.2, sentence:"烗火。" },
  { char:"烚", pinyin:"xia2", radical:"火", components:["火","合"], meaning:"flame", emoji:"🔥", gifDuration:1.2, sentence:"烚烚。" },
  { char:"烜", pinyin:"xuan3", radical:"火", components:["火","亘"], meaning:"burn", emoji:"🔥", gifDuration:1.2, sentence:"烜赫。" },
  { char:"烩", pinyin:"hui4", radical:"火", components:["火","会"], meaning:"braise", emoji:"🍲", gifDuration:1.2, sentence:"杂烩。" },
  { char:"烪", pinyin:"fen4", radical:"火", components:["火","奋"], meaning:"burn", emoji:"🔥", gifDuration:1.2, sentence:"烪火。" },
  { char:"烮", pinyin:"lie4", radical:"火", components:["火","列"], meaning:"fierce", emoji:"🔥", gifDuration:1.2, sentence:"烮火。" },
  { char:"烰", pinyin:"fu2", radical:"火", components:["火","孚"], meaning:"bright", emoji:"✨", gifDuration:1.2, sentence:"烰烰。" },
  { char:"烳", pinyin:"pu3", radical:"火", components:["火","甫"], meaning:"cook", emoji:"🍳", gifDuration:1.2, sentence:"烳饭。" },
  { char:"烴", pinyin:"ting3", radical:"火", components:["火","廷"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"烴火。" },
  { char:"烶", pinyin:"ting3", radical:"火", components:["火","廷"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"烶火。" },
  { char:"烸", pinyin:"hai3", radical:"火", components:["火","每"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"烸火。" },
  { char:"烻", pinyin:"zhan3", radical:"火", components:["火","占"], meaning:"candle", emoji:"🕯️", gifDuration:1.2, sentence:"烻火。" },
  { char:"烾", pinyin:"chi4", radical:"火", components:["火","赤"], meaning:"red hot", emoji:"🔥", gifDuration:1.2, sentence:"烾热。" },
  { char:"烿", pinyin:"yang2", radical:"火", components:["火","昜"], meaning:"sun", emoji:"☀️", gifDuration:1.2, sentence:"烿光。" },
  { char:"焀", pinyin:"yu4", radical:"火", components:["火","谷"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"焀火。" },
  { char:"焁", pinyin:"xi1", radical:"火", components:["火","希"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"焁火。" },
  { char:"焄", pinyin:"xun1", radical:"火", components:["火","君"], meaning:"smoke", emoji:"💨", gifDuration:1.2, sentence:"焄烟。" },
  { char:"焅", pinyin:"ku4", radical:"火", components:["火","告"], meaning:"dry", emoji:"🏜️", gifDuration:1.2, sentence:"焅燥。" },
  { char:"焆", pinyin:"juan1", radical:"火", components:["火","肙"], meaning:"bright", emoji:"✨", gifDuration:1.2, sentence:"焆焆。" },
  { char:"焈", pinyin:"fu2", radical:"火", components:["火","孚"], meaning:"flame", emoji:"🔥", gifDuration:1.2, sentence:"焈火。" },
  { char:"焋", pinyin:"chu4", radical:"火", components:["火","束"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"焋火。" },
  { char:"焍", pinyin:"di4", radical:"火", components:["火","弟"], meaning:"burn", emoji:"🔥", gifDuration:1.2, sentence:"焍火。" },
  { char:"焐", pinyin:"wu4", radical:"火", components:["火","吾"], meaning:"warm", emoji:"♨️", gifDuration:1.2, sentence:"焐手。" },
  { char:"焓", pinyin:"han2", radical:"火", components:["火","含"], meaning:"enthalpy", emoji:"🔥", gifDuration:1.2, sentence:"焓值。" },
  { char:"焗", pinyin:"ju2", radical:"火", components:["火","局"], meaning:"bake", emoji:"🍞", gifDuration:1.2, sentence:"焗饭。" },
  { char:"焘", pinyin:"dao4", radical:"火", components:["火","寿"], meaning:"cover", emoji:"🔥", gifDuration:1.2, sentence:"焘覆。" },
  { char:"焙", pinyin:"bei4", radical:"火", components:["火","咅"], meaning:"roast", emoji:"🔥", gifDuration:1.2, sentence:"焙茶。" },
  { char:"焚", pinyin:"fen2", radical:"火", components:["林","火"], meaning:"burn", emoji:"🔥", gifDuration:1.2, sentence:"焚烧。" },
  { char:"焖", pinyin:"men4", radical:"火", components:["火","闷"], meaning:"braise", emoji:"🍲", gifDuration:1.2, sentence:"焖饭。" },
  { char:"焜", pinyin:"kun1", radical:"火", components:["火","昆"], meaning:"bright", emoji:"✨", gifDuration:1.2, sentence:"焜耀。" },
  { char:"焝", pinyin:"hun4", radical:"火", components:["火","昏"], meaning:"dusk", emoji:"🌆", gifDuration:1.2, sentence:"焝黄。" },
  { char:"焞", pinyin:"tun1", radical:"火", components:["火","享"], meaning:"dim", emoji:"🌑", gifDuration:1.2, sentence:"焞焞。" },
  { char:"焠", pinyin:"cui4", radical:"火", components:["火","卒"], meaning:"quench", emoji:"🔨", gifDuration:1.2, sentence:"焠火。" },
  { char:"焢", pinyin:"hong1", radical:"火", components:["火","空"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"焢火。" },
  { char:"焥", pinyin:"wa4", radical:"火", components:["火","咼"], meaning:"fire", emoji:"🔥", gifDuration:1.2, sentence:"焥火。" },
  { char:"焦", pinyin:"jiao1", radical:"火", components:["隹","火"], meaning:"burnt", emoji:"🔥", gifDuration:1.2, sentence:"烧焦。" },
  { char:"焯", pinyin:"chao1", radical:"火", components:["火","卓"], meaning:"scald", emoji:"🍲", gifDuration:1.2, sentence:"焯水。" },
  { char:"焮", pinyin:"xin4", radical:"火", components:["火","欣"], meaning:"flame", emoji:"🔥", gifDuration:1.2, sentence:"焮火。" },
  { char:"焰", pinyin:"yan4", radical:"火", components:["火","臽"], meaning:"flame", emoji:"🔥", gifDuration:1.2, sentence:"火焰。" },
  { char:"焱", pinyin:"yan4", radical:"火", components:["火","火","火"], meaning:"flames", emoji:"🔥", gifDuration:1.2, sentence:"焱炎。" },
  { char:"煅", pinyin:"duan4", radical:"火", components:["火","段"], meaning:"calcine", emoji:"🔥", gifDuration:1.2, sentence:"煅烧。" },
  { char:"煸", pinyin:"bian1", radical:"火", components:["火","扁"], meaning:"stir-fry", emoji:"🍳", gifDuration:1.2, sentence:"煸炒。" },
  { char:"煻", pinyin:"tang2", radical:"火", components:["火","唐"], meaning:"warm", emoji:"♨️", gifDuration:1.2, sentence:"煻火。" },
  { char:"煽", pinyin:"shan1", radical:"火", components:["火","扇"], meaning:"fan", emoji:"🌬️", gifDuration:1.2, sentence:"煽动。" },
  { char:"熔", pinyin:"rong2", radical:"火", components:["火","容"], meaning:"melt", emoji:"🔥", gifDuration:1.2, sentence:"熔炉。" },
  { char:"熛", pinyin:"biao1", radical:"火", components:["火","票"], meaning:"spark", emoji:"🔥", gifDuration:1.2, sentence:"熛火。" },
  { char:"熠", pinyin:"yi4", radical:"火", components:["火","習"], meaning:"glimmer", emoji:"✨", gifDuration:1.2, sentence:"熠熠生辉。" },
  { char:"熨", pinyin:"yun4", radical:"火", components:["尉","火"], meaning:"iron", emoji:"👕", gifDuration:1.2, sentence:"熨斗。" },
  { char:"熬", pinyin:"ao2", radical:"火", components:["敖","火"], meaning:"boil", emoji:"🍲", gifDuration:1.2, sentence:"熬夜。" },
  { char:"燠", pinyin:"yu4", radical:"火", components:["火","奥"], meaning:"warm", emoji:"♨️", gifDuration:1.2, sentence:"燠热。" },
  { char:"爆", pinyin:"bao4", radical:"火", components:["火","暴"], meaning:"explode", emoji:"💥", gifDuration:1.2, sentence:"爆炸。" },
  { char:"烁", pinyin:"shuo4", radical:"火", components:["火","乐"], meaning:"shining", emoji:"✨", gifDuration:1.2, sentence:"闪烁。" },
  { char:"烂", pinyin:"lan4", radical:"火", components:["火","兰"], meaning:"rotten", emoji:"🥴", gifDuration:1.2, sentence:"破烂。" },
  { char:"烊", pinyin:"yang2", radical:"火", components:["火","羊"], meaning:"melt", emoji:"🔥", gifDuration:1.2, sentence:"糖烊了。" },

  // ───────────────── 🧮 Miscellaneous objects (radicals: 阝, 匕, 匚, etc.) ─────────────────
  { char:"邗", pinyin:"han2", radical:"阝", components:["干","阝"], meaning:"Han state", emoji:"🏙️", gifDuration:1.2, sentence:"邗江。" },
  { char:"邙", pinyin:"mang2", radical:"阝", components:["亡","阝"], meaning:"Mang Mountain", emoji:"⛰️", gifDuration:1.2, sentence:"北邙。" },
  { char:"邡", pinyin:"fang1", radical:"阝", components:["方","阝"], meaning:"Fang County", emoji:"🏙️", gifDuration:1.2, sentence:"什邡。" },
  { char:"邴", pinyin:"bing3", radical:"阝", components:["丙","阝"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"邴氏。" },
  { char:"邳", pinyin:"pi1", radical:"阝", components:["丕","阝"], meaning:"Pi County", emoji:"🏙️", gifDuration:1.2, sentence:"邳州。" },
  { char:"邶", pinyin:"bei4", radical:"阝", components:["北","阝"], meaning:"Bei state", emoji:"🏰", gifDuration:1.2, sentence:"邶风。" },
  { char:"邸", pinyin:"di3", radical:"阝", components:["氐","阝"], meaning:"residence", emoji:"🏠", gifDuration:1.2, sentence:"官邸。" },
  { char:"邰", pinyin:"tai2", radical:"阝", components:["台","阝"], meaning:"Tai state", emoji:"🏙️", gifDuration:1.2, sentence:"邰城。" },
  { char:"邱", pinyin:"qiu1", radical:"阝", components:["丘","阝"], meaning:"hill", emoji:"⛰️", gifDuration:1.2, sentence:"邱陵。" },
  { char:"邴", pinyin:"bing3", radical:"阝", components:["丙","阝"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"邴姓。" },
  { char:"邶", pinyin:"bei4", radical:"阝", components:["北","阝"], meaning:"ancient state", emoji:"🏯", gifDuration:1.2, sentence:"邶国。" },
  { char:"邯", pinyin:"han2", radical:"阝", components:["甘","阝"], meaning:"Handan", emoji:"🏙️", gifDuration:1.2, sentence:"邯郸。" },
  { char:"邺", pinyin:"ye4", radical:"阝", components:["业","阝"], meaning:"Ye city", emoji:"🏙️", gifDuration:1.2, sentence:"邺城。" },
  { char:"郅", pinyin:"zhi4", radical:"阝", components:["至","阝"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"郅姓。" },
  { char:"郇", pinyin:"huan2", radical:"阝", components:["旬","阝"], meaning:"Xun state", emoji:"🏙️", gifDuration:1.2, sentence:"郇国。" },
  { char:"郈", pinyin:"hou4", radical:"阝", components:["后","阝"], meaning:"Hou state", emoji:"🏙️", gifDuration:1.2, sentence:"郈邑。" },
  { char:"郋", pinyin:"yi2", radical:"阝", components:["自","阝"], meaning:"Yi place", emoji:"🏙️", gifDuration:1.2, sentence:"郋城。" },
  { char:"郏", pinyin:"jia2", radical:"阝", components:["夹","阝"], meaning:"Jia County", emoji:"🏙️", gifDuration:1.2, sentence:"郏县。" },
  { char:"郐", pinyin:"kuai4", radical:"阝", components:["会","阝"], meaning:"Kuai state", emoji:"🏙️", gifDuration:1.2, sentence:"郐国。" },
  { char:"郒", pinyin:"lang2", radical:"阝", components:["良","阝"], meaning:"Lang place", emoji:"🏙️", gifDuration:1.2, sentence:"郒中。" },
  { char:"郔", pinyin:"yan2", radical:"阝", components:["延","阝"], meaning:"Yan place", emoji:"🏙️", gifDuration:1.2, sentence:"郔城。" },
  { char:"郕", pinyin:"cheng2", radical:"阝", components:["成","阝"], meaning:"Cheng state", emoji:"🏙️", gifDuration:1.2, sentence:"郕国。" },
  { char:"郗", pinyin:"xi1", radical:"阝", components:["希","阝"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"郗姓。" },
  { char:"郘", pinyin:"lv3", radical:"阝", components:["吕","阝"], meaning:"village", emoji:"🏘️", gifDuration:1.2, sentence:"郘里。" },
  { char:"郙", pinyin:"fu3", radical:"阝", components:["甫","阝"], meaning:"Fu place", emoji:"🏙️", gifDuration:1.2, sentence:"郙城。" },
  { char:"郚", pinyin:"wu2", radical:"阝", components:["吾","阝"], meaning:"Wu city", emoji:"🏙️", gifDuration:1.2, sentence:"郚城。" },
  { char:"郛", pinyin:"fu2", radical:"阝", components:["孚","阝"], meaning:"suburb", emoji:"🏘️", gifDuration:1.2, sentence:"城郛。" },
  { char:"郜", pinyin:"gao4", radical:"阝", components:["告","阝"], meaning:"Gao state", emoji:"🏙️", gifDuration:1.2, sentence:"郜国。" },
  { char:"郝", pinyin:"hao3", radical:"阝", components:["赤","阝"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"郝先生。" },
  { char:"郞", pinyin:"lang2", radical:"阝", components:["良","阝"], meaning:"Lang", emoji:"🏙️", gifDuration:1.2, sentence:"郞官。" },
  { char:"郟", pinyin:"jia2", radical:"阝", components:["夹","阝"], meaning:"Jia", emoji:"🏙️", gifDuration:1.2, sentence:"郟县。" },
  { char:"郠", pinyin:"geng3", radical:"阝", components:["更","阝"], meaning:"Geng place", emoji:"🏙️", gifDuration:1.2, sentence:"郠城。" },
  { char:"郡", pinyin:"jun4", radical:"阝", components:["君","阝"], meaning:"prefecture", emoji:"🏙️", gifDuration:1.2, sentence:"郡县。" },
  { char:"郢", pinyin:"ying3", radical:"阝", components:["呈","阝"], meaning:"Ying capital", emoji:"🏯", gifDuration:1.2, sentence:"郢都。" },
  { char:"郤", pinyin:"xi4", radical:"阝", components:["谷","阝"], meaning:"surname", emoji:"👤", gifDuration:1.2, sentence:"郤氏。" },
  { char:"郥", pinyin:"bei4", radical:"阝", components:["贝","阝"], meaning:"Bei place", emoji:"🏙️", gifDuration:1.2, sentence:"郥城。" },
  { char:"郦", pinyin:"li4", radical:"阝", components:["丽","阝"], meaning:"Li state", emoji:"🏙️", gifDuration:1.2, sentence:"郦国。" },
  { char:"郧", pinyin:"yun2", radical:"阝", components:["员","阝"], meaning:"Yun County", emoji:"🏙️", gifDuration:1.2, sentence:"郧阳。" },
  { char:"郫", pinyin:"pi2", radical:"阝", components:["卑","阝"], meaning:"Pi County", emoji:"🏙️", gifDuration:1.2, sentence:"郫县。" },
  { char:"郬", pinyin:"qiong1", radical:"阝", components:["青","阝"], meaning:"Qiong place", emoji:"🏙️", gifDuration:1.2, sentence:"郬城。" },
  { char:"郭", pinyin:"xu1", radical:"阝", components:["虚","阝"], meaning:"Xu place", emoji:"🏙️", gifDuration:1.2, sentence:"郭城。" },
  { char:"郮", pinyin:"zhao1", radical:"阝", components:["召","阝"], meaning:"Zhao place", emoji:"🏙️", gifDuration:1.2, sentence:"郮城。" },
  { char:"郯", pinyin:"tan2", radical:"阝", components:["炎","阝"], meaning:"Tan state", emoji:"🏙️", gifDuration:1.2, sentence:"郯城。" },
  { char:"郰", pinyin:"qi1", radical:"阝", components:["其","阝"], meaning:"Qi place", emoji:"🏙️", gifDuration:1.2, sentence:"郰城。" },
  { char:"郱", pinyin:"ping2", radical:"阝", components:["并","阝"], meaning:"Ping place", emoji:"🏙️", gifDuration:1.2, sentence:"郱城。" },
  { char:"郲", pinyin:"lai2", radical:"阝", components:["来","阝"], meaning:"Lai place", emoji:"🏙️", gifDuration:1.2, sentence:"郲城。" },
  { char:"郳", pinyin:"ni2", radical:"阝", components:["尼","阝"], meaning:"Ni place", emoji:"🏙️", gifDuration:1.2, sentence:"郳城。" },
  { char:"郴", pinyin:"chen1", radical:"阝", components:["林","阝"], meaning:"Chenzhou", emoji:"🏙️", gifDuration:1.2, sentence:"郴州。" },
  { char:"郶", pinyin:"bu4", radical:"阝", components:["部","阝"], meaning:"Bu place", emoji:"🏙️", gifDuration:1.2, sentence:"郶城。" },
  { char:"郷", pinyin:"xiang1", radical:"阝", components:["乡","阝"], meaning:"village", emoji:"🏡", gifDuration:1.2, sentence:"郷村。" },
  { char:"郹", pinyin:"ju2", radical:"阝", components:["狊","阝"], meaning:"Ju place", emoji:"🏙️", gifDuration:1.2, sentence:"郹城。" },
  { char:"郺", pinyin:"yong1", radical:"阝", components:["雍","阝"], meaning:"Yong place", emoji:"🏙️", gifDuration:1.2, sentence:"郺城。" },
  { char:"郻", pinyin:"yao2", radical:"阝", components:["遥","阝"], meaning:"Yao place", emoji:"🏙️", gifDuration:1.2, sentence:"郻城。" },
  { char:"郼", pinyin:"zhou1", radical:"阝", components:["舟","阝"], meaning:"Zhou place", emoji:"🏙️", gifDuration:1.2, sentence:"郼城。" },
  { char:"都", pinyin:"dou1", radical:"阝", components:["者","阝"], meaning:"capital", emoji:"🏙️", gifDuration:1.2, sentence:"首都。" },
  { char:"郾", pinyin:"yan3", radical:"阝", components:["匽","阝"], meaning:"Yan city", emoji:"🏙️", gifDuration:1.2, sentence:"郾城。" },
  { char:"郿", pinyin:"mei2", radical:"阝", components:["眉","阝"], meaning:"Mei County", emoji:"🏙️", gifDuration:1.2, sentence:"郿县。" },
  { char:"鄀", pinyin:"ruo4", radical:"阝", components:["若","阝"], meaning:"Ruo state", emoji:"🏙️", gifDuration:1.2, sentence:"鄀国。" },
  { char:"鄁", pinyin:"bei4", radical:"阝", components:["背","阝"], meaning:"Bei place", emoji:"🏙️", gifDuration:1.2, sentence:"鄁城。" },
  { char:"鄃", pinyin:"shu1", radical:"阝", components:["俞","阝"], meaning:"Shu County", emoji:"🏙️", gifDuration:1.2, sentence:"鄃城。" },
  { char:"鄄", pinyin:"juan4", radical:"阝", components:["垔","阝"], meaning:"Juancheng", emoji:"🏙️", gifDuration:1.2, sentence:"鄄城。" },
  { char:"鄅", pinyin:"yu3", radical:"阝", components:["禹","阝"], meaning:"Yu state", emoji:"🏙️", gifDuration:1.2, sentence:"鄅国。" },
  { char:"鄇", pinyin:"hou2", radical:"阝", components:["侯","阝"], meaning:"Hou place", emoji:"🏙️", gifDuration:1.2, sentence:"鄇城。" },
  { char:"鄈", pinyin:"kui2", radical:"阝", components:["癸","阝"], meaning:"Kui place", emoji:"🏙️", gifDuration:1.2, sentence:"鄈城。" },
  { char:"鄋", pinyin:"sou1", radical:"阝", components:["叟","阝"], meaning:"Sou place", emoji:"🏙️", gifDuration:1.2, sentence:"鄋城。" },
  { char:"鄌", pinyin:"tang2", radical:"阝", components:["唐","阝"], meaning:"Tang place", emoji:"🏙️", gifDuration:1.2, sentence:"鄌城。" },
  { char:"鄍", pinyin:"ming2", radical:"阝", components:["冥","阝"], meaning:"Ming place", emoji:"🏙️", gifDuration:1.2, sentence:"鄍城。" },
  { char:"鄎", pinyin:"xi1", radical:"阝", components:["息","阝"], meaning:"Xi place", emoji:"🏙️", gifDuration:1.2, sentence:"鄎城。" },
  { char:"鄏", pinyin:"ru3", radical:"阝", components:["辱","阝"], meaning:"Ru mountain", emoji:"⛰️", gifDuration:1.2, sentence:"鄏山。" },
  { char:"鄐", pinyin:"chu4", radical:"阝", components:["畜","阝"], meaning:"Chu place", emoji:"🏙️", gifDuration:1.2, sentence:"鄐城。" },
  { char:"鄑", pinyin:"zi1", radical:"阝", components:["晋","阝"], meaning:"Zi place", emoji:"🏙️", gifDuration:1.2, sentence:"鄑城。" },
  { char:"鄒", pinyin:"zou1", radical:"阝", components:["刍","阝"], meaning:"Zou state", emoji:"🏙️", gifDuration:1.2, sentence:"鄒城。" },
  { char:"鄓", pinyin:"yu4", radical:"阝", components:["尉","阝"], meaning:"Yu place", emoji:"🏙️", gifDuration:1.2, sentence:"鄓城。" },
  { char:"鄔", pinyin:"wu1", radical:"阝", components:["乌","阝"], meaning:"Wu state", emoji:"🏙️", gifDuration:1.2, sentence:"鄔国。" },
  { char:"鄕", pinyin:"xiang1", radical:"阝", components:["乡","郎"], meaning:"village", emoji:"🏡", gifDuration:1.2, sentence:"乡鄕。" },
  { char:"鄖", pinyin:"yun2", radical:"阝", components:["云","阝"], meaning:"Yun place", emoji:"🏙️", gifDuration:1.2, sentence:"鄖城。" },
  { char:"鄗", pinyin:"hao4", radical:"阝", components:["高","阝"], meaning:"Hao county", emoji:"🏙️", gifDuration:1.2, sentence:"鄗城。" },
  { char:"鄘", pinyin:"yong1", radical:"阝", components:["庸","阝"], meaning:"Yong state", emoji:"🏙️", gifDuration:1.2, sentence:"鄘国。" },
  { char:"鄚", pinyin:"mao4", radical:"阝", components:["莫","阝"], meaning:"Mao place", emoji:"🏙️", gifDuration:1.2, sentence:"鄚城。" },
  { char:"鄛", pinyin:"chao2", radical:"阝", components:["巢","阝"], meaning:"Chao place", emoji:"🏙️", gifDuration:1.2, sentence:"鄛城。" },
  { char:"鄜", pinyin:"fu1", radical:"阝", components:["鹿","阝"], meaning:"Fu county", emoji:"🏙️", gifDuration:1.2, sentence:"鄜州。" },
  { char:"鄝", pinyin:"liao2", radical:"阝", components:["翏","阝"], meaning:"Liao place", emoji:"🏙️", gifDuration:1.2, sentence:"鄝城。" },
  { char:"鄞", pinyin:"yin2", radical:"阝", components:["堇","阝"], meaning:"Yin county", emoji:"🏙️", gifDuration:1.2, sentence:"鄞州。" },
  { char:"鄟", pinyin:"zhuan1", radical:"阝", components:["专","阝"], meaning:"Zhuan place", emoji:"🏙️", gifDuration:1.2, sentence:"鄟城。" },
  { char:"鄠", pinyin:"hu4", radical:"阝", components:["户","阝"], meaning:"Hu county", emoji:"🏙️", gifDuration:1.2, sentence:"鄠邑。" },
  { char:"鄡", pinyin:"qiao1", radical:"阝", components:["枭","阝"], meaning:"Qiao place", emoji:"🏙️", gifDuration:1.2, sentence:"鄡城。" },
  { char:"鄢", pinyin:"yan1", radical:"阝", components:["焉","阝"], meaning:"Yan city", emoji:"🏙️", gifDuration:1.2, sentence:"鄢陵。" },
  { char:"鄣", pinyin:"zhang1", radical:"阝", components:["章","阝"], meaning:"Zhang state", emoji:"🏙️", gifDuration:1.2, sentence:"鄣城。" },
  { char:"鄤", pinyin:"man4", radical:"阝", components:["曼","阝"], meaning:"Man place", emoji:"🏙️", gifDuration:1.2, sentence:"鄤城。" },
  { char:"鄥", pinyin:"qiao2", radical:"阝", components:["乔","阝"], meaning:"Qiao place", emoji:"🏙️", gifDuration:1.2, sentence:"鄥城。" },
  { char:"鄦", pinyin:"xu3", radical:"阝", components:["无","阝"], meaning:"Xu state", emoji:"🏙️", gifDuration:1.2, sentence:"鄦国。" },
  { char:"鄧", pinyin:"deng4", radical:"阝", components:["登","阝"], meaning:"Deng state", emoji:"🏙️", gifDuration:1.2, sentence:"鄧州。" },
  { char:"鄩", pinyin:"xun2", radical:"阝", components:["寻","阝"], meaning:"Xun place", emoji:"🏙️", gifDuration:1.2, sentence:"鄩城。" },
  { char:"鄪", pinyin:"bi4", radical:"阝", components:["费","阝"], meaning:"Bi place", emoji:"🏙️", gifDuration:1.2, sentence:"鄪城。" },
  { char:"鄫", pinyin:"zeng1", radical:"阝", components:["曾","阝"], meaning:"Zeng state", emoji:"🏙️", gifDuration:1.2, sentence:"鄫国。" },
  { char:"鄬", pinyin:"wei2", radical:"阝", components:["为","阝"], meaning:"Wei place", emoji:"🏙️", gifDuration:1.2, sentence:"鄬城。" },
  { char:"鄭", pinyin:"zheng4", radical:"阝", components:["奠","阝"], meaning:"Zheng state", emoji:"🏙️", gifDuration:1.2, sentence:"鄭州。" },
  { char:"鄮", pinyin:"mao4", radical:"阝", components:["貿","阝"], meaning:"Mao county", emoji:"🏙️", gifDuration:1.2, sentence:"鄮县。" },
  { char:"鄯", pinyin:"shan4", radical:"阝", components:["善","阝"], meaning:"Shanshan", emoji:"🏙️", gifDuration:1.2, sentence:"鄯善。" },
  { char:"鄲", pinyin:"dan1", radical:"阝", components:["單","阝"], meaning:"Dan city", emoji:"🏙️", gifDuration:1.2, sentence:"邯鄲。" },
  { char:"鄳", pinyin:"meng2", radical:"阝", components:["黽","阝"], meaning:"Meng place", emoji:"🏙️", gifDuration:1.2, sentence:"鄳城。" },
  { char:"鄴", pinyin:"ye4", radical:"阝", components:["業","阝"], meaning:"Ye city", emoji:"🏙️", gifDuration:1.2, sentence:"鄴城。" },
  { char:"鄵", pinyin:"cao4", radical:"阝", components:["喿","阝"], meaning:"Cao place", emoji:"🏙️", gifDuration:1.2, sentence:"鄵城。" },
  { char:"鄶", pinyin:"kuai4", radical:"阝", components:["會","阝"], meaning:"Kuai state", emoji:"🏙️", gifDuration:1.2, sentence:"鄶国。" },
  { char:"鄷", pinyin:"feng1", radical:"阝", components:["豐","阝"], meaning:"Feng place", emoji:"🏙️", gifDuration:1.2, sentence:"鄷城。" },
  { char:"鄸", pinyin:"meng2", radical:"阝", components:["夢","阝"], meaning:"Meng place", emoji:"🏙️", gifDuration:1.2, sentence:"鄸城。" },
  { char:"鄹", pinyin:"zou1", radical:"阝", components:["聚","阝"], meaning:"Zou county", emoji:"🏙️", gifDuration:1.2, sentence:"鄹城。" },
  { char:"鄺", pinyin:"kuang4", radical:"阝", components:["廣","阝"], meaning:"Kuang place", emoji:"🏙️", gifDuration:1.2, sentence:"鄺城。" },
  { char:"鄻", pinyin:"lian3", radical:"阝", components:["輦","阝"], meaning:"Lian place", emoji:"🏙️", gifDuration:1.2, sentence:"鄻城。" },
  { char:"鄼", pinyin:"cuo2", radical:"阝", components:["贊","阝"], meaning:"Cuo place", emoji:"🏙️", gifDuration:1.2, sentence:"鄼城。" },
  { char:"鄽", pinyin:"chan2", radical:"阝", components:["廛","阝"], meaning:"Chan place", emoji:"🏙️", gifDuration:1.2, sentence:"鄽城。" },
  { char:"鄾", pinyin:"you1", radical:"阝", components:["憂","阝"], meaning:"You place", emoji:"🏙️", gifDuration:1.2, sentence:"鄾城。" },
  { char:"鄿", pinyin:"qi2", radical:"阝", components:["齊","阝"], meaning:"Qi place", emoji:"🏙️", gifDuration:1.2, sentence:"鄿城。" },
  { char:"酀", pinyin:"yan4", radical:"阝", components:["燕","阝"], meaning:"Yan place", emoji:"🏙️", gifDuration:1.2, sentence:"酀城。" },
  { char:"酁", pinyin:"chan2", radical:"阝", components:["毚","阝"], meaning:"Chan place", emoji:"🏙️", gifDuration:1.2, sentence:"酁城。" },
  { char:"酂", pinyin:"cuo2", radical:"阝", components:["贊","阝"], meaning:"Cuo place", emoji:"🏙️", gifDuration:1.2, sentence:"酂城。" },
  { char:"酃", pinyin:"ling2", radical:"阝", components:["霝","阝"], meaning:"Ling county", emoji:"🏙️", gifDuration:1.2, sentence:"酃县。" },
  { char:"酄", pinyin:"huan1", radical:"阝", components:["雚","阝"], meaning:"Huan place", emoji:"🏙️", gifDuration:1.2, sentence:"酄城。" },
  { char:"酅", pinyin:"xi1", radical:"阝", components:["巂","阝"], meaning:"Xi place", emoji:"🏙️", gifDuration:1.2, sentence:"酅城。" },
  { char:"酆", pinyin:"feng1", radical:"阝", components:["豐","阝"], meaning:"Feng capital", emoji:"🏙️", gifDuration:1.2, sentence:"酆都。" },
  { char:"酇", pinyin:"zan4", radical:"阝", components:["贊","阝"], meaning:"Zan place", emoji:"🏙️", gifDuration:1.2, sentence:"酇城。" },
  { char:"酈", pinyin:"li4", radical:"阝", components:["麗","阝"], meaning:"Li county", emoji:"🏙️", gifDuration:1.2, sentence:"酈县。" },

  // ───────────────── 🧮 More tools / utensils / random ─────────────────
  { char:"匜", pinyin:"yi2", radical:"匚", components:["匚","也"], meaning:"washbasin", emoji:"🪣", gifDuration:1.2, sentence:"青铜匜。" },
  { char:"匝", pinyin:"za1", radical:"匚", components:["匚","巾"], meaning:"circuit", emoji:"🔄", gifDuration:1.2, sentence:"一匝。" },
  { char:"匞", pinyin:"jiang4", radical:"匚", components:["匚","工"], meaning:"craftsman", emoji:"🛠️", gifDuration:1.2, sentence:"匞人。" },
  { char:"匟", pinyin:"kang4", radical:"匚", components:["匚","亢"], meaning:"couch", emoji:"🛋️", gifDuration:1.2, sentence:"坐匟。" },
  { char:"匢", pinyin:"hu1", radical:"匚", components:["匚","勿"], meaning:"case", emoji:"📦", gifDuration:1.2, sentence:"匢匣。" },
  { char:"匤", pinyin:"qu1", radical:"匚", components:["匚","玉"], meaning:"box", emoji:"🎁", gifDuration:1.2, sentence:"玉匤。" },
  { char:"匥", pinyin:"bian4", radical:"匚", components:["匚","卞"], meaning:"chest", emoji:"🧳", gifDuration:1.2, sentence:"木匥。" },
  { char:"匦", pinyin:"gui3", radical:"匚", components:["匚","轨"], meaning:"box", emoji:"📦", gifDuration:1.2, sentence:"匦匣。" },
  { char:"匧", pinyin:"qie4", radical:"匚", components:["匚","夹"], meaning:"case", emoji:"📦", gifDuration:1.2, sentence:"书匧。" },
  { char:"匨", pinyin:"zang1", radical:"匚", components:["匚","庄"], meaning:"coffer", emoji:"📦", gifDuration:1.2, sentence:"银匨。" },
  { char:"匩", pinyin:"kuang4", radical:"匚", components:["匚","王"], meaning:"frame", emoji:"🖼️", gifDuration:1.2, sentence:"镜匩。" },
  { char:"匫", pinyin:"hu1", radical:"匚", components:["匚","曶"], meaning:"box", emoji:"📦", gifDuration:1.2, sentence:"匫匣。" },
  { char:"匬", pinyin:"yu3", radical:"匚", components:["匚","俞"], meaning:"bucket", emoji:"🪣", gifDuration:1.2, sentence:"水匬。" },
  { char:"匭", pinyin:"gui3", radical:"匚", components:["匚","匱"], meaning:"cabinet", emoji:"🗄️", gifDuration:1.2, sentence:"书匭。" },
  { char:"匱", pinyin:"kui4", radical:"匚", components:["匚","貴"], meaning:"cabinet", emoji:"🗄️", gifDuration:1.2, sentence:"衣匱。" },
  { char:"匲", pinyin:"lian2", radical:"匚", components:["匚","僉"], meaning:"vanity", emoji:"💄", gifDuration:1.2, sentence:"妆匲。" },
  { char:"匳", pinyin:"lian2", radical:"匚", components:["匚","斂"], meaning:"case", emoji:"📦", gifDuration:1.2, sentence:"印匳。" },
  { char:"匴", pinyin:"suan3", radical:"匚", components:["匚","算"], meaning:"basket", emoji:"🧺", gifDuration:1.2, sentence:"竹匴。" },
  { char:"匵", pinyin:"du2", radical:"匚", components:["匚","賣"], meaning:"cabinet", emoji:"🗄️", gifDuration:1.2, sentence:"书匵。" },
  { char:"匶", pinyin:"jiu4", radical:"匚", components:["匚","舊"], meaning:"coffin", emoji:"⚰️", gifDuration:1.2, sentence:"棺匶。" },
  { char:"匷", pinyin:"jue2", radical:"匚", components:["匚","矍"], meaning:"box", emoji:"📦", gifDuration:1.2, sentence:"匷子。" },
  { char:"匸", pinyin:"xi4", radical:"匚", components:["匚","匕"], meaning:"cover", emoji:"🔒", gifDuration:1.2, sentence:"匸藏。" },
  { char:"匼", pinyin:"ge1", radical:"匚", components:["匚","合"], meaning:"box", emoji:"📦", gifDuration:1.2, sentence:"匼子。" },
  { char:"匽", pinyin:"yan3", radical:"匚", components:["匚","妟"], meaning:"hide", emoji:"🙈", gifDuration:1.2, sentence:"匽蔽。" },
  { char:"匾", pinyin:"bian3", radical:"匚", components:["匚","扁"], meaning:"plaque", emoji:"🏷️", gifDuration:1.2, sentence:"门匾。" },
  { char:"匿", pinyin:"ni4", radical:"匚", components:["匚","若"], meaning:"hide", emoji:"🙈", gifDuration:1.2, sentence:"匿名。" },
  { char:"區", pinyin:"qu1", radical:"匚", components:["匚","品"], meaning:"area", emoji:"📍", gifDuration:1.2, sentence:"區域。" },
  { char:"十", pinyin:"shi2", radical:"十", components:[], meaning:"ten", emoji:"🔟", gifDuration:1, sentence:"十分。" },
  { char:"千", pinyin:"qian1", radical:"十", components:["丿","十"], meaning:"thousand", emoji:"🔢", gifDuration:1, sentence:"千万。" },
  { char:"卅", pinyin:"sa4", radical:"十", components:["卅"], meaning:"thirty", emoji:"3️⃣", gifDuration:1.2, sentence:"卅年。" },
  { char:"升", pinyin:"sheng1", radical:"十", components:["丿","廾"], meaning:"rise", emoji:"⬆️", gifDuration:1.2, sentence:"升旗。" },
  { char:"午", pinyin:"wu3", radical:"十", components:["午"], meaning:"noon", emoji:"🕛", gifDuration:1.2, sentence:"中午。" },
  { char:"半", pinyin:"ban4", radical:"丶", components:["丷","十"], meaning:"half", emoji:"🕐", gifDuration:1.2, sentence:"一半。" },
  { char:"卌", pinyin:"xi4", radical:"十", components:["卌"], meaning:"forty", emoji:"4️⃣", gifDuration:1.2, sentence:"卌岁。" },
  { char:"卍", pinyin:"wan4", radical:"十", components:["卍"], meaning:"swastika", emoji:"卐", gifDuration:1.2, sentence:"卍字。" },
  { char:"华", pinyin:"hua2", radical:"十", components:["化","十"], meaning:"China", emoji:"🇨🇳", gifDuration:1.2, sentence:"中华。" },
  { char:"协", pinyin:"xie2", radical:"十", components:["十","办"], meaning:"cooperate", emoji:"🤝", gifDuration:1.2, sentence:"合作。" },
  { char:"卑", pinyin:"bei1", radical:"十", components:["白","十"], meaning:"low", emoji:"👇", gifDuration:1.2, sentence:"卑鄙。" },
  { char:"卒", pinyin:"zu2", radical:"十", components:["衣","十"], meaning:"soldier", emoji:"🎖️", gifDuration:1.2, sentence:"小卒。" },
  { char:"卓", pinyin:"zhuo2", radical:"十", components:["卜","早"], meaning:"outstanding", emoji:"🌟", gifDuration:1.2, sentence:"卓越。" },
  { char:"南", pinyin:"nan2", radical:"十", components:["十","冂","?","?"], meaning:"south", emoji:"🧭", gifDuration:1.2, sentence:"南方。" },
  { char:"博", pinyin:"bo2", radical:"十", components:["十","甫","寸"], meaning:"extensive", emoji:"📚", gifDuration:1.2, sentence:"博士。" },
  { char:"卜", pinyin:"bu3", radical:"卜", components:[], meaning:"divination", emoji:"🔮", gifDuration:1, sentence:"占卜。" },
  { char:"卞", pinyin:"bian4", radical:"卜", components:["亠","卜"], meaning:"hurried", emoji:"⏩", gifDuration:1.2, sentence:"卞急。" },
  { char:"卟", pinyin:"ji1", radical:"卜", components:["口","卜"], meaning:"divine", emoji:"🤔", gifDuration:1.2, sentence:"卟问。" },
  { char:"卡", pinyin:"ka3", radical:"卜", components:["上","卜"], meaning:"card", emoji:"🃏", gifDuration:1.2, sentence:"信用卡。" },
  { char:"卣", pinyin:"you3", radical:"卜", components:["?","卜"], meaning:"wine vessel", emoji:"🏺", gifDuration:1.2, sentence:"青铜卣。" },
  { char:"卤", pinyin:"lu3", radical:"卜", components:["⺊","卤"], meaning:"brine", emoji:"🧂", gifDuration:1.2, sentence:"卤水。" },
  { char:"卦", pinyin:"gua4", radical:"卜", components:["圭","卜"], meaning:"divination", emoji:"🔮", gifDuration:1.2, sentence:"八卦。" },
  { char:"卧", pinyin:"wo4", radical:"卜", components:["臣","卜"], meaning:"lie down", emoji:"🛌", gifDuration:1.2, sentence:"卧倒。" },

  // ───────────────── 🧮 More misc ─────────────────
  { char:"卮", pinyin:"zhi1", radical:"卩", components:["?","卩"], meaning:"goblet", emoji:"🥂", gifDuration:1.2, sentence:"酒卮。" },
  { char:"卯", pinyin:"mao3", radical:"卩", components:["卩"], meaning:"mortise", emoji:"🔩", gifDuration:1.2, sentence:"子午卯酉。" },
  { char:"印", pinyin:"yin4", radical:"卩", components:["爪","卩"], meaning:"print", emoji:"🖨️", gifDuration:1.2, sentence:"打印。" },
  { char:"危", pinyin:"wei1", radical:"卩", components:["厃","卩"], meaning:"danger", emoji:"⚠️", gifDuration:1.2, sentence:"危险。" },
  { char:"却", pinyin:"que4", radical:"卩", components:["去","卩"], meaning:"but", emoji:"↩️", gifDuration:1.2, sentence:"却步。" },
  { char:"卵", pinyin:"luan3", radical:"卩", components:["?","丶","卩"], meaning:"egg", emoji:"🥚", gifDuration:1.2, sentence:"卵子。" },
  { char:"卷", pinyin:"juan3", radical:"卩", components:["?","卩"], meaning:"roll", emoji:"📜", gifDuration:1.2, sentence:"试卷。" },
  { char:"卸", pinyin:"xie4", radical:"卩", components:["?","卩"], meaning:"unload", emoji:"📤", gifDuration:1.2, sentence:"卸货。" },
  { char:"卺", pinyin:"jin3", radical:"卩", components:["丞","卩"], meaning:"nuptial cup", emoji:"🍻", gifDuration:1.2, sentence:"合卺。" },
  { char:"卼", pinyin:"wu4", radical:"尢", components:["兀","危"], meaning:"unsteady", emoji:"😵", gifDuration:1.2, sentence:"危卼。" },
  { char:"厃", pinyin:"wei1", radical:"厂", components:["人","厂"], meaning:"danger", emoji:"⚠️", gifDuration:1.2, sentence:"厃险。" },
  { char:"厇", pinyin:"zhe2", radical:"厂", components:["厂","乇"], meaning:"open", emoji:"🔓", gifDuration:1.2, sentence:"厇开。" },
  { char:"厈", pinyin:"an4", radical:"厂", components:["厂","干"], meaning:"shore", emoji:"🏖️", gifDuration:1.2, sentence:"江厈。" },
  { char:"厉", pinyin:"qi4", radical:"厂", components:["厂","气"], meaning:"cliff", emoji:"⛰️", gifDuration:1.2, sentence:"山厉。" },
  { char:"厊", pinyin:"ya3", radical:"厂", components:["厂","牙"], meaning:"crack", emoji:"💔", gifDuration:1.2, sentence:"厊缝。" },
  { char:"厎", pinyin:"di3", radical:"厂", components:["厂","氐"], meaning:"bottom", emoji:"⬇️", gifDuration:1.2, sentence:"厎石。" },
  { char:"厏", pinyin:"zha3", radical:"厂", components:["厂","乍"], meaning:"narrow", emoji:"📏", gifDuration:1.2, sentence:"厏窄。" },
  { char:"厐", pinyin:"pang2", radical:"厂", components:["厂","龙"], meaning:"big", emoji:"🐘", gifDuration:1.2, sentence:"厐大。" },
  { char:"厑", pinyin:"a1", radical:"厂", components:["厂","阿"], meaning:"shed", emoji:"🏚️", gifDuration:1.2, sentence:"草厑。" },
  { char:"厒", pinyin:"he2", radical:"厂", components:["厂","合"], meaning:"side", emoji:"↔️", gifDuration:1.2, sentence:"厒岸。" },
  { char:"厓", pinyin:"ya2", radical:"厂", components:["厂","圭"], meaning:"cliff", emoji:"⛰️", gifDuration:1.2, sentence:"山厓。" },
  { char:"厔", pinyin:"zhi4", radical:"厂", components:["厂","至"], meaning:"stop", emoji:"🛑", gifDuration:1.2, sentence:"厔步。" },
  { char:"厗", pinyin:"ti2", radical:"厂", components:["厂","弟"], meaning:"cliff", emoji:"⛰️", gifDuration:1.2, sentence:"厗壁。" },
  { char:"厙", pinyin:"ku4", radical:"厂", components:["厂","库"], meaning:"warehouse", emoji:"🏬", gifDuration:1.2, sentence:"仓厙。" },
  { char:"厛", pinyin:"ting2", radical:"厂", components:["厂","廷"], meaning:"hall", emoji:"🏛️", gifDuration:1.2, sentence:"厛堂。" },
  { char:"厜", pinyin:"zui1", radical:"厂", components:["厂","此"], meaning:"corner", emoji:"📐", gifDuration:1.2, sentence:"山厜。" },
  { char:"厝", pinyin:"cuo4", radical:"厂", components:["厂","昔"], meaning:"place", emoji:"📍", gifDuration:1.2, sentence:"厝身。" },
  { char:"厞", pinyin:"fei4", radical:"厂", components:["厂","非"], meaning:"side", emoji:"↔️", gifDuration:1.2, sentence:"山厞。" },
  { char:"原", pinyin:"yuan2", radical:"厂", components:["厂","泉"], meaning:"origin", emoji:"🔙", gifDuration:1.2, sentence:"原来。" },
  { char:"厠", pinyin:"ce4", radical:"厂", components:["厂","则"], meaning:"toilet", emoji:"🚽", gifDuration:1.2, sentence:"厠所。" },
  { char:"厢", pinyin:"xiang1", radical:"厂", components:["厂","相"], meaning:"compartment", emoji:"🚃", gifDuration:1.2, sentence:"车厢。" },
  { char:"厡", pinyin:"yuan2", radical:"厂", components:["厂","原"], meaning:"origin", emoji:"🔙", gifDuration:1.2, sentence:"厡来。" },
  { char:"厥", pinyin:"jue2", radical:"厂", components:["厂","欮"], meaning:"faint", emoji:"😵", gifDuration:1.2, sentence:"昏厥。" },
  { char:"厦", pinyin:"sha4", radical:"厂", components:["厂","夏"], meaning:"mansion", emoji:"🏢", gifDuration:1.2, sentence:"大厦。" },
  { char:"厨", pinyin:"chu2", radical:"厂", components:["厂","豆","寸"], meaning:"kitchen", emoji:"🍳", gifDuration:1.3, sentence:"厨房。" },
  { char:"厬", pinyin:"gui3", radical:"厂", components:["厂","晷"], meaning:"exhausted", emoji:"😩", gifDuration:1.2, sentence:"厬竭。" },
  { char:"厭", pinyin:"yan4", radical:"厂", components:["厂","猒"], meaning:"dislike", emoji:"😒", gifDuration:1.2, sentence:"厭恶。" },
  { char:"厮", pinyin:"si1", radical:"厂", components:["厂","斯"], meaning:"servant", emoji:"🧹", gifDuration:1.2, sentence:"小厮。" },
  { char:"厱", pinyin:"qian1", radical:"厂", components:["厂","僉"], meaning:"cliff", emoji:"⛰️", gifDuration:1.2, sentence:"厱崖。" },
  { char:"厲", pinyin:"li4", radical:"厂", components:["厂","萬"], meaning:"strict", emoji:"😤", gifDuration:1.2, sentence:"嚴厲。" },
  { char:"厳", pinyin:"yan2", radical:"厂", components:["厂","敢"], meaning:"strict", emoji:"😠", gifDuration:1.2, sentence:"厳格。" },
  { char:"厴", pinyin:"yan3", radical:"厂", components:["厂","厭"], meaning:"kitchen", emoji:"🍳", gifDuration:1.2, sentence:"庖厴。" },
  { char:"厵", pinyin:"yuan2", radical:"厂", components:["厂","原"], meaning:"origin", emoji:"🔙", gifDuration:1.2, sentence:"厵始。" },
  { char:"厷", pinyin:"gong1", radical:"厶", components:["ㄥ","厶"], meaning:"arm", emoji:"💪", gifDuration:1.2, sentence:"厷骨。" },
  { char:"参", pinyin:"can1", radical:"厶", components:["厶","大","彡"], meaning:"participate", emoji:"🙋", gifDuration:1.3, sentence:"参加。" },
  { char:"叄", pinyin:"can1", radical:"厶", components:["参"], meaning:"three", emoji:"3️⃣", gifDuration:1.2, sentence:"叄天。" },
  { char:"叉", pinyin:"cha1", radical:"又", components:["又","丶"], meaning:"fork", emoji:"🍴", gifDuration:1.2, sentence:"叉子。" },
  { char:"及", pinyin:"ji2", radical:"又", components:["人","又"], meaning:"and", emoji:"🔗", gifDuration:1.2, sentence:"以及。" },
  { char:"友", pinyin:"you3", radical:"又", components:["又","又"], meaning:"friend", emoji:"👫", gifDuration:1.2, sentence:"朋友。" },
  { char:"双", pinyin:"shuang1", radical:"又", components:["又","又"], meaning:"pair", emoji:"👯", gifDuration:1.2, sentence:"一双。" },
  { char:"反", pinyin:"fan3", radical:"又", components:["厂","又"], meaning:"opposite", emoji:"↔️", gifDuration:1.2, sentence:"反对。" },
  { char:"发", pinyin:"fa1", radical:"又", components:["丿","又"], meaning:"send", emoji:"📤", gifDuration:1.2, sentence:"发送。" },
  { char:"叔", pinyin:"shu1", radical:"又", components:["上","小","又"], meaning:"uncle", emoji:"👨", gifDuration:1.2, sentence:"叔叔。" },
  { char:"取", pinyin:"qu3", radical:"又", components:["耳","又"], meaning:"take", emoji:"✋", gifDuration:1.2, sentence:"取款。" },
  { char:"受", pinyin:"shou4", radical:"又", components:["爪","冖","又"], meaning:"receive", emoji:"📥", gifDuration:1.2, sentence:"接受。" },
  { char:"变", pinyin:"bian4", radical:"又", components:["亦","又"], meaning:"change", emoji:"🔄", gifDuration:1.2, sentence:"变化。" },
  { char:"叙", pinyin:"xu4", radical:"又", components:["余","又"], meaning:"narrate", emoji:"📖", gifDuration:1.2, sentence:"叙述。" },
  { char:"叛", pinyin:"pan4", radical:"又", components:["半","反"], meaning:"rebel", emoji:"⚔️", gifDuration:1.2, sentence:"叛变。" },
  { char:"叟", pinyin:"sou3", radical:"又", components:["臼","丨","又"], meaning:"old man", emoji:"👴", gifDuration:1.2, sentence:"老叟。" },
  { char:"叠", pinyin:"die2", radical:"又", components:["叒","冝","又"], meaning:"stack", emoji:"📚", gifDuration:1.3, sentence:"叠被子。" },
  { char:"燮", pinyin:"xie4", radical:"火", components:["火","言","又"], meaning:"harmony", emoji:"🕊️", gifDuration:1.3, sentence:"燮理。" },
  { char:"夊", pinyin:"sui1", radical:"夊", components:[], meaning:"walk slowly", emoji:"🚶", gifDuration:1, sentence:"夊步。" },
  { char:"夋", pinyin:"qun1", radical:"夊", components:["允","夊"], meaning:"falter", emoji:"🐢", gifDuration:1.2, sentence:"夋巡。" },
  { char:"夌", pinyin:"ling2", radical:"夊", components:["土","夊"], meaning:"tall", emoji:"⛰️", gifDuration:1.2, sentence:"夌山。" },
  { char:"夎", pinyin:"cuo4", radical:"夊", components:["坐","夊"], meaning:"kneel", emoji:"🧎", gifDuration:1.2, sentence:"夎拜。" },
  { char:"夒", pinyin:"nao2", radical:"夊", components:["夒"], meaning:"monkey", emoji:"🐒", gifDuration:1.2, sentence:"夒猿。" },
  { char:"夓", pinyin:"xia4", radical:"夊", components:["頁","夊"], meaning:"summer", emoji:"☀️", gifDuration:1.2, sentence:"炎夓。" },
  { char:"夔", pinyin:"kui2", radical:"夊", components:["首","止","巳","夊"], meaning:"one-legged monster", emoji:"👹", gifDuration:1.3, sentence:"夔牛。" },
  { char:"夗", pinyin:"yuan4", radical:"夕", components:["夕","卩"], meaning:"turn over", emoji:"🔄", gifDuration:1.2, sentence:"夗转。" },
  { char:"夞", pinyin:"xi1", radical:"夊", components:["夊","希"], meaning:"slow", emoji:"🐢", gifDuration:1.2, sentence:"夞行。" }
];