const componentMeanings = {
  // Basic radicals & high-frequency
  "走":"walk","彳":"step","正":"correct","己":"self","戉":"axe","召":"call","干":"dry",
  "乂":"govern","刍":"hay","尚":"still","夂":"go slowly","余":"surplus","㝵":"obtain",
  "寸":"inch","聿":"brush","廴":"move","木":"tree","田":"field","火":"fire",
  "一":"one","水":"water","氵":"water","可":"able","每":"every","工":"work",
  "十":"ten","也":"also","先":"before","山":"mountain","石":"stone","厂":"cliff",
  "夹":"squeeze","夆":"meet","广":"wide","开":"open","皮":"skin","更":"more",
  "日":"sun","月":"moon","生":"birth","𡗸":"?","雨":"rain","彐":"snout",
  "务":"task","亻":"person","尔":"you","门":"gate","乍":"first","言":"speech",
  "专":"focus","女":"woman","子":"child","马":"horse","昏":"dusk","未":"not yet",
  "亥":"sign","⺈":"knife","冖":"cover","口":"mouth","乞":"beg","曷":"why",
  "昌":"bright","心":"heart","亡":"die","夬":"decide","相":"mutual","宀":"roof",
  "豕":"pig","至":"arrive","吕":"spine","占":"occupy","付":"pay","力":"strength",
  "土":"earth","门":"gate","间":"between","问":"ask","手":"hand","丁":"adult",
  "扌":"hand","巴":"snake","合":"join","妾":"concubine","刀":"knife","七":"seven",
  "八":"eight","纟":"silk","钅":"metal","艮":"stop","戋":"small","讠":"speech",
  "舌":"tongue","兑":"exchange","儿":"child","斤":"axe","欠":"lack",
  "王":"king","玉":"jade","里":"inside","阝":"city","⻏":"mound","贝":"shell",
  "车":"vehicle","长":"long","页":"page","见":"see",
  "不":"not","之":"of","习":"practice","飞":"fly","食":"food","鱼":"fish",
  "鸟":"bird","饣":"food","马":"horse","风":"wind",
  "立":"stand","音":"sound","甘":"sweet","疒":"sickness","示":"altar",
  "衤":"clothes","角":"horn","豆":"bean","酉":"wine","足":"foot",
  "身":"body","歹":"death","骨":"bone","鬼":"ghost","牛":"cow","犬":"dog",
  "犭":"dog","爪":"claw","父":"father","爻":"intertwine","爿":"bed",
  "片":"slice","斤":"axe","欠":"yawn","戈":"spear","户":"door",
  "气":"air","毛":"hair","比":"compare","瓦":"tile","甘":"sweet",
  "目":"eye","矢":"arrow","禾":"grain","白":"white","瓜":"melon",
  "疒":"sick","立":"stand","衤":"clothes","穴":"cave","虫":"insect",
  "竹":"bamboo","米":"rice","舟":"boat","羽":"feather","老":"old",
  "而":"and","耂":"old","耳":"ear","聿":"brush","臣":"minister",
  "自":"self","至":"arrive","臼":"mortar","舌":"tongue","艮":"tough",
  "色":"color","艹":"grass","虍":"tiger","羊":"sheep","⺷":"sheep",
  "羽":"feather","辰":"morning","辶":"walk","邑":"city","酉":"alcohol",
  "釆":"divide","里":"village","金":"metal","隹":"bird","青":"blue",
  "雨":"rain","非":"not","面":"face","革":"leather","韦":"leather",
  "音":"sound","頁":"page","风":"wind","食":"eat","馬":"horse",
  "宀":"roof","爫":"claw","冫":"ice","刂":"knife","冖":"cover",
  "⺌":"small","夊":"go slowly","夂":"go slowly","彡":"hair","幺":"tiny",
  "廴":"move","廾":"two hands","忄":"heart","扌":"hand","氵":"water",
  "犭":"dog","王":"jade","礻":"spirit","⺮":"bamboo","衤":"clothes",
  "讠":"speech","贝":"shell","车":"cart","钅":"metal","饣":"food",
  "灬":"fire","冖":"cover","宀":"roof","彡":"hair","彳":"step","忄":"heart",
  "扌":"hand","氵":"water","艹":"grass","辶":"walk","阝":"mound",
  "⺮":"bamboo","讠":"speech","饣":"food","纟":"silk","钅":"metal",
  "门":"door","马":"horse","鱼":"fish","鸟":"bird","虫":"insect",
  "日":"sun","月":"moon","山":"mountain","石":"stone","火":"fire",
  "水":"water","木":"tree","金":"metal","土":"earth",
  "又":"again","寸":"inch","小":"small","大":"big","中":"middle",
  "上":"up","下":"down","左":"left","右":"right","前":"front","后":"back",
  "里":"in","外":"out","东":"east","西":"west","南":"south","北":"north",
  "白":"white","黑":"black","红":"red","黄":"yellow","绿":"green",
  "青":"blue","紫":"purple","蓝":"blue","灰":"grey",
  "米":"rice","面":"flour","豆":"bean","瓜":"melon","果":"fruit",
  "菜":"vegetable","茶":"tea","酒":"alcohol","肉":"meat","魚":"fish",
  "食":"food","饭":"rice","汤":"soup","奶":"milk","水":"water",
  "人":"person","口":"mouth","手":"hand","足":"foot","目":"eye",
  "耳":"ear","鼻":"nose","心":"heart","身":"body","骨":"bone",
  "父":"father","母":"mother","子":"child","女":"woman","男":"man",
  "老":"old","幼":"young","朋":"friend","敌":"enemy",
  "學":"study","問":"ask","寫":"write","讀":"read","見":"see",
  "聽":"hear","說":"speak","想":"think","愛":"love","恨":"hate",
  "喜":"happy","怒":"angry","哀":"sad","樂":"joy","怕":"fear",
  "龍":"dragon","鳳":"phoenix","虎":"tiger","獅":"lion","象":"elephant",
  "貓":"cat","狗":"dog","牛":"ox","羊":"sheep","馬":"horse",
  "雞":"chicken","鴨":"duck","鵝":"goose","鳥":"bird","魚":"fish",
  "蛙":"frog","蛇":"snake","蟲":"insect","蝶":"butterfly","蜂":"bee",
  "舟":"boat","車":"car","飛":"fly","行":"go","走":"walk",
  "跑":"run","跳":"jump","游":"swim","騎":"ride","駕":"drive",
  "出":"out","入":"enter","進":"enter","退":"retreat",
  "開":"open","關":"close","來":"come","去":"go",
  "上":"up","下":"down","左":"left","右":"right",
  "高":"tall","低":"low","遠":"far","近":"near",
  "多":"many","少":"few","大":"big","小":"small",
  "一":"1","二":"2","三":"3","四":"4","五":"5",
  "六":"6","七":"7","八":"8","九":"9","十":"10",
  "百":"100","千":"1000","万":"10000","亿":"100 million",
  "年":"year","月":"month","日":"day","时":"hour","分":"minute",
  "今天":"today","昨天":"yesterday","明天":"tomorrow",
  "春":"spring","夏":"summer","秋":"autumn","冬":"winter",
  "东":"east","南":"south","西":"west","北":"north",
  "金":"gold","木":"wood","水":"water","火":"fire","土":"earth",
  "风":"wind","云":"cloud","雨":"rain","雪":"snow","电":"electricity",
  "天":"sky","地":"earth","山":"mountain","河":"river","海":"sea",
  "湖":"lake","岛":"island","星":"star","月":"moon","日":"sun",
  "花":"flower","草":"grass","树":"tree","叶":"leaf","果":"fruit",
  "书":"book","笔":"pen","纸":"paper","刀":"knife","剑":"sword",
  "钱":"money","金":"gold","银":"silver","铜":"copper","铁":"iron",
  "王":"king","主":"master","臣":"minister","民":"people",
  "军":"army","兵":"soldier","战":"war","和":"peace",
  "国":"country","家":"home","城":"city","村":"village",
  "路":"road","桥":"bridge","門":"gate","窗":"window",
  "桌":"table","椅":"chair","床":"bed","窗":"window",
  "灯":"lamp","机":"machine","车":"vehicle",
  "手":"hand","机":"machine","电":"electricity","话":"speech",
  "网":"net","信":"letter","息":"breath",
  "计":"calculate","算":"calculate","机":"machine",
  "科":"science","学":"study","校":"school",
  "医":"medicine","院":"courtyard","药":"medicine",
  "身":"body","体":"body","健":"health","康":"peace",
  "心":"heart","理":"reason","情":"feeling","感":"feel",
  "爱":"love","恨":"hate","思":"think","想":"think",
  // Additional from parts 6/7
  "匕":"spoon","匚":"box","卜":"divination","卩":"seal","儿":"child",
  "八":"eight","入":"enter","厶":"private","厶":"private","厂":"cliff",
  "又":"again","口":"mouth","囗":"enclosure","夊":"slow","夕":"evening",
  "大":"big","女":"woman","子":"child","宀":"roof","寸":"inch",
  "小":"small","尢":"lame","尸":"corpse","屮":"sprout","山":"mountain",
  "巛":"river","工":"work","己":"self","巾":"cloth","干":"dry",
  "幺":"tiny","广":"shelter","廴":"move","廾":"two hands","弋":"shoot",
  "弓":"bow","彐":"snout","彡":"hair","彳":"step","心":"heart",
  "戈":"spear","户":"door","手":"hand","支":"branch","攵":"tap",
  "文":"literature","斗":"dipper","斤":"axe","方":"square","无":"not",
  "日":"sun","曰":"say","月":"moon","木":"tree","欠":"lack",
  "止":"stop","歹":"death","殳":"weapon","毋":"do not","比":"compare",
  "毛":"hair","氏":"clan","气":"air","水":"water","火":"fire",
  "爪":"claw","父":"father","爻":"cross","爿":"wood","片":"slice",
  "牙":"tooth","牛":"cow","犬":"dog","玄":"dark","玉":"jade",
  "瓜":"melon","瓦":"tile","甘":"sweet","生":"life","用":"use",
  "田":"field","疋":"bolt","疒":"sick","癶":"back","白":"white",
  "皮":"skin","皿":"dish","目":"eye","矛":"spear","矢":"arrow",
  "石":"stone","示":"spirit","禸":"track","禾":"grain","穴":"cave",
  "立":"stand","竹":"bamboo","米":"rice","糸":"silk","缶":"jar",
  "网":"net","羊":"sheep","羽":"feather","老":"old","而":"and",
  "耂":"old","耳":"ear","聿":"brush","肉":"meat","臣":"minister",
  "自":"self","至":"arrive","臼":"mortar","舌":"tongue","舛":"oppose",
  "舟":"boat","艮":"tough","色":"color","艹":"grass","虍":"tiger",
  "虫":"insect","血":"blood","行":"go","衣":"clothes","襾":"cover",
  "见":"see","角":"horn","言":"speech","谷":"valley","豆":"bean",
  "豕":"pig","豸":"beast","贝":"shell","赤":"red","走":"walk",
  "足":"foot","身":"body","车":"cart","辛":"bitter","辰":"morning",
  "辵":"walk","邑":"city","酉":"wine","釆":"divide","里":"village",
  "金":"metal","长":"long","门":"door","阜":"mound","隶":"slave",
  "隹":"bird","雨":"rain","青":"blue","非":"not","面":"face",
  "革":"leather","韦":"leather","韭":"leek","音":"sound","页":"page",
  "风":"wind","飞":"fly","食":"eat","首":"head","香":"fragrant",
  "马":"horse","骨":"bone","高":"high","髟":"hair","鬥":"fight",
  "鬯":"sacrificial wine","鬲":"cauldron","鬼":"ghost","鱼":"fish",
  "鸟":"bird","卤":"salt","鹿":"deer","麦":"wheat","麻":"hemp",
  "黄":"yellow","黍":"millet","黑":"black","黹":"embroidery",
  "黾":"frog","鼎":"tripod","鼓":"drum","鼠":"rat","鼻":"nose",
  "齐":"neat","齿":"tooth","龙":"dragon","龟":"turtle",
  // Components found in part6/7
  "夋":"falter","夒":"monkey","夓":"summer","夔":"monster",
  "匜":"basin","匝":"circuit","匞":"craftsman","匟":"couch",
  "匢":"case","匤":"box","匥":"chest","匦":"box","匧":"case",
  "匨":"coffer","匩":"frame","匫":"box","匬":"bucket","匭":"cabinet",
  "匱":"cabinet","匲":"vanity","匳":"case","匴":"basket","匵":"cabinet",
  "匶":"coffin","匷":"box","匸":"cover","匼":"box","匽":"hide",
  "匾":"plaque","匿":"hide","區":"area",
  "十":"ten","千":"thousand","卅":"thirty","升":"rise","午":"noon",
  "半":"half","卌":"forty","卍":"swastika","华":"China","协":"cooperate",
  "卑":"low","卒":"soldier","卓":"outstanding","南":"south","博":"extensive",
  "卜":"divination","卞":"hurried","卟":"divine","卡":"card","卣":"wine vessel",
  "卤":"brine","卦":"divination","卧":"lie down",
  "卮":"goblet","卯":"mortise","印":"print","危":"danger","却":"but",
  "卵":"egg","卷":"roll","卸":"unload","卺":"nuptial cup",
  "卼":"unsteady","厃":"danger","厇":"open","厈":"shore","厉":"cliff",
  "厊":"crack","厎":"bottom","厏":"narrow","厐":"big","厑":"shed",
  "厒":"side","厓":"cliff","厔":"stop","厗":"cliff","厙":"warehouse",
  "厛":"hall","厜":"corner","厝":"place","厞":"side","原":"origin",
  "厠":"toilet","厢":"compartment","厡":"origin","厥":"faint","厦":"mansion",
  "厨":"kitchen","厬":"exhausted","厭":"dislike","厮":"servant",
  "厱":"cliff","厲":"strict","厳":"strict","厴":"kitchen","厵":"origin",
  "厷":"arm","参":"participate","叄":"three",
  "叉":"fork","及":"and","友":"friend","双":"pair","反":"opposite",
  "发":"send","叔":"uncle","取":"take","受":"receive","变":"change",
  "叙":"narrate","叛":"rebel","叟":"old man","叠":"stack","燮":"harmony",
  "夊":"walk slowly","夌":"tall","夎":"kneel","夗":"turn over",
  "夞":"slow",
  // For the element series
  "气":"air","氕":"protium","氘":"deuterium","氚":"tritium",
  "氙":"xenon","氜":"helium","氛":"atmosphere","氟":"fluorine",
  "氪":"krypton","氖":"neon","氡":"radon","氩":"argon",
  "氤":"misty","氲":"thick","氵":"water",
  "氾":"flood","氿":"spring","汀":"sandbank","汁":"juice",
  "汇":"converge","汉":"Han","汈":"Diao River","泛":"float",
  "汍":"shed tears","汎":"wide","汏":"cleanse","汐":"night tide",
  "汔":"almost","汕":"Swatow","汗":"sweat","沆":"vast",
  "沈":"sink","沉":"sink","沌":"chaos","沍":"frozen",
  "沏":"infuse","沐":"bathe","沔":"flood","沛":"copious",
  "沗":"vast","沘":"Bi River","沙":"sand","沚":"islet",
  "洵":"true","洹":"Huan River","洺":"Ming River","活":"live",
  "洼":"hollow","洽":"negotiate","派":"faction","浔":"water edge",
  "洛":"Luo River","浏":"clear","济":"help","浑":"muddy",
  "浓":"dense","浙":"Zhejiang","浚":"dredge","浣":"wash",
  "浦":"river bank","浩":"vast","浪":"wave","浮":"float",
  "浴":"bathe","浸":"soak","涂":"paint","涅":"black dye",
  "消":"disappear","涉":"wade","涌":"gush","涕":"tears",
  "涛":"billows","涡":"whirlpool","润":"moist","涨":"rise",
  "涩":"astringent","涯":"shore","液":"liquid","涵":"contain",
  "凉":"cool","淀":"sediment","淄":"black","淅":"drizzle",
  "淆":"confuse","淇":"Qi River","淋":"drench","淌":"drip",
  "淑":"gentle","淘":"wash","淚":"tears","淡":"insipid",
  "淨":"clean","淪":"sink","淫":"excessive","淮":"Huai River",
  "深":"deep","淳":"honest","混":"mix","淹":"flood",
  "淺":"shallow","添":"add","清":"clear","渊":"abyss",
  "渐":"gradually","温":"warm",
  // some more
  "亻":"person","彳":"step","厶":"private","夂":"walk",
  "卩":"seal","屮":"sprout","巛":"river",
  "宀":"roof","爫":"claw","冫":"ice","刂":"knife",
  "冖":"cover","⺌":"small","夊":"go slowly","夂":"go slowly",
  "彡":"hair","幺":"tiny","廴":"move","廾":"two hands",
  "忄":"heart","扌":"hand","氵":"water","犭":"dog",
  "王":"jade","礻":"spirit","⺮":"bamboo","衤":"clothes",
  "讠":"speech","贝":"shell","车":"cart","钅":"metal",
  "饣":"food","灬":"fire","冖":"cover","宀":"roof",
  "彡":"hair","彳":"step","忄":"heart","扌":"hand",
  "氵":"water","艹":"grass","辶":"walk","阝":"mound",
  "⺮":"bamboo","讠":"speech","饣":"food","纟":"silk",
  "钅":"metal","门":"door","马":"horse","鱼":"fish",
  "鸟":"bird","虫":"insect","日":"sun","月":"moon",
  "山":"mountain","石":"stone","火":"fire","水":"water",
  "木":"tree","金":"metal","土":"earth",
  "又":"again","寸":"inch","小":"small","大":"big",
  "中":"middle","上":"up","下":"down","左":"left",
  "右":"right","前":"front","后":"back","里":"in",
  "外":"out","东":"east","西":"west","南":"south","北":"north",
  "白":"white","黑":"black","红":"red","黄":"yellow","绿":"green",
  "青":"blue","紫":"purple","蓝":"blue","灰":"grey",
  "米":"rice","面":"flour","豆":"bean","瓜":"melon","果":"fruit",
  "菜":"vegetable","茶":"tea","酒":"alcohol","肉":"meat",
  "食":"food","饭":"rice","汤":"soup","奶":"milk",
  "人":"person","口":"mouth","手":"hand","足":"foot","目":"eye",
  "耳":"ear","鼻":"nose","心":"heart","身":"body","骨":"bone",
  "父":"father","母":"mother","子":"child","女":"woman","男":"man",
  "老":"old","幼":"young","朋":"friend","敌":"enemy",
  "學":"study","問":"ask","寫":"write","讀":"read","見":"see",
  "聽":"hear","說":"speak","想":"think","愛":"love","恨":"hate",
  "喜":"happy","怒":"angry","哀":"sad","樂":"joy","怕":"fear",
  "龍":"dragon","鳳":"phoenix","虎":"tiger","獅":"lion","象":"elephant",
  "貓":"cat","狗":"dog","牛":"ox","羊":"sheep","馬":"horse",
  "雞":"chicken","鴨":"duck","鵝":"goose","鳥":"bird","魚":"fish",
  "蛙":"frog","蛇":"snake","蟲":"insect","蝶":"butterfly","蜂":"bee",
  "舟":"boat","車":"car","飛":"fly","行":"go","走":"walk",
  "跑":"run","跳":"jump","游":"swim","騎":"ride","駕":"drive",
  "出":"out","入":"enter","進":"enter","退":"retreat",
  "開":"open","關":"close","來":"come","去":"go",
  "上":"up","下":"down","左":"left","右":"right",
  "高":"tall","低":"low","遠":"far","近":"near",
  "多":"many","少":"few","大":"big","小":"small",
  "一":"1","二":"2","三":"3","四":"4","五":"5",
  "六":"6","七":"7","八":"8","九":"9","十":"10",
  "百":"100","千":"1000","万":"10000","亿":"100 million",
  "年":"year","月":"month","日":"day","时":"hour","分":"minute",
  "今天":"today","昨天":"yesterday","明天":"tomorrow",
  "春":"spring","夏":"summer","秋":"autumn","冬":"winter",
  "东":"east","南":"south","西":"west","北":"north",
  "金":"gold","木":"wood","水":"water","火":"fire","土":"earth",
  "风":"wind","云":"cloud","雨":"rain","雪":"snow","电":"electricity",
  "天":"sky","地":"earth","山":"mountain","河":"river","海":"sea",
  "湖":"lake","岛":"island","星":"star","月":"moon","日":"sun",
  "花":"flower","草":"grass","树":"tree","叶":"leaf","果":"fruit",
  "书":"book","笔":"pen","纸":"paper","刀":"knife","剑":"sword",
  "钱":"money","金":"gold","银":"silver","铜":"copper","铁":"iron",
  "王":"king","主":"master","臣":"minister","民":"people",
  "军":"army","兵":"soldier","战":"war","和":"peace",
  "国":"country","家":"home","城":"city","村":"village",
  "路":"road","桥":"bridge","門":"gate","窗":"window",
  "桌":"table","椅":"chair","床":"bed","窗":"window",
  "灯":"lamp","机":"machine","车":"vehicle",
  "手":"hand","机":"machine","电":"electricity","话":"speech",
  "网":"net","信":"letter","息":"breath",
  "计":"calculate","算":"calculate","机":"machine",
  "科":"science","学":"study","校":"school",
  "医":"medicine","院":"courtyard","药":"medicine",
  "身":"body","体":"body","健":"health","康":"peace",
  "心":"heart","理":"reason","情":"feeling","感":"feel",
  "爱":"love","恨":"hate","思":"think","想":"think",
  // Some missing radicals from part6/7
  "钅":"metal","镸":"long","镹":"long","長":"long",
  "門":"door","闩":"bolt","闫":"surname Yan","闱":"door",
  "闳":"wide","闵":"surname Min","闶":"high door","闼":"door",
  "闾":"gate","闿":"open","阇":"watchtower","阉":"eunuch",
  "阏":"block","阒":"quiet","阑":"railing","阕":"end",
  "阖":"close","阗":"fill","阘":"door","阛":"market",
  "阞":"vein",
  // for elements
  "钣":"sheet metal","钤":"seal","钫":"francium","钬":"holmium",
  "钭":"surname","钯":"palladium","钺":"battle-axe","钼":"molybdenum",
  "钽":"tantalum","钿":"ornament","铆":"rivet","铈":"cerium",
  "铉":"stick","铊":"thallium","铋":"bismuth","铌":"niobium",
  "铍":"beryllium","铑":"rhodium","铒":"erbium","铕":"europium",
  "铖":"surname","铗":"pincers","铙":"cymbal","铬":"chromium",
  "铞":"padlock","铟":"indium","铥":"thulium","铪":"hafnium",
  "铯":"cesium","铷":"rubidium","铹":"lawrencium","铼":"rhenium",
  "铽":"terbium","锇":"osmium","锊":"ancient weight","锒":"chain",
  "锘":"nobelium","锛":"adze","锝":"technetium","锞":"ingot",
  "锠":"spear","锪":"scraper","锬":"lance","锱":"weight",
  "锴":"high quality iron","锵":"scissors","锷":"blade","锸":"spade",
  "锹":"shovel","锺":"bell","锻":"forge","锽":"bell","锾":"weight",
  "锿":"einsteinium","镀":"plating","镁":"magnesium","镂":"engrave",
  "镐":"pickaxe","镒":"weight","镓":"gallium","镔":"fine steel",
  "镗":"boring tool","镚":"small coin","镣":"fetters","镤":"protactinium",
  "镥":"lutetium","镨":"praseodymium","镩":"ice skate","镫":"stirrup",
  "镱":"ytterbium","镳":"bit","镵":"sharp","镶":"inlay",
  "镼":"bracelet","镽":"chain","镾":"full","长":"long",
  // Animal-related
  "猁":"lynx","猇":"roar","猊":"lion","猋":"whirlwind",
  "猌":"dog","猒":"satiated","猘":"mad dog","猡":"fierce",
  "猢":"monkey","猤":"fierce","猬":"hedgehog","猭":"wild dog",
  "猯":"badger","猰":"dog","猱":"monkey","猲":"pig dog",
  "猵":"otter","猷":"plan","猸":"civet","猹":"badger",
  "猺":"jackal","猼":"leopard","猽":"dark dog","獀":"hunting dog",
  "獉":"wild boar","獒":"mastiff","獓":"wild dog","獠":"hunt",
  "獦":"ape","獬":"unicorn","獭":"otter","獯":"tribe",
  "獴":"mongoose","獿":"monkey","獾":"badger","犸":"mammoth",
  "犼":"mythical beast",
  // extra
  "夊":"walk slowly","夊":"walk slowly","夞":"slow",
};